#pragma once

#include "FileDock.Support.h"

namespace ksword::ui::file_dock
{
class FileDetailDialog final : public QDialog
    {
    public:
        explicit FileDetailDialog(
            const QString& filePath,
            QWidget* parent = nullptr,
            const QString& initialTabKey = QString());

        explicit FileDetailDialog(
            const QStringList& filePaths,
            QWidget* parent = nullptr,
            const QString& initialTabKey = QString());

        ~FileDetailDialog() override;

    protected:
        void closeEvent(QCloseEvent* event) override;

        void changeEvent(QEvent* event) override;

    private:
        void applyThemeStyle();

        struct HashCalculationResult
        {
            bool openOk = false;       // openOk: Whether the file opened successfully.
            bool cancelled = false;    // cancelled: Whether the user cancelled.
            qint64 totalBytes = 0;     // totalBytes: Total file size.
            qint64 readBytes = 0;      // readBytes: Actual bytes read.
            qint64 elapsedMs = 0;      // elapsedMs: Elapsed time in milliseconds.
            QString sha256Text;        // sha256Text: hexadecimal SHA256.
            QFileDevice::FileError fileError = QFileDevice::NoError; // fileError: Stable error code independent of system UI language.
        };

        struct PrintableStringsPreview
        {
            QString sourcePrefixText;  // sourcePrefixText: Description generated by the application that requires translation.
            QString rawStringText;     // rawStringText: Raw string extracted from the file; do not translate.
        };

        struct FileMetadataSnapshot
        {
            bool ok = false;                 // ok: Whether the target was successfully opened and FileBasicInfo was read.
            DWORD win32Error = ERROR_SUCCESS; // win32Error: Win32 error code for the failed step.
            FILE_BASIC_INFO basicInfo{};     // basicInfo: Snapshot of four timestamps and full attribute flags.
            bool identityAvailable = false;  // identityAvailable: Whether the volume serial number and file index are available for verification.
            DWORD volumeSerialNumber = 0U;   // volumeSerialNumber: Identity of the volume containing the file.
            std::uint64_t fileIndex = 0U;    // fileIndex: Stable file identity within the same volume.
        };

        struct FileMetadataUpdateRequest
        {
            std::array<bool, 4> updateTime{};       // updateTime: Determines whether to write each corresponding time entry.
            std::array<LARGE_INTEGER, 4> timeValue{}; // timeValue: FILETIME 100ns values converted from local edit values.
            bool updateAttributes = false;         // updateAttributes: Whether the editable attribute flags have changed.
            DWORD editableAttributes = 0U;         // editableAttributes: Six bit flags for editable attributes.
            bool validateIdentity = false;         // validateIdentity: Whether the initial file identity must match before writing.
            DWORD expectedVolumeSerialNumber = 0U; // expectedVolumeSerialNumber: Initial volume identity.
            std::uint64_t expectedFileIndex = 0U;  // expectedFileIndex: Initial file index.
        };

        struct FileMetadataUpdateResult
        {
            bool ok = false;                  // ok: Whether both write call and back-read succeeded.
            bool verificationMatched = false; // verificationMatched: Whether the re-read value matches the request.
            DWORD win32Error = ERROR_SUCCESS; // win32Error: Retains a stable error code on failure.
            FileMetadataSnapshot snapshot;   // snapshot: The actual FileBasicInfo written after the operation.
        };

        static const std::array<DWORD, 6>& editableFileAttributeMasks();

        static DWORD editableFileAttributeMask();

        static HANDLE openFileMetadataHandle(
            const QString& filePath,
            const DWORD desiredAccess,
            DWORD& errorOut);

        static FileMetadataSnapshot readFileMetadataSnapshot(
            const QString& filePath,
            const DWORD desiredAccess = FILE_READ_ATTRIBUTES);

        static QDateTime fileMetadataTimeToLocalDateTime(const LARGE_INTEGER timeValue);

        static LARGE_INTEGER localDateTimeToFileMetadataTime(const QDateTime& dateTime);

        static std::array<LARGE_INTEGER, 4> fileMetadataTimes(const FILE_BASIC_INFO& basicInfo);

        static FileMetadataUpdateResult writeFileMetadata(
            const QString& filePath,
            const FileMetadataUpdateRequest& request);

        static QString formatHexValue(const quint64 value, const int digitCount);

        static QString formatHex64(const std::uint64_t value);

        static QString formatNtStatus(const long status);

        static QString formatAuditBool(const bool value);

        static QString friendlyFileIoMessage(const std::string& messageText);

        static QString fixedWideAuditText(const wchar_t* const textBuffer, const std::size_t maxChars);

        template <std::size_t CharCount>
        static QString fixedWideAuditText(const wchar_t (&textBuffer)[CharCount])
        {
            // Purpose: Fixed array overload so callers do not need to repeatedly write std::size.
            // Returns: safe display text for a fixed UTF-16 field.
            return fixedWideAuditText(textBuffer, CharCount);
        }

        template <typename AuditResult>
        static QString formatAuditResultHeader(
            const QString& titleText,
            const AuditResult& result,
            const std::uint32_t responseFlags,
            const bool explicitTruncated)
        {
            // Purpose: Generate a unified summary header for all R0 file/storage audit wrappers.
            // Input: titleText is the audit block title, result is the structure returned by ArkDriverClient.
            // Returns: A multi-line text containing IO, total/returned, truncated status, and a human-readable explanation.
            const bool kCountTruncated = result.returnedCount < result.totalCount;
            const bool kTruncated = explicitTruncated || kCountTruncated;
            QString content;
            content += QStringLiteral("[%1]\n").arg(titleText);
            content += QStringLiteral("IO状态: %1\n").arg(result.io.ok ? QStringLiteral("OK") : QStringLiteral("FAIL"));
            content += QStringLiteral("unsupported: %1\n").arg(formatAuditBool(result.unsupported));
            content += QStringLiteral("version: %1\n").arg(result.version);
            content += QStringLiteral("status: %1\n").arg(result.status);
            content += QStringLiteral("totalCount: %1\n").arg(result.totalCount);
            content += QStringLiteral("returnedCount: %1\n").arg(result.returnedCount);
            content += QStringLiteral("truncated: %1\n").arg(formatAuditBool(kTruncated));
            content += QStringLiteral("entrySize/rowSize: %1\n").arg(result.entrySize);
            content += QStringLiteral("responseFlags: 0x%1\n").arg(responseFlags, 8, 16, QChar('0')).toUpper();
            content += QStringLiteral("lastStatus: %1\n").arg(formatNtStatus(result.lastStatus));
            content += QStringLiteral("win32Error: %1\n").arg(result.io.win32Error);
            content += QStringLiteral("bytesReturned: %1\n").arg(result.io.bytesReturned);
            content += QStringLiteral("说明: %1\n").arg(friendlyFileIoMessage(result.io.message));
            return content;
        }

        static QString formatMinifilterInventoryRows(const ksword::ark::MinifilterInventoryResult& result);

        static QString formatVolumeStackAuditRows(const ksword::ark::StorageVolumeStackAuditResult& result);

        static QString formatBitlockerFveAuditRows(const ksword::ark::StorageBitlockerFveAuditResult& result);

        static QString formatMountMgrMappingAuditRows(const ksword::ark::StorageMountMgrMappingAuditResult& result);

        static QString formatFilesystemIntegrityAuditRows(const ksword::ark::StorageFilesystemIntegrityAuditResult& result);

        static QString fileTimeToText(const std::int64_t fileTimeValue);

        static QString fileAttributesToText(const std::uint32_t attributes);

        static QString fileInfoStatusText(const std::uint32_t status);

        static ksword::ark::FileInfoQueryResult queryR0FileInfo(const QFileInfo& info, const QString& ntPathText);

        QString formatR0FileInfoText(const ksword::ark::FileInfoQueryResult& result) const;

        // formatFileSizeText:
        // - Display file size with both a human-readable unit and the exact byte count, avoiding a raw number that requires the user to count digits;
        // - No conversion value for sizes under 1KB; display only bytes.
        // Parameter sizeBytes: size in bytes.
        // Returns: e.g., "1.21 MB (1268736 bytes)".
        static QString formatFileSizeText(const qulonglong sizeBytes);

        // fileAttributeFlagRows:
        // - Input attributes: FILE_ATTRIBUTE_* bit set;
        // - Processing: Expand only set attributes, providing the Win32 constant name and Chinese meaning for each bit.
        //   Previously, these bits were compressed into an A|B|C string, readable only by those who remember the constant names.
        // - Return: List of constant name/meaning pairs; returns an empty list if no bits are set, with the caller adding a description row.
        static QList<QPair<QString, QString>> fileAttributeFlagRows(const std::uint32_t attributes);

        void refreshGeneralTab();

        // syncGeneralTextView:
        // - Export the current property tree as indented text and populate the text view on the General page;
        // - The text view no longer builds a separate content copy: both views share the same translated data, preventing
        //   inconsistencies where the tree updates but the text remains stale after language switching or R0 results arrive.
        // Returns: Nothing.
        void syncGeneralTextView();

        void startHashCalculation(
            CodeEditorWidget* textEditorWidget,
            QProgressBar* progressBar,
            QPushButton* startButton,
            QPushButton* cancelButton);

        void requestHashCancel(QPushButton* cancelButton);

        struct UsageSelection
        {
            std::uint32_t processId = 0;
            std::uint64_t processCreationTime = 0;
            std::uint64_t handleValue = 0;
            QString processName;
            QString matchedTargetPath;
            bool matchedByDirectoryRule = false;
        };

        static constexpr int kUsageProcessIdRole = Qt::UserRole;
        static constexpr int kUsageProcessCreationTimeRole = Qt::UserRole + 1;
        static constexpr int kUsageHandleValueRole = Qt::UserRole + 2;
        static constexpr int kUsageMatchedTargetPathRole = Qt::UserRole + 3;
        static constexpr int kUsageDirectoryMatchRole = Qt::UserRole + 4;

        static bool readUsageSelection(QTreeWidget* table, UsageSelection& selectionOut);

        void closeSelectedUsageHandle(
            QTreeWidget* table,
            QLabel* statusLabel,
            QPushButton* refreshButton);

        void terminateSelectedUsageProcess(
            QTreeWidget* table,
            QLabel* statusLabel,
            QPushButton* refreshButton,
            const bool useKernelDriver);

        void refreshUsageTable(QTreeWidget* table, QLabel* statusLabel, QPushButton* refreshButton);

        void startR0FileInfoLoad(const QFileInfo& info, const QString& ntPathText);

        static FileSecuritySnapshot loadFileSecuritySnapshot(const QString& nativePath);

        static QString buildSecurityDeepText(const QString& nativePath);

        void populateSecurityWidgets(
            QTableWidget* aceTable,
            CodeEditorWidget* detailEditor,
            QLabel* statusLabel,
            const QString& baseContent,
            const FileSecuritySnapshot& snapshot);

        void startSecurityDeepLoad(
            QTableWidget* aceTable,
            CodeEditorWidget* detailEditor,
            QLabel* statusLabel,
            const QString& baseContent,
            const QString& nativePath);

        DWORD maskFromSecurityPreset(const int presetIndex);

        DWORD maskFromSecurityChecks(
            QCheckBox* readCheck,
            QCheckBox* writeCheck,
            QCheckBox* executeCheck,
            QCheckBox* deleteCheck,
            QCheckBox* writeDacCheck,
            QCheckBox* writeOwnerCheck);

        DWORD inheritanceFlagsFromCombo(const int inheritIndex);

        bool extractAceSidAndType(LPVOID acePointer, BYTE* aceTypeOut, PSID* sidOut);

        DWORD applySecurityAceChange(
            const QString& accountText,
            const DWORD accessMask,
            const ACCESS_MODE accessMode,
            const DWORD inheritanceFlags,
            QString& detailTextOut);

        DWORD deleteSelectedDaclAce(QTableWidget* aceTable, QString& detailTextOut);

        void startSignatureLoad(CodeEditorWidget* textEditorWidget);

        void startPeAnalysisLoad(CodeEditorWidget* textEditorWidget);

        static PrintableStringsPreview extractPrintableStringsPreview(const QString& filePath);

        void startStringsLoad(CodeEditorWidget* textEditorWidget);

        static QString dependencyRowsToClipboardText(QTableWidget* table, const bool dllOnly);

        void populateDependencyTable(QTableWidget* table, QLabel* statusLabel, const file_dock_detail::PeDependencyResult& result, const qint64 elapsedMs);

        void startDependencyLoad(QTableWidget* table, QLabel* statusLabel, CodeEditorWidget* detailEditor);

        void setMetadataEditorBusy(const bool busy);

        void applyMetadataSnapshotToEditor(const FileMetadataSnapshot& snapshot);

        static FileMetadataSnapshot metadataSnapshotForEditor(
            const ks::file::metadata::FileSnapshot& snapshot);

        void applyBatchMetadataSnapshotsToEditor(
            const QList<ks::file::metadata::FileSnapshot>& snapshots);

        void refreshMetadataEditor();

        void applyMetadataEditorChanges();

        int pendingTargetCount() const;

        bool ensurePendingPatchesForStaging();

        int pendingOperationCount() const;

        void updatePendingSaveUi();

        void resetPatchKeepingSnapshot(ks::file::metadata::TargetPatch& patch);

        void discardPendingChanges();

        static QString transactionOperationText(const QString& operation);

        void showTransactionResults(const ks::file::metadata::TransactionResult& result);

        void setTransactionBusy(const bool busy);

        void saveAllPendingChanges();

        QWidget* buildDeferredTab(const QString& lazyKey);

        void activateDeferredTab(QTabWidget* tabWidget, const int tabIndex);

        QWidget* buildGeneralTab();

        static QComboBox* buildChangeStateCombo(QWidget* parent);

        static ks::file::metadata::ChangeState changeStateFromCombo(const QComboBox* combo);

        static QByteArray parseMetadataHexText(const QString& text, bool* okOut);

        static QByteArray metadataEditorBytes(
            const QPlainTextEdit* editor,
            const QComboBox* formatCombo,
            bool* okOut);

        void refreshMetadataStreamTable(QTableWidget* table);

        void refreshMetadataEaTable(QTableWidget* table);

        QWidget* buildMetadataNameAndFilesystemPage(QWidget* parent);

        QWidget* buildMetadataShellPropertyPage(QWidget* parent);

        QWidget* buildMetadataAdsPage(QWidget* parent);

        QWidget* buildMetadataEaPage(QWidget* parent);

        QWidget* buildMetadataSecurityPage(QWidget* parent);

        QWidget* buildMetadataPeAndReparsePage(QWidget* parent);

        QWidget* buildMetadataBasicPropertiesPage(QWidget* parent);

        QTabWidget* buildMetadataEditorTabs(QWidget* parent);

        QWidget* buildMetadataTab();

        QWidget* buildReparseTab();

        QWidget* buildSecurityTab();

        QWidget* buildHashTab();

        QWidget* buildUsageTab();

        QWidget* buildFileObjectTab();

        QWidget* buildStorageTab();

        void startStorageAuditLoad(QWidget* storagePage, QWidget* placeholderReportView);

        static QString buildStorageAuditReportText(const QString& filePathText);

        QWidget* buildFilterTopologyTab();

        QWidget* buildSignatureTab();

        QWidget* buildPeTab();

        QWidget* buildDependencyTab();

        QWidget* buildStringsTab();

        QWidget* buildHexTab();

    private:
        QStringList filePaths_; // All targets corresponding to the current details window; single-file mode contains only one item.
        QString filePath_;   // Single-file target or the first item in batch mode, reused by the existing read-only analysis page.
        bool batchMode_ = false; // In multi-target mode, only provide standard summary, batch hashing, and metadata editing.
        QString initialTabKey_; // Initial tab specified by the external entry; the usage entry performs automatic scanning.
        QWidget* tabNavigation_ = nullptr; // Left navigation container for file properties.
        QTabWidget* tabWidget_ = nullptr; // Continue supporting existing pages and lazy-loading mechanisms.
        QButtonGroup* tabNavigationButtonGroup_ = nullptr; // Ensures single selection in the left navigation.
        QVector<QToolButton*> tabNavigationButtons_; // Corresponds one-to-one with tab indices, used to synchronize the selected state during page switching.
        QTreeWidget* generalPropertyTree_ = nullptr; // General page property tree; the entire tree is rebuilt during language switching or upon return from R0.
        CodeEditorWidget* generalTextEditor_ = nullptr; // General page text view; content is exported from the property tree and refreshes in sync with the tree.
        QString generalNtPathText_; // NT path reused on the general page to avoid redundant queries during language switching.
        bool generalR0Loaded_ = false; // Whether R0 file information has finished background reading.
        ksword::ark::FileInfoQueryResult generalR0Info_{}; // Preserve original R0 data for bilingual redrawing.
        std::uint64_t generalR0LoadGeneration_ = 0U; // Old R0 queries initiated before evicting metadata.
        std::array<QCheckBox*, 4> metadataTimeChecks_{}; // Individual write switches for the four timestamp fields.
        std::array<QDateTimeEdit*, 4> metadataTimeEdits_{}; // Four local time editors.
        std::array<QCheckBox*, 6> metadataAttributeChecks_{}; // Six directly toggleable attribute bits.
        std::array<bool, 6> metadataAttributeTouched_{}; // In batch mixed mode, only write attributes that the user actually toggled.
        bool metadataApplyingSnapshot_ = false; // When filling back the mixed state, do not misjudge program assignment as user modification.
        QPushButton* metadataRefreshButton_ = nullptr; // Re-read the latest FileBasicInfo.
        QPushButton* metadataApplyButton_ = nullptr; // Add base metadata changes to a unified staging transaction.
        QLabel* metadataStatusLabel_ = nullptr; // Status of read, write, and re-read verification.
        FileMetadataSnapshot metadataSnapshot_{}; // Attribute snapshot currently displayed by the editor.
        bool metadataHasSnapshot_ = false; // Prevent writing uninitialized values after a read failure.
        bool metadataEditorBusy_ = false; // Prevents duplicate reading or application.
        std::uint64_t metadataOperationGeneration_ = 0U; // Discard late background results after eviction, close, or refresh.
        QList<ks::file::metadata::TargetPatch> pendingPatches_; // Unified R3 temporary patches for each target.
        QCheckBox* backupBeforeSaveCheck_ = nullptr; // Copy the target or generate a directory metadata manifest before saving.
        QLabel* pendingChangesLabel_ = nullptr; // Pending summary in the bottom unified save bar.
        QPushButton* discardPendingButton_ = nullptr; // Discard all pending patches.
        QPushButton* saveAllButton_ = nullptr; // The only entry point that triggers file writes.
        bool transactionBusy_ = false; // Lock editing and prevent duplicate submissions during transaction execution.
        std::shared_ptr<std::atomic_bool> hashCancelRequested_; // Hash cancellation flag, shared by background thread.
        std::shared_ptr<std::atomic_bool> usageScanCancelRequested_; // File usage scan cancellation flag; set when closing the properties window.
        QProgressBar* usageScanProgressBar_ = nullptr; // Progress bar for the property page's file usage scan stage.
        bool usageScanInProgress_ = false; // Whether the property page's usage scan is still running in the background.
        bool usageRetryAfterR0Start_ = false; // R3 fallback result: whether to wait for the next successful R0 start before rescanning.
        bool usageR0StartedDuringScan_ = false; // Whether R0 started before the current R3 fallback scan completed.
        bool themeStyleApplying_ = false; // Prevent style re-entry triggered by PaletteChange.
    };
}
