#pragma once

// ============================================================
// KernelObjectDirectoryDeepWorker.h
// Purpose:
// 1) Provide an R3 Object Manager Directory recursive enumeration interface;
// 2) Use NtOpenDirectoryObject + NtQueryDirectoryObject;
// 3) Recursively process only objects where TypeName == Directory; treat other objects as leaves and return.
// ============================================================

#include <QString>

#include <cstddef>
#include <vector>

// KernelObjectDirectoryDeepEntry
// - Purpose: Stores an object record from a directory recursive enumeration.
// - Fields: cover root path, directory path, object name, type, full path, depth, status, and whether it is a directory.
struct KernelObjectDirectoryDeepEntry
{
    QString rootPath;       // rootPath: The root path for the current recursive task, e.g., "\" or "\Device".
    QString directoryPath;  // directoryPath: The directory path where the current object resides.
    QString objectName;     // objectName: the current object name; if opening the root directory fails, it can be the leaf name of the root path.
    QString objectType;     // objectType: The TypeName returned by NtQueryDirectoryObject.
    QString fullPath;       // fullPath: The complete object path formed by concatenating directoryPath and objectName.
    int depth = 0;          // depth: Recursive depth relative to rootPath; root directory children are 0.
    QString statusText;     // statusText: Enumerated status, failed NTSTATUS, or safety upper bound description.
    bool querySucceeded = false; // querySucceeded: Whether the query/open operation for this record succeeded.
    bool isDirectory = false;    // isDirectory: whether objectType is a Directory.
};

// KernelObjectDirectoryDeepOptions
// - Purpose: Control the safety boundaries for recursive enumeration to prevent UI hangs caused by anomalous object trees.
// - Caller: Generated by the Widget based on input; the Worker is responsible for further range correction.
struct KernelObjectDirectoryDeepOptions
{
    QString rootPath = QStringLiteral("\\"); // rootPath: Starting Object Manager directory.
    int maxDepth = 4;                        // maxDepth: Maximum depth for drilling down into the Directory.
    std::size_t maxEntriesPerDirectory = 4096; // maxEntriesPerDirectory: Maximum number of entries to read per directory.
    std::size_t maxTotalEntries = 50000;       // maxTotalEntries: Total output record limit.
};

// KernelObjectDirectoryDeepResult
// - Purpose: Aggregate recursive enumeration results and overall diagnostics.
// - success=false indicates fatal errors such as Nt API loading failure; individual directory access failures are still recorded in rows.
struct KernelObjectDirectoryDeepResult
{
    bool success = false;              // success: Indicates whether the task started successfully and completed the scanning process.
    QString errorText;                 // errorText: fatal error text; empty on success.
    QString normalizedRootPath;        // normalizedRootPath: Root path normalized by the Worker.
    std::size_t visitedDirectoryCount = 0; // visitedDirectoryCount: Number of directories successfully attempted to enumerate.
    std::size_t failedDirectoryCount = 0;  // failedDirectoryCount: Number of directories that failed to open or query.
    bool totalLimitReached = false;        // totalLimitReached: Whether the total entry limit has been reached.
    bool depthLimitReached = false;        // depthLimitReached: Whether the depth limit has been reached.
    bool perDirectoryLimitReached = false; // perDirectoryLimitReached: Whether the per-directory entry limit was reached.
    std::vector<KernelObjectDirectoryDeepEntry> rows; // rows: recursive enumeration output records.
};

// runKernelObjectDirectoryDeepSnapshotTask：
// - Purpose: Recursively enumerate Object Manager Directories according to options.rootPath.
// - Input options: root path and safety upper bound; the function performs conservative correction for empty paths or out-of-bounds upper bounds.
// - Processing logic: Open directory -> query entries -> record all objects -> recursively process Directory sub-items.
// - Returns: KernelObjectDirectoryDeepResult; non-fatal access failures are written to rows without throwing exceptions.
KernelObjectDirectoryDeepResult runKernelObjectDirectoryDeepSnapshotTask(
    const KernelObjectDirectoryDeepOptions& options);
