#pragma once

// ============================================================
// CodeEditorWidget.h
// Purpose:
// - Provides a reusable 'instant window code editor' component;
// - Integrate line numbers, find/replace, jump-to-line, file read/write, and bracket highlighting/matching.
// - Subsequent scenarios requiring 'Notepad-like/code editor input fields' can directly reuse this.
// ============================================================

#include <QString>
#include <QStringConverter>
#include <QWidget>

class QComboBox;
class QLabel;
class QLineEdit;
class QEvent;
class QStackedWidget;
class QToolButton;
class QVBoxLayout;
class QHBoxLayout;
class QWidget;

class CodeTextEdit;

namespace ks::ui
{
    class ReportStructuredView;

    // localizeGeneratedReport:
    // - Translate the 'audit report text generated by this program itself' line by line, following rules identical to the CodeEditorWidget read-only page:
    //   If the entire line matches a localization key, replace directly; otherwise, attempt to translate the status value after the colon in "Label: Value".
    // - Dynamic content such as paths, hashes, and addresses will not be rewritten.
    // Purpose: Reports may be inserted into a read-only text box or parsed into structured views like property trees.
    //       Both paths must share the same localization logic; otherwise, the same data reverts to English when switching views.
    // Input parameter sourceText: The untranslated original report text.
    // Returns: The report text translated line by line.
    QString localizeGeneratedReport(const QString& sourceText);
}

// CodeEditorWidget：
// - Unified text editor wrapper;
// - Provides external basic text read/write, current file path, and file encoding session access;
class CodeEditorWidget final : public QWidget
{
    Q_OBJECT

public:
    // Constructor:
    // - parent: Qt parent widget, may be null.
    explicit CodeEditorWidget(QWidget* parent = nullptr);

    // Destructor:
    // - Resources are automatically reclaimed by Qt's parent-child mechanism.
    ~CodeEditorWidget() override;

    // text：
    // - Return the current editor text content.
    QString text() const;

    // setText：
    // - Overrides setting the editor text content;
    // - Read-only mode defaults to generating reports and supports immediate language switching;
    // - Raw logs, JSON, and file/byte content must explicitly call setRawText.
    // Parameter plainText: Target text.
    void setText(const QString& plainText);

    // setRawText：
    // - Unconditionally overwrites content with the original text without translation, and does not repaint on LanguageChange.
    // - Used for user files, raw logs, API JSON, and byte ASCII views.
    void setRawText(const QString& plainText);

    // setLocalizedText：
    // - Used for generated read-only reports, not user source file content.
    // - Save the Chinese specification source text and re-render it according to the current language on LanguageChange;
    // - Standard setText exits this mode to avoid accidentally translating user-opened source code or log content.
    void setLocalizedText(const QString& sourceText);

    // setLocalizedTextWithRawSuffix：
    // - sourceText: the report prefix generated by the application that needs to be redrawn when the language is switched.
    // - rawSuffix is the original content returned by the file or system, always preserved verbatim and not translated;
    // - Supports mixed display of 'program hints + raw strings/logs'.
    void setLocalizedTextWithRawSuffix(const QString& sourceText, const QString& rawSuffix);

    // currentFilePath：
    // - Returns the current file path (empty if not saved).
    QString currentFilePath() const;

    // setCurrentFilePath：
    // - Note: External setting of current file path label.
    // Parameter filePath: file path.
    void setCurrentFilePath(const QString& filePath);

    // setReadOnly：
    // - Sets whether the editor is read-only;
    // - In read-only mode, write-related buttons and replace functionality are disabled.
    // Input readOnly: true=read-only, false=editable.
    void setReadOnly(bool readOnly);

    // isReadOnly：
    // - Returns whether the editor is currently read-only.
    bool isReadOnly() const;

    // setStructuredReportViewEnabled：
    // - Disable the built-in toggle entry for switching between 'Structured View' and 'Raw Text'.
    // - Only for pages that already have a built-in structured view (e.g., an attribute tree constructed field-by-field from an R0
    //   structure); otherwise, the same page would display two structured views, forcing the user to determine which is more accurate.
    // - Enabled by default; ordinary read-only report boxes do not need to call this.
    void setStructuredReportViewEnabled(bool enabled);

    // currentEncodingDisplayText：
    // - Returns the display text for the current file encoding (e.g., "UTF-8 BOM");
    // - Returns "Unknown" if the current content is not loaded from a file.
    QString currentEncodingDisplayText() const;

    // openLocalFile：
    // - Open local text files via programmatic API (auto-detect encoding);
    // - Does not depend on UI buttons; suitable for direct invocation by business logic code.
    // Returns: true on success, false on failure.
    bool openLocalFile(const QString& filePath);

    // openLocalFileWithEncoding：
    // - Open local text files via the program interface with a specified encoding.
    // - Used for the "reopen with other encoding" scenario.
    // Returns: true on success, false on failure.
    bool openLocalFileWithEncoding(const QString& filePath, QStringConverter::Encoding encoding);

    // reopenCurrentFileWithEncoding：
    // - Reloads the current file with the specified encoding using the current file path;
    // - Will fail directly if the current file path is empty.
    // Returns: true on success, false on failure.
    bool reopenCurrentFileWithEncoding(QStringConverter::Encoding encoding);

signals:
    // contentChanged: Notify external detail layouts that the currently visible text has changed.
    // Invocation: emitted automatically after programmatic writes, user edits, or language-switch repaints.
    // Input text: Current complete plain text of the editor; Return: Qt signal has no return value.
    void contentChanged(const QString& text);

protected:
    // changeEvent: Re-renders the generated report saved by setLocalizedText when the language is switched.
    void changeEvent(QEvent* event) override;

    // eventFilter: When the content area changes pages or size, reposition the floating switch button in the top-right corner.
    bool eventFilter(QObject* watchedObject, QEvent* eventObject) override;

private:
    // initializeUi：
    // - Creates the toolbar, find/replace panel, jump panel, editor area, and status bar.
    void initializeUi();

    // initializeConnections：
    // - Connect buttons, shortcuts, and editor state callbacks.
    void initializeConnections();

    // applyThemeStyle：
    // - Unify the style of tool buttons and input fields.
    void applyThemeStyle();

    // openFindReplacePanel：
    // - Display the Find and Replace panel;
    // - Activates the replace input box simultaneously when replaceEnabled=true.
    void openFindReplacePanel(bool replaceEnabled);

    // openGotoPanel：
    // - Display the go-to-line panel and focus the input.
    void openGotoPanel();

    // closeInlinePanels：
    // - Hide the find/replace and go-to-line panels.
    void closeInlinePanels();

    // updateStatusText：
    // - Refresh the bottom status bar text (line number, column number, length, path).
    void updateStatusText();

    // findByDirection：
    // - Performs forward/backward search (non-blocking).
    // Input parameter forward: true = search backward, false = search forward.
    // Returns: true if a match is found, false otherwise.
    bool findByDirection(bool forward);

    // replaceCurrentSelection：
    // - If the current match is found, replace it with the target text.
    void replaceCurrentSelection();

    // replaceAllMatches：
    // - Perform a full-text replacement and return the number of replacements.
    int replaceAllMatches();

    // jumpToInputLine：
    // - Navigate to the specified line via the jump panel input.
    void jumpToInputLine();

    // openTextFile：
    // - Open text files to the editor via a file picker (auto-detect encoding).
    void openTextFile();

    // loadLocalFile：
    // - Internal file loading implementation;
    // - Supports automatic encoding detection or forced decoding with a specified encoding.
    bool loadLocalFile(const QString& filePath, bool forceEncoding, QStringConverter::Encoding forcedEncoding);

    // saveTextFile：
    // - Save text to file.
    // Input forceSaveAs: true forces 'Save As', false prioritizes overwriting the current path.
    void saveTextFile(bool forceSaveAs);

    // refreshReadOnlyUiState：
    // - Update button availability and panel visibility according to the read-only state.
    void refreshReadOnlyUiState();

    // resetFileSessionMetadata：
    // - Reset the current file session metadata (encoding/BOM/line endings).
    void resetFileSessionMetadata();

    // applyStructuredAutoFormatIfNeeded：
    // - Automatically formats the text if it is recognized as JSON/XML;
    // - Returns the formatted text. If parsing fails or the text cannot be recognized, the original text is returned unchanged.
    QString applyStructuredAutoFormatIfNeeded(const QString& inputText, QString* detectedKindOut = nullptr) const;

    // positionStructuredSwitch：
    // - Attach the floating switch dropdown to the top-right of the content area;
    // - The control is not added to any layout; its size is determined by its own sizeHint, with an additional right margin to avoid the currently visible vertical scrollbar on the current page.
    void positionStructuredSwitch();

    // updateStructuredReportView：
    // - When the current content is a read-only report and can be parsed into a structure, display the structure view toggle button and switch to the page based on the user's last selection.
    // - Hide the entry point and force a return to plain text when the content lacks structure (logs, raw data, user files).
    // - Driven uniformly by text changes, overriding setText, setRawText, setLocalizedText, and language-switch repaints.
    void updateStructuredReportView();

private:
    // m_rootLayout: Root layout.
    QVBoxLayout* rootLayout_ = nullptr;

    // m_toolbarLayout: Layout for top-level shortcut action buttons.
    QHBoxLayout* toolbarLayout_ = nullptr;

    // m_toolbarWidget: The top toolbar container.
    QWidget* toolbarWidget_ = nullptr;

    // m_newButton: Button to create new text.
    QToolButton* newButton_ = nullptr;

    // m_openButton: Open text button.
    QToolButton* openButton_ = nullptr;

    // m_saveButton: Save text button.
    QToolButton* saveButton_ = nullptr;

    // m_saveAsButton: Save As button.
    QToolButton* saveAsButton_ = nullptr;

    // m_undoButton: Undo button.
    QToolButton* undoButton_ = nullptr;

    // m_redoButton: Redo button.
    QToolButton* redoButton_ = nullptr;

    // m_cutButton: Cut button.
    QToolButton* cutButton_ = nullptr;

    // m_copyButton: Copy button.
    QToolButton* copyButton_ = nullptr;

    // m_pasteButton: Paste button.
    QToolButton* pasteButton_ = nullptr;

    // m_findButton: Open find panel button.
    QToolButton* findButton_ = nullptr;

    // m_replaceButton: Button to open the replace panel.
    QToolButton* replaceButton_ = nullptr;

    // m_gotoButton: Open go-to panel button.
    QToolButton* gotoButton_ = nullptr;

    // m_wrapButton: Toggle auto-wrap button.
    QToolButton* wrapButton_ = nullptr;

    // m_findPanel: Find and replace panel.
    QWidget* findPanel_ = nullptr;

    // m_findLayout: Find and replace panel layout.
    QHBoxLayout* findLayout_ = nullptr;

    // m_findEdit: Find input box.
    QLineEdit* findEdit_ = nullptr;

    // m_replaceEdit: Replace input box.
    QLineEdit* replaceEdit_ = nullptr;

    // m_findPrevButton: Find Previous button.
    QToolButton* findPrevButton_ = nullptr;

    // m_findNextButton: Find Next button.
    QToolButton* findNextButton_ = nullptr;

    // m_replaceOneButton: Replace current match button.
    QToolButton* replaceOneButton_ = nullptr;

    // m_replaceAllButton: Replace All button.
    QToolButton* replaceAllButton_ = nullptr;

    // m_findCloseButton: Button to close the find panel.
    QToolButton* findCloseButton_ = nullptr;

    // m_gotoPanel: Go-to-line panel.
    QWidget* gotoPanel_ = nullptr;

    // m_gotoLayout: Go-to-line panel layout.
    QHBoxLayout* gotoLayout_ = nullptr;

    // m_gotoLineEdit: Go-to line input box.
    QLineEdit* gotoLineEdit_ = nullptr;

    // m_gotoApplyButton: Go to Apply button.
    QToolButton* gotoApplyButton_ = nullptr;

    // m_gotoCloseButton: Button to close the goto panel.
    QToolButton* gotoCloseButton_ = nullptr;

    // m_structuredCombo: Dropdown to switch between structured view and raw text (visible only when parsing is supported for read-only reports).
    QComboBox* structuredCombo_ = nullptr;

    // m_viewStack: Container for switching between the plain text editor and the structured view.
    QStackedWidget* viewStack_ = nullptr;

    // m_structuredView: Structured presentation of the current content.
    ks::ui::ReportStructuredView* structuredView_ = nullptr;

    // m_editor: Core code editor (line numbers + bracket highlighting).
    CodeTextEdit* editor_ = nullptr;

    // m_statusLabel: Bottom status information label.
    QLabel* statusLabel_ = nullptr;

    // m_currentFilePath: Current file path (used for save overwrite).
    QString currentFilePath_;

    // m_localizedSourceText: Chinese standard source report saved by setLocalizedText.
    QString localizedSourceText_;

    // m_localizedRawSuffix: Original suffix that must be preserved verbatim and not translated in mixed reports.
    QString localizedRawSuffix_;

    // m_localizedTextActive: When true, LanguageChange re-renders the generated report body.
    bool localizedTextActive_ = false;

    // m_fileEncoding: Current file encoding (valid only after file loading).
    QStringConverter::Encoding fileEncoding_ = QStringConverter::Utf8;

    // m_fileHasBom: Whether the current file has a BOM.
    bool fileHasBom_ = false;

    // m_fileLineEnding: The dominant line ending style of the current file ("\r\n" / "\n" / "\r").
    QString fileLineEnding_ = QStringLiteral("\n");

    // m_fileSessionAvailable: Whether current encoding metadata is valid and displayable.
    bool fileSessionAvailable_ = false;

    // m_replaceEnabled: Flag indicating whether the replace control is currently shown in the find panel.
    bool replaceEnabled_ = false;

    // m_readOnlyMode: Flag indicating whether the current mode is read-only.
    bool readOnlyMode_ = false;

    // m_structuredViewEnabled: Whether to allow the built-in structured view toggle entry.
    bool structuredViewEnabled_ = true;

    // m_destroying: Marks the component is being destroyed.
    // - Input/Processing: Set to true in the destructor; all delayed signal callbacks check this before refreshing the UI;
    // - Return behavior: No return value; used to prevent accessing released child controls during mainWindow's exit destruction chain.
    bool destroying_ = false;
};
