#include "ReportStructuredView.h"

// ============================================================
// ReportStructuredView.cpp
// Purpose:
// - Implement parsing of report plain text into structured block models;
// - Render property tables, group trees, data grids, and monospace code blocks separately in block form.
//
// Note on trade-offs:
// - The report text parsed here is generated by this program itself; its format is guaranteed by upstream generated code, not external input;
// - A more thorough approach would have each collection page directly produce structured data, but that requires modifying dozens of forensic logic points.
//   Parsing at the presentation layer allows all detail views to immediately move away from plain text boxes without risking corruption of forensic results.
// - If the condition fails, fall back to plain text; better to have no structure than to forcibly split logs and raw data into tables.
// ============================================================

#include "../Theme.h"
#include "../internationalization/LanguageManager.h"

#include <QAbstractItemModel>
#include <QAbstractItemView>
#include <QAction>
#include <QApplication>
#include <QClipboard>
#include <QEvent>
#include <QFontDatabase>
#include <QFontMetrics>
#include <QFrame>
#include <QHeaderView>
#include <QLabel>
#include <QLayoutItem>
#include <QMenu>
#include <QPalette>
#include <QPlainTextEdit>
#include <QPoint>
#include <QRegularExpression>
#include <QScrollArea>
#include <QScrollBar>
#include <QShowEvent>
#include <QTableWidget>
#include <QTreeWidget>
#include <QVBoxLayout>

#include <algorithm>

namespace
{
    // kMaxFieldNameLength: Maximum number of characters in a field name.
    // Any 'colon prefix' exceeding this length is almost always a narrative sentence rather than a field name, so it is treated as a description line.
    constexpr int kMaxFieldNameLength = 48;

    // kMinTableRunRows: Number of consecutive rows with consistent column counts required to recognize an aligned table.
    // The value 3 is chosen to avoid misinterpreting two accidentally aligned lines as a table.
    constexpr int kMinTableRunRows = 3;

    // kMaxCodeBlockHeight: Maximum pixel height for monospaced code blocks; content exceeding this limit scrolls within the block.
    constexpr int kMaxCodeBlockHeight = 320;

    // scaledBlockFont purpose: Delegates to the unified public scaling rule, ensuring only one multiplier definition exists within and outside this file.
    QFont scaledBlockFont(const QFont& baseFont)
    {
        return ks::ui::scaledReportFont(baseFont);
    }

    // ParsedField: A single attribute row or a multi-column description row.
    struct ParsedField
    {
        QString name;         // name: Attribute name; stores the full sentence when describing a line.
        QString value;        // value: Attribute value; empty when describing a line.
        bool isNote = false;  // isNote: true indicates a note row spanning two columns.
    };

    // ParsedBlock: A contiguous block of the same shape in the report.
    struct ParsedBlock
    {
        enum class Kind
        {
            kFields,  // Fields: Collection of attribute rows (may include explanatory rows).
            kTable,   // Table: Homogeneous multi-column data rows.
            kCode,    // Code: Hex dump / machine code / blocks requiring preservation of original alignment.
            kNote     // Note: Standalone explanatory text.
        };

        Kind kind = Kind::kFields;
        QList<ParsedField> fields;    // fields: Fields block content.
        QList<QStringList> tableRows; // tableRows: Table block rows; the first row if a header is included.
        bool tableHasHeader = false;  // tableHasHeader: Whether the first row is a header.
        QStringList lines;            // lines: original lines of the Code / Note block.
    };

    // ParsedSection: A report group; an empty title indicates an unnamed default group.
    struct ParsedSection
    {
        QString title;
        QList<ParsedBlock> blocks;
    };

    // ParsedDocument: Parsing result of the entire report.
    struct ParsedDocument
    {
        QString title;                 // title: report first-line title (empty if no title).
        QList<ParsedSection> sections; // sections: Groups arranged in order of appearance.
        int fieldCount = 0;            // fieldCount: Total number of attribute rows.
        int tableRowCount = 0;         // tableRowCount: Total number of rows in the table data.
        int contentLineCount = 0;      // contentLineCount: Total number of non-empty lines.
        int namedSectionCount = 0;     // namedSectionCount: Number of named groups.
        bool hasNonFieldBlock = false; // hasNonFieldBlock: Whether a table or code block exists.
        bool structured = false;       // structured: Whether to provide a structured view.
    };

    // sectionTitleFrom:
    // - Input trimmedLine: report line with leading and trailing whitespace removed;
    // - Processing: Recognize four grouping formats: "[Group]", "【Group】", "=== Group ===", and "--- Group ---".
    // - Returns: The group title if matched; otherwise, an empty string.
    QString sectionTitleFrom(const QString& trimmedLine)
    {
        const qsizetype kLineLength = trimmedLine.size();
        if (kLineLength < 3 || kLineLength > 80)
        {
            return QString();
        }

        // Bracket notation: The entire line contains exactly one pair of brackets with no nesting, to avoid misinterpreting "[10:00:01] Log" as a group.
        const bool kHalfWidthBracket =
            trimmedLine.startsWith(QLatin1Char('[')) && trimmedLine.endsWith(QLatin1Char(']'));
        const bool kFullWidthBracket =
            trimmedLine.startsWith(QChar(0x3010)) && trimmedLine.endsWith(QChar(0x3011));
        if (kHalfWidthBracket || kFullWidthBracket)
        {
            const QString kInnerText = trimmedLine.mid(1, kLineLength - 2).trimmed();
            if (kInnerText.isEmpty() ||
                kInnerText.contains(QLatin1Char('[')) ||
                kInnerText.contains(QLatin1Char(']')) ||
                kInnerText.contains(QChar(0x3010)) ||
                kInnerText.contains(QChar(0x3011)))
            {
                return QString();
            }
            return kInnerText;
        }

        // Border with equals/dash: at least three identical symbols on both ends.
        for (const QChar kDecorationChar : { QLatin1Char('='), QLatin1Char('-') })
        {
            if (!trimmedLine.startsWith(QString(3, kDecorationChar)) ||
                !trimmedLine.endsWith(QString(3, kDecorationChar)))
            {
                continue;
            }
            QString innerText = trimmedLine;
            while (innerText.startsWith(kDecorationChar))
            {
                innerText.remove(0, 1);
            }
            while (innerText.endsWith(kDecorationChar))
            {
                innerText.chop(1);
            }
            innerText = innerText.trimmed();
            if (!innerText.isEmpty())
            {
                return innerText;
            }
        }
        return QString();
    }

    // splitFieldLine:
    // - Input trimmedLine: report line with leading/trailing whitespace removed; nameOut/valueOut: parsed output parameters;
    // - Processing: Only recognize the first ': ' or full-width '：'; colons in timestamps, drive letters, and NT paths are not mistaken as delimiters.
    //   If the field name contains brackets, pipes, tabs, or is too long, treat it as a narrative sentence;
    // - Returns: true if this is an attribute line.
    bool splitFieldLine(const QString& trimmedLine, QString* nameOut, QString* valueOut)
    {
        const qsizetype kHalfWidthIndex = trimmedLine.indexOf(QStringLiteral(": "));
        const qsizetype kFullWidthIndex = trimmedLine.indexOf(QChar(0xFF1A));

        qsizetype separatorIndex = -1;
        qsizetype separatorLength = 0;
        if (kHalfWidthIndex >= 0 && (kFullWidthIndex < 0 || kHalfWidthIndex < kFullWidthIndex))
        {
            separatorIndex = kHalfWidthIndex;
            separatorLength = 2;
        }
        else if (kFullWidthIndex >= 0)
        {
            separatorIndex = kFullWidthIndex;
            separatorLength = 1;
        }
        else if (trimmedLine.endsWith(QLatin1Char(':')))
        {
            // Note: "Name:" on its own line; the value may be in subsequent indented lines, so accept it as an empty field for now.
            separatorIndex = trimmedLine.size() - 1;
            separatorLength = 1;
        }

        if (separatorIndex <= 0)
        {
            return false;
        }

        const QString kFieldName = trimmedLine.left(separatorIndex).trimmed();
        if (kFieldName.isEmpty() || kFieldName.size() > kMaxFieldNameLength)
        {
            return false;
        }
        if (kFieldName.contains(QLatin1Char('[')) ||
            kFieldName.contains(QLatin1Char(']')) ||
            kFieldName.contains(QLatin1Char('|')) ||
            kFieldName.contains(QLatin1Char('\t')))
        {
            return false;
        }

        if (nameOut != nullptr)
        {
            *nameOut = kFieldName;
        }
        if (valueOut != nullptr)
        {
            *valueOut = trimmedLine.mid(separatorIndex + separatorLength).trimmed();
        }
        return true;
    }

    // machineCodeLineRegex:
    // - Returns the regular expression matching hex dump and machine code lines.
    // - Lines formatted like "0000: 41 42 43 44" or "FFFFF80542 48 8B C4 48" must preserve original alignment.
    const QRegularExpression& machineCodeLineRegex()
    {
        static const QRegularExpression kPattern(
            QStringLiteral("^[0-9A-Fa-f]{4,16}\\s*[:|h]?\\s+(?:[0-9A-Fa-f]{2}\\s+){3,}"));
        return kPattern;
    }

    // splitAlignedColumns:
    // - Input trimmedLine: Candidate table row;
    // - Processing: Split by vertical bar first; if no vertical bar exists, split by two or more consecutive spaces.
    // - Returns: The split columns; returns an empty list if fewer than two columns exist.
    QStringList splitAlignedColumns(const QString& trimmedLine)
    {
        QStringList columnTexts;
        if (trimmedLine.count(QLatin1Char('|')) >= 2)
        {
            columnTexts = trimmedLine.split(QLatin1Char('|'), Qt::SkipEmptyParts);
        }
        else
        {
            static const QRegularExpression kGapPattern(QStringLiteral("\\s{2,}"));
            columnTexts = trimmedLine.split(kGapPattern, Qt::SkipEmptyParts);
        }

        for (QString& columnText : columnTexts)
        {
            columnText = columnText.trimmed();
        }
        columnTexts.removeAll(QString());
        return columnTexts.size() >= 2 ? columnTexts : QStringList();
    }

    // looksLikeTableHeader:
    // - Input columnTexts: candidate table header columns;
    // - Processing: Table header columns should not contain addresses, pure numbers, or colon assignments.
    // - Returns: true indicates that this row resembles a table header rather than a data row.
    bool looksLikeTableHeader(const QStringList& columnTexts)
    {
        for (const QString& columnText : columnTexts)
        {
            if (columnText.contains(QLatin1Char(':')))
            {
                return false;
            }
            bool numericConversionOk = false;
            columnText.toLongLong(&numericConversionOk);
            if (numericConversionOk || columnText.startsWith(QStringLiteral("0x"), Qt::CaseInsensitive))
            {
                return false;
            }
        }
        return true;
    }

    // appendBlock: Merges the collected block into the current group; discards empty blocks directly.
    void appendBlock(ParsedSection& section, ParsedBlock& block)
    {
        const bool kBlockEmpty =
            block.fields.isEmpty() && block.tableRows.isEmpty() && block.lines.isEmpty();
        if (!kBlockEmpty)
        {
            section.blocks.append(block);
        }
        block = ParsedBlock();
    }

    // parseReport:
    // - Input reportText: Localized report plain text;
    // - Processing: classify line by line into group headers, attribute lines, table rows, machine code lines, and description lines;
    //   merge consecutive lines of the same type into blocks; finally, determine if structuring is worthwhile based on field density;
    // - Returns: Complete block model.
    ParsedDocument parseReport(const QString& reportText)
    {
        ParsedDocument document;

        // JSON/XML originals have their own formatting channels; never split into attribute lines here.
        const QString kLeadingText = reportText.trimmed();
        if (kLeadingText.startsWith(QLatin1Char('{')) || kLeadingText.startsWith(QLatin1Char('<')))
        {
            return document;
        }

        const QStringList kReportLines = reportText.split(QLatin1Char('\n'));

        // Pre-scan: mark table rows with consistent column counts across 'kMinTableRunRows' or more consecutive lines.
        QList<QStringList> lineColumns;
        lineColumns.reserve(kReportLines.size());
        for (const QString& reportLine : kReportLines)
        {
            const QString kTrimmedLine = reportLine.trimmed();
            QStringList columnTexts;
            if (!kTrimmedLine.isEmpty() &&
                sectionTitleFrom(kTrimmedLine).isEmpty() &&
                !machineCodeLineRegex().match(kTrimmedLine).hasMatch() &&
                !splitFieldLine(kTrimmedLine, nullptr, nullptr))
            {
                columnTexts = splitAlignedColumns(kTrimmedLine);
            }
            lineColumns.append(columnTexts);
        }

        QList<bool> isTableLine;
        isTableLine.fill(false, static_cast<int>(kReportLines.size()));
        for (int lineIndex = 0; lineIndex < lineColumns.size();)
        {
            const int kColumnCount = lineColumns.at(lineIndex).size();
            if (kColumnCount < 2)
            {
                ++lineIndex;
                continue;
            }

            int runEndIndex = lineIndex;
            while (runEndIndex < lineColumns.size() &&
                lineColumns.at(runEndIndex).size() == kColumnCount)
            {
                ++runEndIndex;
            }
            if (runEndIndex - lineIndex >= kMinTableRunRows)
            {
                for (int markIndex = lineIndex; markIndex < runEndIndex; ++markIndex)
                {
                    isTableLine[markIndex] = true;
                }
            }
            lineIndex = runEndIndex;
        }

        ParsedSection currentSection;
        ParsedBlock currentBlock;
        bool documentTitleResolved = false;
        QString pendingLeadingNote;

        // flushSection: End the current group and write to the document.
        auto flushSection = [&document, &currentSection, &currentBlock]()
            {
                appendBlock(currentSection, currentBlock);
                if (!currentSection.blocks.isEmpty() || !currentSection.title.isEmpty())
                {
                    document.sections.append(currentSection);
                }
                currentSection = ParsedSection();
            };

        // adoptPendingTitle: If the first line note is followed by body content, that line is the report title.
        // All four main text branches must call this; otherwise, the pending title will leak to the next section and be inserted as a regular note in the wrong position.
        auto adoptPendingTitle = [&document, &pendingLeadingNote]()
            {
                if (!pendingLeadingNote.isEmpty() && document.title.isEmpty())
                {
                    document.title = pendingLeadingNote;
                }
                pendingLeadingNote.clear();
            };

        for (int lineIndex = 0; lineIndex < kReportLines.size(); ++lineIndex)
        {
            const QString kTrimmedLine = kReportLines.at(lineIndex).trimmed();
            if (kTrimmedLine.isEmpty())
            {
                // Empty lines only split blocks, not groups: empty lines in reports primarily separate field clusters.
                appendBlock(currentSection, currentBlock);
                continue;
            }
            ++document.contentLineCount;

            const QString kSectionTitle = sectionTitleFrom(kTrimmedLine);
            if (!kSectionTitle.isEmpty())
            {
                adoptPendingTitle();
                flushSection();
                currentSection.title = kSectionTitle;
                ++document.namedSectionCount;
                documentTitleResolved = true;
                continue;
            }

            if (isTableLine.at(lineIndex))
            {
                adoptPendingTitle();
                // Aligned blocks with different column counts must be split: merging them into a single table would silently drop the extra columns in the latter block.
                const bool kColumnCountChanged =
                    currentBlock.kind == ParsedBlock::Kind::kTable &&
                    !currentBlock.tableRows.isEmpty() &&
                    currentBlock.tableRows.constLast().size() != lineColumns.at(lineIndex).size();
                if (currentBlock.kind != ParsedBlock::Kind::kTable || kColumnCountChanged)
                {
                    appendBlock(currentSection, currentBlock);
                    currentBlock.kind = ParsedBlock::Kind::kTable;
                    currentBlock.tableHasHeader = looksLikeTableHeader(lineColumns.at(lineIndex));
                }
                currentBlock.tableRows.append(lineColumns.at(lineIndex));
                ++document.tableRowCount;
                document.hasNonFieldBlock = true;
                documentTitleResolved = true;
                continue;
            }

            if (machineCodeLineRegex().match(kTrimmedLine).hasMatch())
            {
                adoptPendingTitle();
                if (currentBlock.kind != ParsedBlock::Kind::kCode)
                {
                    appendBlock(currentSection, currentBlock);
                    currentBlock.kind = ParsedBlock::Kind::kCode;
                }
                // Code blocks retain original lines rather than trimmed results, as indentation itself carries information.
                currentBlock.lines.append(kReportLines.at(lineIndex));
                document.hasNonFieldBlock = true;
                documentTitleResolved = true;
                continue;
            }

            QString fieldName;
            QString fieldValue;
            if (splitFieldLine(kTrimmedLine, &fieldName, &fieldValue))
            {
                adoptPendingTitle();
                if (currentBlock.kind != ParsedBlock::Kind::kFields)
                {
                    appendBlock(currentSection, currentBlock);
                    currentBlock.kind = ParsedBlock::Kind::kFields;
                }
                currentBlock.fields.append(ParsedField{ fieldName, fieldValue, false });
                ++document.fieldCount;
                documentTitleResolved = true;
                continue;
            }

            if (!documentTitleResolved && document.title.isEmpty() && pendingLeadingNote.isEmpty())
            {
                // The report's first line is often a title; suspend it temporarily and wait for the next line to confirm it is indeed followed by fields.
                pendingLeadingNote = kTrimmedLine;
                continue;
            }

            if (!pendingLeadingNote.isEmpty())
            {
                // If the first line is followed by a note, it is not a heading; treat it as a regular note and append to the body.
                appendBlock(currentSection, currentBlock);
                currentBlock.kind = ParsedBlock::Kind::kNote;
                currentBlock.lines.append(pendingLeadingNote);
                pendingLeadingNote.clear();
            }

            if (currentBlock.kind == ParsedBlock::Kind::kFields && !currentBlock.fields.isEmpty())
            {
                // Note: Comments between fields remain in the same attribute table and display across columns to avoid splitting a field cluster into two parts.
                currentBlock.fields.append(ParsedField{ kTrimmedLine, QString(), true });
                continue;
            }

            if (currentBlock.kind != ParsedBlock::Kind::kNote)
            {
                appendBlock(currentSection, currentBlock);
                currentBlock.kind = ParsedBlock::Kind::kNote;
            }
            currentBlock.lines.append(kTrimmedLine);
        }

        if (!pendingLeadingNote.isEmpty())
        {
            // The entire text is a single line with no fields or subsequent content; handle it according to the specification.
            appendBlock(currentSection, currentBlock);
            currentBlock.kind = ParsedBlock::Kind::kNote;
            currentBlock.lines.append(pendingLeadingNote);
        }
        flushSection();

        // Structured-content detection: fall back to plain text instead of forcing logs or prose into a property table.
        const bool kFieldDense =
            document.fieldCount >= 3 &&
            document.fieldCount * 2 >= document.contentLineCount;
        const bool kGroupedFields =
            document.namedSectionCount >= 2 && document.fieldCount >= 2;
        const bool kTableRich = document.tableRowCount >= kMinTableRunRows;
        document.structured = kFieldDense || kGroupedFields || kTableRich;
        return document;
    }

    // fixedFont: Returns a fixed-width font for addresses, hashes, and machine codes.
    // Scale up by kBlockFontScale as well: scaling only the body text would make addresses in the same line appear shorter than labels.
    QFont fixedFont()
    {
        return scaledBlockFont(QFontDatabase::systemFont(QFontDatabase::FixedFont));
    }

    // valueLooksMonospace:
    // - Input valueText: attribute value;
    // - Return: true indicates the value is an address, hash, or pure hexadecimal, suitable for monospace display.
    bool valueLooksMonospace(const QString& valueText)
    {
        if (valueText.size() < 6)
        {
            return false;
        }
        if (valueText.startsWith(QStringLiteral("0x"), Qt::CaseInsensitive))
        {
            return true;
        }
        for (const QChar kValueChar : valueText)
        {
            const bool kHexDigit =
                (kValueChar >= QLatin1Char('0') && kValueChar <= QLatin1Char('9')) ||
                (kValueChar >= QLatin1Char('a') && kValueChar <= QLatin1Char('f')) ||
                (kValueChar >= QLatin1Char('A') && kValueChar <= QLatin1Char('F'));
            if (!kHexDigit && kValueChar != QLatin1Char(' '))
            {
                return false;
            }
        }
        return true;
    }

    // valueStatusColor:
    // - Input valueText: attribute value; colorOut: matched semantic color output;
    // - Processing: Determine 'Normal/Warning/Risk' based on bilingual keywords; only accept terms with clear overall semantics.
    // - Return: true indicates the value has a semantic color.
    bool valueStatusColor(const QString& valueText, QColor* colorOut)
    {
        if (valueText.isEmpty() || valueText.size() > 64)
        {
            return false;
        }

        static const QStringList kErrorKeywords = {
            QStringLiteral("失败"), QStringLiteral("无效"), QStringLiteral("异常"),
            QStringLiteral("篡改"), QStringLiteral("风险"), QStringLiteral("错误"),
            QStringLiteral("拒绝"), QStringLiteral("命中"), QStringLiteral("未签名"),
            QStringLiteral("failed"), QStringLiteral("invalid"), QStringLiteral("error"),
            QStringLiteral("denied"), QStringLiteral("tampered"), QStringLiteral("unsigned")
        };
        static const QStringList kWarningKeywords = {
            QStringLiteral("未知"), QStringLiteral("不可用"), QStringLiteral("降级"),
            QStringLiteral("未验证"), QStringLiteral("警告"), QStringLiteral("跳过"),
            QStringLiteral("unknown"), QStringLiteral("unavailable"), QStringLiteral("degraded"),
            QStringLiteral("warning"), QStringLiteral("skipped"), QStringLiteral("false")
        };
        static const QStringList kSuccessKeywords = {
            QStringLiteral("有效"), QStringLiteral("正常"), QStringLiteral("通过"),
            QStringLiteral("成功"), QStringLiteral("已验证"), QStringLiteral("已启用"),
            QStringLiteral("valid"), QStringLiteral("normal"), QStringLiteral("passed"),
            QStringLiteral("success"), QStringLiteral("verified"), QStringLiteral("enabled"),
            QStringLiteral("true")
        };

        // Check risk first, then warning, then normal: when all appear in the same sentence, the highest risk level takes precedence.
        for (const QString& keyword : kErrorKeywords)
        {
            if (valueText.contains(keyword, Qt::CaseInsensitive))
            {
                *colorOut = ksword_theme::errorColor();
                return true;
            }
        }
        for (const QString& keyword : kWarningKeywords)
        {
            if (valueText.contains(keyword, Qt::CaseInsensitive))
            {
                *colorOut = ksword_theme::warningColor();
                return true;
            }
        }
        for (const QString& keyword : kSuccessKeywords)
        {
            if (valueText.contains(keyword, Qt::CaseInsensitive))
            {
                *colorOut = ksword_theme::successColor();
                return true;
            }
        }
        return false;
    }

    // installCopyMenu:
    // - Adds a right-click copy menu to the property/data table: copy cell, copy entire row, copy all;
    // - The structured view must not be harder to forensicate than plain text; copy capability must be provided.
    void installCopyMenu(QAbstractItemView* itemView)
    {
        if (itemView == nullptr)
        {
            return;
        }

        itemView->setContextMenuPolicy(Qt::CustomContextMenu);
        QObject::connect(
            itemView,
            &QAbstractItemView::customContextMenuRequested,
            itemView,
            [itemView](const QPoint& menuPosition)
            {
                QAbstractItemModel* itemModel = itemView->model();
                if (itemModel == nullptr)
                {
                    return;
                }

                const QModelIndex kClickedIndex = itemView->indexAt(menuPosition);
                QMenu contextMenu(itemView);
                QAction* copyCellAction = contextMenu.addAction(
                    ks::i18n::displayText(QStringLiteral("复制该值")));
                QAction* copyRowAction = contextMenu.addAction(
                    ks::i18n::displayText(QStringLiteral("复制该行")));
                QAction* copyAllAction = contextMenu.addAction(
                    ks::i18n::displayText(QStringLiteral("复制全部")));
                copyCellAction->setEnabled(kClickedIndex.isValid());
                copyRowAction->setEnabled(kClickedIndex.isValid());

                // rowTextAt: Concatenate all non-empty columns in a row into 'A: B' or tab-separated text.
                auto rowTextAt = [itemModel](const QModelIndex& rowIndex) -> QString
                    {
                        QStringList columnTexts;
                        const int kColumnCount = itemModel->columnCount(rowIndex.parent());
                        for (int columnIndex = 0; columnIndex < kColumnCount; ++columnIndex)
                        {
                            const QString kCellText =
                                itemModel->index(rowIndex.row(), columnIndex, rowIndex.parent())
                                    .data(Qt::DisplayRole).toString();
                            if (!kCellText.isEmpty())
                            {
                                columnTexts << kCellText;
                            }
                        }
                        return kColumnCount == 2 && columnTexts.size() == 2
                            ? QStringLiteral("%1: %2").arg(columnTexts.at(0), columnTexts.at(1))
                            : columnTexts.join(QLatin1Char('\t'));
                    };

                const QAction* selectedAction =
                    contextMenu.exec(itemView->viewport()->mapToGlobal(menuPosition));
                if (selectedAction == nullptr)
                {
                    return;
                }

                QString clipboardText;
                if (selectedAction == copyCellAction && kClickedIndex.isValid())
                {
                    clipboardText = kClickedIndex.data(Qt::DisplayRole).toString();
                }
                else if (selectedAction == copyRowAction && kClickedIndex.isValid())
                {
                    clipboardText = rowTextAt(kClickedIndex);
                }
                else if (selectedAction == copyAllAction)
                {
                    QStringList allRowTexts;
                    // The attribute table has at most two levels; retrieving text layer by layer covers both the grouping tree and flat table forms.
                    for (int rowIndex = 0; rowIndex < itemModel->rowCount(); ++rowIndex)
                    {
                        const QModelIndex kTopIndex = itemModel->index(rowIndex, 0);
                        allRowTexts << rowTextAt(kTopIndex);
                        for (int childIndex = 0; childIndex < itemModel->rowCount(kTopIndex); ++childIndex)
                        {
                            allRowTexts << rowTextAt(itemModel->index(childIndex, 0, kTopIndex));
                        }
                    }
                    clipboardText = allRowTexts.join(QLatin1Char('\n'));
                }

                QClipboard* clipboardObject = QApplication::clipboard();
                if (clipboardObject != nullptr && !clipboardText.isEmpty())
                {
                    clipboardObject->setText(clipboardText);
                }
            });
    }

    // kPreserveCustomFontProperty: Marks that this control manages its own font.
    // After appearance settings change, mainWindow applies the application font to every QAbstractItemView.
    // Without this marker, changing the font would reset the enlarged report-view font to the default size.
    constexpr const char* kPreserveCustomFontProperty = "ksword_preserve_custom_font";

    // applyNameColumnWidth:
    // - Calculate the name column width based on the actual property name and clamp it to the available range.
    // - Do not use resizeColumnToContents: it includes the full length of multi-column description lines in column 0. A long description can
    //   expand the name column to over 1000 pixels, pushing the value column off-screen (this is how the WMI segment in GPU pages behaves).
    void applyNameColumnWidth(QTreeWidget* treeWidget)
    {
        constexpr int kMinNameColumnWidth = 140;
        constexpr int kMaxNameColumnWidth = 360;

        const QFontMetrics kNameMetrics(treeWidget->font());
        int widestNameWidth = 0;

        // The report tree has at most two levels (grouping + attribute rows); traversing layer by layer covers both flat tables and grouped trees.
        for (int topIndex = 0; topIndex < treeWidget->topLevelItemCount(); ++topIndex)
        {
            QTreeWidgetItem* topItem = treeWidget->topLevelItem(topIndex);
            if (!topItem->isFirstColumnSpanned())
            {
                widestNameWidth = std::max(widestNameWidth, kNameMetrics.horizontalAdvance(topItem->text(0)));
            }
            for (int childIndex = 0; childIndex < topItem->childCount(); ++childIndex)
            {
                QTreeWidgetItem* childItem = topItem->child(childIndex);
                if (childItem->isFirstColumnSpanned())
                {
                    continue;
                }
                widestNameWidth = std::max(
                    widestNameWidth,
                    kNameMetrics.horizontalAdvance(childItem->text(0)) + treeWidget->indentation());
            }
        }

        // Reserve extra space for expand arrows and horizontal padding; long field names are handled by ToolTip.
        const int kPaddedWidth = widestNameWidth + treeWidget->indentation() + 16;
        treeWidget->setColumnWidth(
            0, std::clamp(kPaddedWidth, kMinNameColumnWidth, kMaxNameColumnWidth));
    }

    // configurePropertyView:
    // Unified property view appearance: two columns, non-editable, no sorting, with copy menu.
    // - The order of report rows carries meaning (written in collection order), so sorting is disabled entirely.
    void configurePropertyView(QTreeWidget* treeWidget, const bool showTreeBranches)
    {
        treeWidget->setProperty(kPreserveCustomFontProperty, true);
        treeWidget->setColumnCount(2);
        treeWidget->setHeaderLabels(QStringList{
            ks::i18n::displayText(QStringLiteral("属性")),
            ks::i18n::displayText(QStringLiteral("值"))
            });
        treeWidget->setRootIsDecorated(showTreeBranches);
        treeWidget->setAlternatingRowColors(true);
        treeWidget->setSelectionBehavior(QAbstractItemView::SelectRows);
        treeWidget->setEditTriggers(QAbstractItemView::NoEditTriggers);
        treeWidget->setUniformRowHeights(true);
        treeWidget->setSortingEnabled(false);
        treeWidget->setFrameShape(QFrame::NoFrame);
        if (treeWidget->header() != nullptr)
        {
            treeWidget->header()->setStretchLastSection(true);
        }
        installCopyMenu(treeWidget);
    }

    // applyFieldItemStyle:
    // - Indicates the row spans two columns and uses secondary text color;
    // - Color attributes by semantics; use monospace font for addresses/hashes;
    // - Values are also written to the ToolTip so the full content remains visible on hover when column width truncates.
    void applyFieldItemStyle(QTreeWidgetItem* rowItem, const ParsedField& field)
    {
        if (field.isNote)
        {
            rowItem->setFirstColumnSpanned(true);
            rowItem->setForeground(0, ksword_theme::textSecondaryColor());
            rowItem->setToolTip(0, field.name);
            return;
        }

        rowItem->setToolTip(1, field.value);
        QColor statusColor;
        if (valueStatusColor(field.value, &statusColor))
        {
            rowItem->setForeground(1, statusColor);
        }
        if (valueLooksMonospace(field.value))
        {
            rowItem->setFont(1, fixedFont());
        }
    }

    // appendFieldRows: Appends all rows from a Fields block to the specified parent node in the attribute view.
    void appendFieldRows(
        QTreeWidget* treeWidget,
        QTreeWidgetItem* parentItem,
        const QList<ParsedField>& fields)
    {
        for (const ParsedField& field : fields)
        {
            QTreeWidgetItem* rowItem = parentItem != nullptr
                ? new QTreeWidgetItem(parentItem)
                : new QTreeWidgetItem(treeWidget);
            rowItem->setText(0, field.name);
            if (!field.isNote)
            {
                rowItem->setText(1, field.value);
            }
            applyFieldItemStyle(rowItem, field);
        }
    }

    // propertyViewHeightFor:
    // - Input treeWidget and visible row count;
    // - Returns: the exact height required to contain all rows, allowing the outer scrollbar to handle scrolling.
    int propertyViewHeightFor(const QTreeWidget* treeWidget, const int visibleRowCount)
    {
        const int kRowHeight = treeWidget->fontMetrics().height() + 10;
        const int kHeaderHeight =
            treeWidget->header() != nullptr ? treeWidget->header()->sizeHint().height() : 0;
        return kHeaderHeight + std::max(visibleRowCount, 1) * kRowHeight + 6;
    }
}

namespace ks::ui
{
    QFont scaledReportFont(const QFont& baseFont)
    {
        // kReportFontScale: Scaling factor for the report font relative to the default interface font size.
        // Reports require reading addresses, hashes, and paths line by line; the small font size used in the toolbar is too straining to read.
        // This is the only definition in the entire project: the page's self-built property tree also uses this, so the font size remains consistent.
        constexpr double kReportFontScale = 1.6;

        QFont scaledFont = baseFont;
        if (scaledFont.pointSizeF() > 0.0)
        {
            scaledFont.setPointSizeF(scaledFont.pointSizeF() * kReportFontScale);
            return scaledFont;
        }
        if (scaledFont.pixelSize() > 0)
        {
            scaledFont.setPixelSize(static_cast<int>(scaledFont.pixelSize() * kReportFontScale));
        }
        return scaledFont;
    }

    ReportStructuredView::ReportStructuredView(QWidget* parent)
        : QWidget(parent)
    {
        QVBoxLayout* rootLayout = new QVBoxLayout(this);
        rootLayout->setContentsMargins(0, 0, 0, 0);
        rootLayout->setSpacing(0);

        scrollArea_ = new QScrollArea(this);
        scrollArea_->setWidgetResizable(true);
        scrollArea_->setFrameShape(QFrame::NoFrame);
        // Backgrounds are handled exclusively by the global stylesheet: setting a styleSheet here would override the parent Dock's theme rules.
        scrollArea_->viewport()->setAutoFillBackground(false);

        blockHost_ = new QWidget(scrollArea_);
        blockHost_->setAutoFillBackground(false);
        // Font size is scaled only here: all block controls are descendants of m_blockHost. Qt fonts inherit along
        // the parent-child chain; calling setFont on each control individually risks missing newly added block types.
        blockHost_->setFont(scaledBlockFont(font()));
        blockLayout_ = new QVBoxLayout(blockHost_);
        blockLayout_->setContentsMargins(0, 0, 0, 0);
        blockLayout_->setSpacing(8);
        scrollArea_->setWidget(blockHost_);

        rootLayout->addWidget(scrollArea_, 1);
    }

    ReportStructuredView::~ReportStructuredView() = default;

    bool ReportStructuredView::setReportText(const QString& localizedReportText)
    {
        reportText_ = localizedReportText;
        hasStructure_ = parseReport(localizedReportText).structured;
        blocksDirty_ = true;
        if (isVisible())
        {
            rebuildBlocks();
        }
        return hasStructure_;
    }

    bool ReportStructuredView::canStructure(const QString& localizedReportText)
    {
        return parseReport(localizedReportText).structured;
    }

    bool ReportStructuredView::hasStructure() const
    {
        return hasStructure_;
    }

    int ReportStructuredView::verticalScrollBarWidth() const
    {
        if (scrollArea_ == nullptr || scrollArea_->verticalScrollBar() == nullptr)
        {
            return 0;
        }
        if (!scrollArea_->verticalScrollBar()->isVisible())
        {
            return 0;
        }
        return scrollArea_->verticalScrollBar()->width();
    }

    void ReportStructuredView::changeEvent(QEvent* event)
    {
        QWidget::changeEvent(event);
        if (event == nullptr)
        {
            return;
        }
        if (event->type() != QEvent::PaletteChange &&
            event->type() != QEvent::ApplicationPaletteChange &&
            event->type() != QEvent::FontChange)
        {
            return;
        }

        // Semantic colors and font sizes are computed based on the current theme/font and written to the block control; any change requires recalculating the entire block.
        blocksDirty_ = true;
        if (isVisible())
        {
            rebuildBlocks();
        }
    }

    void ReportStructuredView::showEvent(QShowEvent* event)
    {
        QWidget::showEvent(event);
        if (blocksDirty_)
        {
            rebuildBlocks();
        }
    }

    void ReportStructuredView::clearBlocks()
    {
        while (QLayoutItem* layoutItem = blockLayout_->takeAt(0))
        {
            if (QWidget* blockWidget = layoutItem->widget())
            {
                blockWidget->setParent(nullptr);
                blockWidget->deleteLater();
            }
            delete layoutItem;
        }
    }

    void ReportStructuredView::rebuildBlocks()
    {
        blocksDirty_ = false;
        clearBlocks();

        // Recalculate based on the current inherited font on every rebuild: global styles may not have been applied to the control at
        // construction time, and once m_blockHost has an explicit setFont, it no longer follows the parent chain, so it must be refreshed here.
        blockHost_->setFont(scaledBlockFont(font()));

        const ParsedDocument kDocument = parseReport(reportText_);
        if (!kDocument.structured)
        {
            return;
        }

        if (!kDocument.title.isEmpty())
        {
            QLabel* titleLabel = new QLabel(kDocument.title, blockHost_);
            titleLabel->setWordWrap(true);
            QFont titleFont = titleLabel->font();
            titleFont.setBold(true);
            titleLabel->setFont(titleFont);
            blockLayout_->addWidget(titleLabel);
        }

        // Form 1: The document contains only attribute fields.
        // Using a tree to fill the entire view is the most efficient in terms of controls and offers the best usability:
        // If grouping exists, make the group a collapsible top-level node; otherwise, degrade to a two-column flat table without arrows.
        if (!kDocument.hasNonFieldBlock)
        {
            QTreeWidget* propertyView = new QTreeWidget(blockHost_);
            configurePropertyView(propertyView, kDocument.namedSectionCount > 0);

            for (const ParsedSection& section : kDocument.sections)
            {
                QTreeWidgetItem* groupItem = nullptr;
                if (!section.title.isEmpty())
                {
                    groupItem = new QTreeWidgetItem(propertyView);
                    groupItem->setText(0, section.title);
                    QFont groupFont = groupItem->font(0);
                    groupFont.setBold(true);
                    groupItem->setFont(0, groupFont);
                    // Group rows are unselectable to prevent them from being copied as a single attribute.
                    groupItem->setFlags(groupItem->flags() & ~Qt::ItemIsSelectable);
                    groupItem->setExpanded(true);
                }

                for (const ParsedBlock& block : section.blocks)
                {
                    if (block.kind == ParsedBlock::Kind::kFields)
                    {
                        appendFieldRows(propertyView, groupItem, block.fields);
                        continue;
                    }
                    // The note block spans columns even in pure field documents to ensure no line of the main text is lost.
                    QList<ParsedField> noteFields;
                    noteFields.reserve(block.lines.size());
                    for (const QString& noteLine : block.lines)
                    {
                        noteFields.append(ParsedField{ noteLine, QString(), true });
                    }
                    appendFieldRows(propertyView, groupItem, noteFields);
                }
            }

            propertyView->expandAll();
            applyNameColumnWidth(propertyView);
            blockLayout_->addWidget(propertyView, 1);
            return;
        }

        // Form 2: The report contains mixed tables or machine code blocks.
        // At this point, forcing them into a single tree is not feasible; use separate controls per block, stack them vertically, and apply unified scrolling.
        for (const ParsedSection& section : kDocument.sections)
        {
            if (!section.title.isEmpty())
            {
                QLabel* sectionLabel = new QLabel(section.title, blockHost_);
                QFont sectionFont = sectionLabel->font();
                sectionFont.setBold(true);
                sectionLabel->setFont(sectionFont);
                sectionLabel->setContentsMargins(0, 6, 0, 0);
                blockLayout_->addWidget(sectionLabel);
            }

            for (const ParsedBlock& block : section.blocks)
            {
                switch (block.kind)
                {
                case ParsedBlock::Kind::kFields:
                {
                    QTreeWidget* propertyView = new QTreeWidget(blockHost_);
                    configurePropertyView(propertyView, false);
                    appendFieldRows(propertyView, nullptr, block.fields);
                    applyNameColumnWidth(propertyView);
                    propertyView->setFixedHeight(
                        propertyViewHeightFor(propertyView, static_cast<int>(block.fields.size())));
                    blockLayout_->addWidget(propertyView);
                    break;
                }
                case ParsedBlock::Kind::kTable:
                {
                    const bool kUseHeaderRow = block.tableHasHeader && block.tableRows.size() > 1;
                    const int kDataRowOffset = kUseHeaderRow ? 1 : 0;
                    const int kDataRowCount = static_cast<int>(block.tableRows.size()) - kDataRowOffset;
                    const int kColumnCount = static_cast<int>(block.tableRows.at(0).size());

                    QTableWidget* tableView = new QTableWidget(kDataRowCount, kColumnCount, blockHost_);
                    tableView->setProperty(kPreserveCustomFontProperty, true);
                    tableView->setEditTriggers(QAbstractItemView::NoEditTriggers);
                    tableView->setSelectionBehavior(QAbstractItemView::SelectRows);
                    tableView->setAlternatingRowColors(true);
                    tableView->setFrameShape(QFrame::NoFrame);
                    tableView->verticalHeader()->setVisible(false);
                    if (kUseHeaderRow)
                    {
                        tableView->setHorizontalHeaderLabels(block.tableRows.at(0));
                    }
                    else
                    {
                        tableView->horizontalHeader()->setVisible(false);
                    }

                    for (int dataRowIndex = 0; dataRowIndex < kDataRowCount; ++dataRowIndex)
                    {
                        const QStringList& rowColumns = block.tableRows.at(dataRowIndex + kDataRowOffset);
                        for (int columnIndex = 0; columnIndex < kColumnCount; ++columnIndex)
                        {
                            const QString kCellText = rowColumns.value(columnIndex);
                            QTableWidgetItem* cellItem = new QTableWidgetItem(kCellText);
                            cellItem->setToolTip(kCellText);
                            QColor statusColor;
                            if (valueStatusColor(kCellText, &statusColor))
                            {
                                cellItem->setForeground(statusColor);
                            }
                            if (valueLooksMonospace(kCellText))
                            {
                                cellItem->setFont(fixedFont());
                            }
                            tableView->setItem(dataRowIndex, columnIndex, cellItem);
                        }
                    }

                    tableView->resizeColumnsToContents();
                    tableView->horizontalHeader()->setStretchLastSection(true);
                    const int kTableRowHeight = tableView->fontMetrics().height() + 10;
                    const int kTableHeaderHeight = kUseHeaderRow
                        ? tableView->horizontalHeader()->sizeHint().height()
                        : 0;
                    tableView->setFixedHeight(
                        kTableHeaderHeight + std::max(kDataRowCount, 1) * kTableRowHeight + 6);
                    installCopyMenu(tableView);
                    blockLayout_->addWidget(tableView);
                    break;
                }
                case ParsedBlock::Kind::kCode:
                {
                    QPlainTextEdit* codeView = new QPlainTextEdit(
                        block.lines.join(QLatin1Char('\n')), blockHost_);
                    codeView->setReadOnly(true);
                    codeView->setFont(fixedFont());
                    codeView->setLineWrapMode(QPlainTextEdit::NoWrap);
                    codeView->setFrameShape(QFrame::NoFrame);
                    const int kCodeLineHeight = codeView->fontMetrics().height() + 2;
                    codeView->setFixedHeight(std::min(
                        static_cast<int>(block.lines.size()) * kCodeLineHeight + 12,
                        kMaxCodeBlockHeight));
                    blockLayout_->addWidget(codeView);
                    break;
                }
                case ParsedBlock::Kind::kNote:
                {
                    QLabel* noteLabel = new QLabel(
                        block.lines.join(QLatin1Char('\n')), blockHost_);
                    noteLabel->setWordWrap(true);
                    noteLabel->setTextInteractionFlags(Qt::TextSelectableByMouse);
                    noteLabel->setForegroundRole(QPalette::PlaceholderText);
                    blockLayout_->addWidget(noteLabel);
                    break;
                }
                }
            }
        }
        blockLayout_->addStretch(1);
    }
}
