#pragma once

// ============================================================
// ReportStructuredView.h
// Purpose:
// - Parses 'read-only detailed report plain text' generated by various audit pages in this application into a structured view.
// - Parse results are presented in blocks based on content type, rather than being forced into a single property tree:
//     Grouping fields → collapsible groups + two-column property table;
//     · No grouping fields → Tiled two-column property table (no tree arrows displayed);
//     • Isomorphic multi-column rows (vertical bars/multiple spaces alignment) → True table control;
//     • Hex dump / disassembly / continuous indented blocks → monospaced read-only code blocks;
//     Full sentence explanation → multi-column row or independent paragraph;
// - Perform only display-layer parsing; never modify the original report text, and do not participate in forensic logic.
//
// Usage:
// - CodeEditorWidget embeds this view in read-only report mode and provides a toggle entry;
// - Other scenarios requiring 'the same report with a different structured view' can be directly reused.
// ============================================================

#include <QFont>
#include <QString>
#include <QWidget>

class QVBoxLayout;
class QScrollArea;

namespace ks::ui
{
    // scaledReportFont:
    // - Input baseFont: default interface font.
    // - Processing: Scale the structured report uniformly; prefer pointSizeF, falling back to pixel values if point size is unavailable.
    // - Returns: The font to be used for the report structured view.
    // Purpose: The detailed report reads addresses, hashes, and paths line by line; the default font size for the UI is too small to read comfortably.
    //       Page-built property trees (e.g., the tree constructed from the R0 structure for the file general page) must also
    //       call it; otherwise, two different font sizes will appear for the two structured views within the same window.
    QFont scaledReportFont(const QFont& baseFont);

    // ReportStructuredView: Report structured view control.
    // Lifecycle is managed by Qt's parent-child mechanism; the control holds no resources other than copies of business data.
    class ReportStructuredView final : public QWidget
    {
    public:
        // Constructor: creates a scroll container and vertical block layout without performing any parsing.
        // Input parameter parent: the Qt parent widget, which may be null.
        explicit ReportStructuredView(QWidget* parent = nullptr);
        ~ReportStructuredView() override;

        // setReportText：
        // - Input localizedReportText: Localized report plain text (caller is responsible for translation);
        // - Processing: Parse into block model and cache; when the control is invisible, only cache without creating the control, and build it when displayed.
        // - Return: true indicates a displayable structure was parsed; caller should allow switching to this view.
        //         false indicates the text has no structure (pure description, log, or raw data) and should remain as plain text.
        bool setReportText(const QString& localizedReportText);

        // canStructure：
        // - Input parameter localizedReportText: the plain text report to be evaluated.
        // - Processing: Perform only parsing checks without creating any controls;
        // - Return: true indicates a structured view is worth providing.
        static bool canStructure(const QString& localizedReportText);

        // hasStructure: Returns the result of the last setReportText evaluation.
        bool hasStructure() const;

        // verticalScrollBarWidth：
        // - Returns the width of the currently visible vertical scrollbar; returns 0 if no scrollbar exists.
        // - Purpose: When the host attaches a floating control to the top-right corner, it must avoid the scrollbar to prevent accidental clicks on the scroll bar.
        int verticalScrollBarWidth() const;

    protected:
        // changeEvent: Rebuild blocks with the new foreground color when the theme palette changes, ensuring status colors follow the theme.
        void changeEvent(QEvent* event) override;

        // showEvent: Rebuild child controls only on first display or cache invalidation to avoid unnecessary overhead from frequent row selections.
        void showEvent(QShowEvent* event) override;

    private:
        // rebuildBlocks: Rebuild all child controls based on the currently cached block model.
        void rebuildBlocks();

        // clearBlocks: Remove built block controls and clear the layout.
        void clearBlocks();

        QScrollArea* scrollArea_ = nullptr;   // m_scrollArea: Scroll host for the block container.
        QWidget* blockHost_ = nullptr;        // m_blockHost: Content panel hosting all block controls.
        QVBoxLayout* blockLayout_ = nullptr;  // m_blockLayout: Block vertical layout.
        QString reportText_;                  // m_reportText: The most recently parsed report text (localized).
        bool hasStructure_ = false;           // m_hasStructure: Whether the last parsing hit a structure.
        bool blocksDirty_ = true;             // m_blocksDirty: Whether the block controls need to be rebuilt.
    };
}
