// Offline automated test for the HOOK patch page construction layer (shared/evidence/HookPatchCompose.h).
//
// The four functions under test share a common characteristic: **they do not report errors when calculations are wrong**. If the final page is missing one byte,
// the result manifests only as "the machine behaves strangely at some moment"; if the rel32 displacement base is off by 5, the jump lands five bytes before the
// target, where there are often still valid instructions; if the ModRM byte of FF25 is written as a different value, the instruction still decodes correctly,
// but it fetches the jump target from a non-existent address; if the out-of-bounds check uses 32-bit addition, a request with an out-of-bounds size of 4 billion
// bytes will be judged as valid. These are not errors that can be detected by "installing and running once," so they must be proven on the build machine.
//
// Assertion principle (consistent with HvmEptSwitchTests.cpp):
//   * Expected values must be **independently calculated and hardcoded**, never derived by reversing the function
//     under test — a test that derives expected values from the code under test only proves that the code equals itself.
//   * Write architecture constants as **literals**, not symbols: an equation like f(SYMBOL) == SYMBOL
//     remains true if the constant is changed to another number, so no assertion will ever trigger.
//   * Test boundaries on both sides (exactly 4096 and 4097, +0x7FFFFFFF and +0x80000000, -0x80000000 and
//     -0x80000001): Testing only one side of the boundary is equivalent to not testing the boundary at all;
//   * The check order is also a criterion: when multiple reasons hold simultaneously, the return value is
//     strictly determined by the order of checks; otherwise, swapping the two if statements would have no effect.

#include "TestSupport.h"

#include "../../../shared/evidence/HookPatchCompose.h"

#include <array>
#include <cstdint>
#include <string_view>

namespace {

using namespace ksword::evidence;

// ---------------------------------------------------------------------------
// fixture
// ---------------------------------------------------------------------------

using Page = std::array<std::uint8_t, 4096>;

// The original page's bytes are generated by an expression unrelated to the code under test; the test recalculates the same expression to verify the expected value.
// The step 31 is coprime with 256, so no segment within the full 4096-byte page is constant;
// 'missing a segment' or 'copying with an offset error' can both alter the result.
Page makeOriginal(const std::uint8_t seed) {
    Page page{};
    for (std::uint32_t i = 0U; i < 4096U; ++i) {
        page[i] = static_cast<std::uint8_t>((i * 31U + 17U + seed) & 0xFFU);
    }
    return page;
}

std::uint8_t originalByte(const std::uint32_t index, const std::uint8_t seed) {
    return static_cast<std::uint8_t>((index * 31U + 17U + seed) & 0xFFU);
}

// Bytes outside the patch range match the original page byte-by-byte—this is the invariant for "shadow page = original page + patch".
bool outsidePatchMatchesOriginal(const ComposedPage& composed,
                                 const Page& original,
                                 const std::uint32_t offset,
                                 const std::uint32_t length) {
    for (std::uint32_t i = 0U; i < 4096U; ++i) {
        if (i >= offset && i < offset + length) {
            continue;
        }
        if (composed.bytes[i] != original[i]) {
            return false;
        }
    }
    return true;
}

bool patchLanded(const ComposedPage& composed,
                 const std::uint8_t* patch,
                 const std::uint32_t offset,
                 const std::uint32_t length) {
    for (std::uint32_t i = 0U; i < length; ++i) {
        if (composed.bytes[offset + i] != patch[i]) {
            return false;
        }
    }
    return true;
}

bool allZero(const std::uint8_t* bytes, const std::uint32_t length) {
    for (std::uint32_t i = 0U; i < length; ++i) {
        if (bytes[i] != 0U) {
            return false;
        }
    }
    return true;
}

// Read the encoded 4-byte displacement as a signed integer in little-endian order. Test this step with a standalone implementation without
// borrowing any code from the unit under test; otherwise, 'encoding errors' and 'decoding errors' would cancel each other out and pass the test.
std::int32_t readDisplacement(const std::array<std::uint8_t, 5>& bytes) {
    const std::uint32_t kRaw = static_cast<std::uint32_t>(bytes[1]) |
                              (static_cast<std::uint32_t>(bytes[2]) << 8U) |
                              (static_cast<std::uint32_t>(bytes[3]) << 16U) |
                              (static_cast<std::uint32_t>(bytes[4]) << 24U);
    return static_cast<std::int32_t>(kRaw);
}

std::uint64_t readAbsoluteTarget(const std::array<std::uint8_t, 14>& bytes) {
    std::uint64_t value = 0ULL;
    for (std::uint32_t i = 0U; i < 8U; ++i) {
        value |= static_cast<std::uint64_t>(bytes[6U + i]) << (i * 8U);
    }
    return value;
}

// Reverse-engineer the target from the given displacement: target = src + 5 + delta (modulo 2^64). The fixture uses this to
// construct samples, while the function under test walks back using subtraction; the two paths do not borrow from each other.
std::uint64_t targetForDisplacement(const std::uint64_t srcVa, const std::int64_t delta) {
    return srcVa + 5ULL + static_cast<std::uint64_t>(delta);
}

// ---------------------------------------------------------------------------
// Architectural and protocol constants: write literals, not symbols.
// ---------------------------------------------------------------------------
void testArchitecturalLiterals(ksword_tests::Suite& s) {
    // A single view covers exactly one page. This value also represents the shadow byte count required by addView under
    // the Explicit seed (KvmControl.cpp:1142-1150); reducing it by one will cause the driver to reject every installation.
    s.expect(kPatchPageBytes == 4096U, L"the patch page is exactly 4096 bytes");
    // E9 rel32 instruction length. Writing 4 shifts the displacement base forward by one byte, causing the
    // jump to land one byte before the target—where it usually still decodes without immediate machine error.
    s.expect(kRel32JumpLength == 5U, L"a near jump is exactly 5 bytes");
    // FF /4 + ModRM + disp32 + 8-byte target = 14 bytes.
    s.expect(kAbsoluteJumpLength == 14U, L"an absolute jump is exactly 14 bytes");

    // Variable names 'near'/'far' are not used: the two corresponding names in Windows headers are empty macros;
    // including any additional header in this chain later would cause this file to fail compilation unexpectedly.
    const Rel32Jump kShortJump = encodeRel32Jump(0x1000ULL, 0x1005ULL);
    // The primary opcode for JMP rel32 is 0xE9 (SDM Vol.2A, JMP). 0xEB is rel8, with a different encoding length.
    s.expect(kShortJump.bytes[0] == 0xE9U, L"the near jump opcode is literally 0xE9");

    const auto kLongJump = encodeAbsoluteJump(0ULL);
    // FF /4 is JMP r/m64.
    s.expect(kLongJump[0] == 0xFFU, L"the absolute jump opcode is literally 0xFF");
    // ModRM 0x25 = mod 00 / reg 100 / rm 101. In 64-bit mode, mod=00 and rm=101 indicate RIP-relative
    // addressing; writing 0x24 (rm=100) would switch to SIB addressing, and writing 0x2C would replace the
    // reg field, turning it into a non-JMP instruction. All three encodings remain valid instructions.
    s.expect(kLongJump[1] == 0x25U, L"the absolute jump ModRM byte is literally 0x25");

    s.expect(ComposedPage{}.bytes.size() == 4096U, L"the composed page array holds 4096 bytes");
    s.expect(Rel32Jump{}.bytes.size() == 5U, L"the near jump array holds 5 bytes");
    s.expect(kLongJump.size() == 14U, L"the absolute jump array holds 14 bytes");
}

// ---------------------------------------------------------------------------
// Status name
// ---------------------------------------------------------------------------
void testStatusNames(ksword_tests::Suite& s) {
    using SV = std::string_view;
    s.expect(SV(patchComposeStatusName(PatchComposeStatus::kOk)) == "Ok",
             L"compose status Ok has its own name");
    s.expect(SV(patchComposeStatusName(PatchComposeStatus::kOriginalMissing)) == "OriginalMissing",
             L"compose status OriginalMissing has its own name");
    s.expect(SV(patchComposeStatusName(PatchComposeStatus::kPatchMissing)) == "PatchMissing",
             L"compose status PatchMissing has its own name");
    s.expect(SV(patchComposeStatusName(PatchComposeStatus::kCrossesPageBoundary)) == "CrossesPageBoundary",
             L"compose status CrossesPageBoundary has its own name");
    s.expect(SV(patchComposeStatusName(PatchComposeStatus::kEmptyPatch)) == "EmptyPatch",
             L"compose status EmptyPatch has its own name");
    s.expect(SV(jumpEncodeStatusName(JumpEncodeStatus::kOk)) == "Ok",
             L"jump status Ok has its own name");
    s.expect(SV(jumpEncodeStatusName(JumpEncodeStatus::kDisplacementOutOfRange)) == "DisplacementOutOfRange",
             L"jump status DisplacementOutOfRange has its own name");
    s.expect(SV(crossPageClassificationName(CrossPageClassification::kInPage)) == "InPage",
             L"classification InPage has its own name");
    s.expect(SV(crossPageClassificationName(CrossPageClassification::kCrossesPage)) == "CrossesPage",
             L"classification CrossesPage has its own name");

    // The names are distinct. Merging two names into one results in no rejection reason:
    // the UI would display the same message for two completely different errors.
    const PatchComposeStatus kAll[] = {
        PatchComposeStatus::kOk,
        PatchComposeStatus::kOriginalMissing,
        PatchComposeStatus::kPatchMissing,
        PatchComposeStatus::kCrossesPageBoundary,
        PatchComposeStatus::kEmptyPatch,
    };
    bool distinct = true;
    for (std::uint32_t i = 0U; i < 5U; ++i) {
        for (std::uint32_t j = i + 1U; j < 5U; ++j) {
            if (SV(patchComposeStatusName(kAll[i])) == SV(patchComposeStatusName(kAll[j]))) {
                distinct = false;
            }
        }
    }
    s.expect(distinct, L"every compose status renders a distinct name");
}

// ---------------------------------------------------------------------------
// Geometry: classifyCrossPage
// ---------------------------------------------------------------------------
void testCrossPageGeometry(ksword_tests::Suite& s) {
    s.expect(classifyCrossPage(0U, 4096U) == CrossPageClassification::kInPage,
             L"a full-page patch at offset zero is in page");
    s.expect(classifyCrossPage(0U, 4097U) == CrossPageClassification::kCrossesPage,
             L"one byte past a full page crosses");
    s.expect(classifyCrossPage(4095U, 1U) == CrossPageClassification::kInPage,
             L"the last byte of the page is in page");
    s.expect(classifyCrossPage(4095U, 2U) == CrossPageClassification::kCrossesPage,
             L"two bytes at the last offset cross");
    s.expect(classifyCrossPage(4096U, 0U) == CrossPageClassification::kInPage,
             L"an empty span ending exactly at the page end is in page");
    s.expect(classifyCrossPage(4096U, 1U) == CrossPageClassification::kCrossesPage,
             L"one byte starting at the page end crosses");
    s.expect(classifyCrossPage(1U, 4095U) == CrossPageClassification::kInPage,
             L"a patch ending exactly at the page end is in page");
    s.expect(classifyCrossPage(1U, 4096U) == CrossPageClassification::kCrossesPage,
             L"a full-page patch at offset one crosses");
    s.expect(classifyCrossPage(0U, 0U) == CrossPageClassification::kInPage,
             L"an empty span at offset zero is in page");
    s.expect(classifyCrossPage(2048U, 2048U) == CrossPageClassification::kInPage,
             L"a half page starting mid page is in page");
    s.expect(classifyCrossPage(2048U, 2049U) == CrossPageClassification::kCrossesPage,
             L"one byte past the middle-start half page crosses");
    s.expect(classifyCrossPage(4097U, 0U) == CrossPageClassification::kCrossesPage,
             L"an empty span starting past the page end still crosses");
    s.expect(classifyCrossPage(5000U, 0U) == CrossPageClassification::kCrossesPage,
             L"an offset far past the page end crosses even with no bytes");

    // 32-bit wraparound trap: 0xFFFFFFFF + 2 equals 1 in 32-bit arithmetic, which would incorrectly classify all three cases as InPage.
    s.expect(classifyCrossPage(0xFFFFFFFFU, 2U) == CrossPageClassification::kCrossesPage,
             L"a wrapping offset plus length does not fold back into the page");
    s.expect(classifyCrossPage(2U, 0xFFFFFFFFU) == CrossPageClassification::kCrossesPage,
             L"a wrapping length does not fold back into the page");
    s.expect(classifyCrossPage(0xFFFFFFFFU, 0xFFFFFFFFU) == CrossPageClassification::kCrossesPage,
             L"both operands at the 32-bit maximum still cross");

    // Scan the entire page: at each starting point, "exact fit" is valid, while "one extra byte" causes an out-of-bounds error.
    bool exactFitAllInPage = true;
    bool oneMoreAllCrosses = true;
    bool emptyAllInPage = true;
    for (std::uint32_t offset = 0U; offset <= 4096U; ++offset) {
        if (classifyCrossPage(offset, 4096U - offset) != CrossPageClassification::kInPage) {
            exactFitAllInPage = false;
        }
        if (classifyCrossPage(offset, 4096U - offset + 1U) != CrossPageClassification::kCrossesPage) {
            oneMoreAllCrosses = false;
        }
        if (classifyCrossPage(offset, 0U) != CrossPageClassification::kInPage) {
            emptyAllInPage = false;
        }
    }
    s.expect(exactFitAllInPage, L"every offset accepts the length that exactly fills the page");
    s.expect(oneMoreAllCrosses, L"every offset rejects one byte more than fills the page");
    s.expect(emptyAllInPage, L"an empty span is in page at every offset up to the page end");
}

// ---------------------------------------------------------------------------
// composePage geometry and check order.
// ---------------------------------------------------------------------------
void testComposeGeometryAndOrder(ksword_tests::Suite& s) {
    const Page kOriginal = makeOriginal(0U);
    const Page kPatch = makeOriginal(0x5AU);
    const auto kStatusAt = [&](const std::uint32_t offset, const std::uint32_t length) {
        return composePage(kOriginal.data(), offset, kPatch.data(), length).status;
    };

    s.expect(kStatusAt(0U, 4096U) == PatchComposeStatus::kOk,
             L"a patch that exactly fills the page is accepted");
    s.expect(kStatusAt(0U, 4097U) == PatchComposeStatus::kCrossesPageBoundary,
             L"4097 bytes at offset zero is refused");
    s.expect(kStatusAt(4095U, 1U) == PatchComposeStatus::kOk,
             L"a single byte at the last offset is accepted");
    s.expect(kStatusAt(4095U, 2U) == PatchComposeStatus::kCrossesPageBoundary,
             L"two bytes at the last offset are refused");
    s.expect(kStatusAt(4096U, 1U) == PatchComposeStatus::kCrossesPageBoundary,
             L"a patch starting at the page end is refused");
    s.expect(kStatusAt(0xFFFFFFFFU, 2U) == PatchComposeStatus::kCrossesPageBoundary,
             L"compose refuses the 32-bit wrapping request the same way the classifier does");

    // --- Check Order --- The criterion for which reason to return when all four conditions hold is part of
    // the logic. Without these checks, swapping two if statements in the future would cause no reaction,
    // while the UI would start providing a rejection reason that fails to explain the actual issue.
    s.expect(composePage(nullptr, 0U, kPatch.data(), 16U).status == PatchComposeStatus::kOriginalMissing,
             L"a null original page is refused");
    s.expect(composePage(nullptr, 5000U, nullptr, 0U).status == PatchComposeStatus::kOriginalMissing,
             L"the null original is reported ahead of every other defect");
    s.expect(composePage(kOriginal.data(), 0U, nullptr, 8U).status == PatchComposeStatus::kPatchMissing,
             L"a null patch with a non-zero length is refused");
    s.expect(composePage(kOriginal.data(), 5000U, nullptr, 8U).status == PatchComposeStatus::kPatchMissing,
             L"the null patch is reported ahead of the geometry");
    s.expect(composePage(kOriginal.data(), 100U, nullptr, 0U).status == PatchComposeStatus::kEmptyPatch,
             L"a null patch of length zero is an empty patch rather than a missing one");
    s.expect(kStatusAt(100U, 0U) == PatchComposeStatus::kEmptyPatch,
             L"an empty patch is refused instead of producing a page equal to the original");
    s.expect(kStatusAt(4096U, 0U) == PatchComposeStatus::kEmptyPatch,
             L"an empty patch at the page end passes the geometry and is refused as empty");
    s.expect(kStatusAt(5000U, 0U) == PatchComposeStatus::kCrossesPageBoundary,
             L"the geometry is reported ahead of the emptiness so both functions agree");

    // --- Echo and failure states ---
    const ComposedPage kAccepted = composePage(kOriginal.data(), 1234U, kPatch.data(), 56U);
    const ComposedPage kRefused = composePage(kOriginal.data(), 4090U, kPatch.data(), 16U);
    s.expect(kAccepted.ok() && kAccepted.patchOffset == 1234U && kAccepted.patchLength == 56U,
             L"an accepted result echoes the request it was given");
    s.expect(!kRefused.ok() && kRefused.patchOffset == 4090U && kRefused.patchLength == 16U,
             L"a refused result echoes the request so the reason can name it");
    s.expect(kRefused.status == PatchComposeStatus::kCrossesPageBoundary,
             L"sixteen bytes at offset 4090 cross the page end");
    s.expect(allZero(kRefused.bytes.data(), 4096U),
             L"a refused compose leaves the page all zero rather than a half-built one");
    s.expect(allZero(composePage(nullptr, 0U, nullptr, 0U).bytes.data(), 4096U),
             L"a refused compose with no inputs at all still leaves the page all zero");
    const ComposedPage kDefaulted{};
    s.expect(!kDefaulted.ok() && allZero(kDefaulted.bytes.data(), 4096U),
             L"a default-constructed result is a failure carrying an all-zero page");
    s.expect(kDefaulted.status == PatchComposeStatus::kOriginalMissing,
             L"the default state is a named failure rather than a silent Ok");

    // Every rejection path must leave a zero page, especially for EmptyPatch: if it falls back to producing a page
    // identical to the original, a caller that forgets to check the status will install a 'no-change' HOOK view;
    // since this view generates no violations in steady state, no one would notice that the patch was never applied.
    const ComposedPage kEmpty = composePage(kOriginal.data(), 100U, kPatch.data(), 0U);
    const ComposedPage kMissing = composePage(kOriginal.data(), 100U, nullptr, 8U);
    const ComposedPage kNoOriginal = composePage(nullptr, 100U, kPatch.data(), 8U);
    s.expect(allZero(kEmpty.bytes.data(), 4096U),
             L"an empty patch leaves an all-zero page rather than a copy of the original");
    s.expect(allZero(kMissing.bytes.data(), 4096U),
             L"a missing patch pointer leaves an all-zero page");
    s.expect(kEmpty.patchOffset == 100U && kEmpty.patchLength == 0U,
             L"the empty-patch refusal still echoes the request");
    s.expect(kNoOriginal.patchOffset == 100U && kNoOriginal.patchLength == 8U,
             L"the missing-original refusal still echoes the request");
    s.expect(!kEmpty.ok() && !kMissing.ok() && !kNoOriginal.ok() && !kRefused.ok(),
             L"none of the four refusal statuses reports itself as ok");

    // The two functions must always yield consistent conclusions for the same set of parameters.
    const std::uint32_t kOffsets[] = { 0U, 1U, 4090U, 4095U, 4096U, 4097U, 5000U, 0xFFFFFFFFU };
    const std::uint32_t kLengths[] = { 0U, 1U, 2U, 5U, 14U, 4096U, 0xFFFFFFFFU };
    bool agree = true;
    for (const std::uint32_t kOffset : kOffsets) {
        for (const std::uint32_t kLength : kLengths) {
            const bool kCrosses =
                classifyCrossPage(kOffset, kLength) == CrossPageClassification::kCrossesPage;
            const bool kRefusedHere =
                kStatusAt(kOffset, kLength) == PatchComposeStatus::kCrossesPageBoundary;
            if (kCrosses != kRefusedHere) {
                agree = false;
            }
        }
    }
    s.expect(agree, L"compose refuses exactly the spans the classifier calls crossing");
}

// ---------------------------------------------------------------------------
// The 'exact fit' boundary for every real patch length.
// ---------------------------------------------------------------------------
void testExactFitLengths(ksword_tests::Suite& s) {
    const Page kOriginal = makeOriginal(0U);
    const Page kPatch = makeOriginal(0xA5U);
    const auto kFitsOnlyAt = [&](const std::uint32_t length) {
        const std::uint32_t kLastOffset = 4096U - length;
        const bool kFits =
            composePage(kOriginal.data(), kLastOffset, kPatch.data(), length).status ==
            PatchComposeStatus::kOk;
        const bool kOneMore =
            composePage(kOriginal.data(), kLastOffset + 1U, kPatch.data(), length).status ==
            PatchComposeStatus::kCrossesPageBoundary;
        return kFits && kOneMore;
    };

    // This table's lengths aren't arbitrary: 1/2/4/8 are data patches, 5 is an E9 near jump, 14 is an FF25 far jump, and the rest are
    // common function header overwrite sizes. Each entry strictly defines the 'last valid start offset' and 'the next byte after it'.
    s.expect(kFitsOnlyAt(1U), L"a 1-byte patch fits only up to offset 4095");
    s.expect(kFitsOnlyAt(2U), L"a 2-byte patch fits only up to offset 4094");
    s.expect(kFitsOnlyAt(4U), L"a 4-byte patch fits only up to offset 4092");
    s.expect(kFitsOnlyAt(5U), L"a 5-byte near jump fits only up to offset 4091");
    s.expect(kFitsOnlyAt(8U), L"an 8-byte patch fits only up to offset 4088");
    s.expect(kFitsOnlyAt(14U), L"a 14-byte absolute jump fits only up to offset 4082");
    s.expect(kFitsOnlyAt(16U), L"a 16-byte patch fits only up to offset 4080");
    s.expect(kFitsOnlyAt(32U), L"a 32-byte patch fits only up to offset 4064");
    s.expect(kFitsOnlyAt(64U), L"a 64-byte patch fits only up to offset 4032");
    s.expect(kFitsOnlyAt(128U), L"a 128-byte patch fits only up to offset 3968");
    s.expect(kFitsOnlyAt(256U), L"a 256-byte patch fits only up to offset 3840");
    s.expect(kFitsOnlyAt(512U), L"a 512-byte patch fits only up to offset 3584");
    s.expect(kFitsOnlyAt(1024U), L"a 1024-byte patch fits only up to offset 3072");
    s.expect(kFitsOnlyAt(2048U), L"a 2048-byte patch fits only up to offset 2048");
    s.expect(kFitsOnlyAt(4095U), L"a 4095-byte patch fits only at offset 0 and 1");
    s.expect(kFitsOnlyAt(4096U), L"a full-page patch fits only at offset 0");
}

// ---------------------------------------------------------------------------
// Bytes of the compiled page
// ---------------------------------------------------------------------------
void testComposedBytes(ksword_tests::Suite& s) {
    const Page kOriginal = makeOriginal(0U);
    const std::array<std::uint8_t, 5> kPatch = { 0xE9U, 0x11U, 0x22U, 0x33U, 0x44U };

    const ComposedPage kMid = composePage(kOriginal.data(), 0x100U, kPatch.data(), 5U);
    s.expect(kMid.ok() && kMid.bytes.size() == 4096U,
             L"an accepted page is always exactly one page long");
    s.expect(patchLanded(kMid, kPatch.data(), 0x100U, 5U),
             L"the patch bytes land at the requested offset");
    s.expect(outsidePatchMatchesOriginal(kMid, kOriginal, 0x100U, 5U),
             L"every byte outside the patch equals the original page");
    // Expected values are recalculated independently: the byte immediately before offset 0x100 must remain the original page value.
    s.expect(kMid.bytes[0xFFU] == originalByte(0xFFU, 0U) &&
                 kMid.bytes[0x105U] == originalByte(0x105U, 0U),
             L"the bytes immediately around the patch are untouched");

    const ComposedPage kHead = composePage(kOriginal.data(), 0U, kPatch.data(), 5U);
    s.expect(kHead.ok() && patchLanded(kHead, kPatch.data(), 0U, 5U),
             L"a patch at offset zero lands at the start of the page");
    s.expect(outsidePatchMatchesOriginal(kHead, kOriginal, 0U, 5U),
             L"the rest of the page survives a patch at offset zero");

    const ComposedPage kTail = composePage(kOriginal.data(), 4091U, kPatch.data(), 5U);
    s.expect(kTail.ok() && patchLanded(kTail, kPatch.data(), 4091U, 5U),
             L"a patch ending exactly at the page end lands there");
    s.expect(outsidePatchMatchesOriginal(kTail, kOriginal, 4091U, 5U),
             L"the prefix survives a patch that ends at the page end");
    s.expect(kTail.bytes[4095U] == 0x44U && kTail.bytes[4090U] == originalByte(4090U, 0U),
             L"the last page byte is the patch tail and the byte before it is original");

    const Page kFullPatch = makeOriginal(0x33U);
    const ComposedPage kFull = composePage(kOriginal.data(), 0U, kFullPatch.data(), 4096U);
    s.expect(kFull.ok() && kFull.bytes == kFullPatch,
             L"a full-page patch replaces the page entirely");
    // Applying the same full-page patch over another original page must yield the same page bytes: this proves that "no
    // original page bytes survive." Comparing full.bytes with fullPatch again is merely a rephrasing of the previous assertion.
    const Page kOtherBase = makeOriginal(0x77U);
    const ComposedPage kFullOverOther = composePage(kOtherBase.data(), 0U, kFullPatch.data(), 4096U);
    s.expect(kFullOverOther.ok() && kFullOverOther.bytes == kFull.bytes,
             L"a full-page patch makes the result independent of the page underneath");

    // All 256 byte values. Mixing uint8_t and char causes sign issues on 0x80..0xFF.
    std::array<std::uint8_t, 256> everyValue{};
    for (std::uint32_t i = 0U; i < 256U; ++i) {
        everyValue[i] = static_cast<std::uint8_t>(i);
    }
    const ComposedPage kSpread = composePage(kOriginal.data(), 1000U, everyValue.data(), 256U);
    s.expect(kSpread.ok() && patchLanded(kSpread, everyValue.data(), 1000U, 256U),
             L"all 256 byte values survive the copy unchanged");
    s.expect(kSpread.bytes[1000U + 0x80U] == 0x80U,
             L"a high-bit byte is not sign extended on the way in");
    s.expect(kSpread.bytes[1000U + 0xFFU] == 0xFFU,
             L"the 0xFF byte lands as 0xFF");
    s.expect(outsidePatchMatchesOriginal(kSpread, kOriginal, 1000U, 256U),
             L"a 256-byte patch leaves the remaining 3840 bytes alone");

    // Center: half original page, half patch; any implementation that stops after copying half a page will be exposed here.
    const Page kHalfPatch = makeOriginal(0x0FU);
    const ComposedPage kHalf = composePage(kOriginal.data(), 2048U, kHalfPatch.data(), 2048U);
    s.expect(kHalf.ok() && patchLanded(kHalf, kHalfPatch.data(), 2048U, 2048U),
             L"a half-page patch starting at the midpoint lands in full");
    s.expect(outsidePatchMatchesOriginal(kHalf, kOriginal, 2048U, 2048U),
             L"the first half of the page survives a half-page patch");
    const std::array<std::uint8_t, 2> kStraddle = { 0xAAU, 0xBBU };
    const ComposedPage kMidpoint = composePage(kOriginal.data(), 2047U, kStraddle.data(), 2U);
    s.expect(kMidpoint.ok() && kMidpoint.bytes[2047U] == 0xAAU && kMidpoint.bytes[2048U] == 0xBBU,
             L"a patch straddling the midpoint writes both halves");

    // Patch bytes exactly match original page bytes: this is valid input, producing a page identical
    // to the original. This is distinct from EmptyPatch, which means 'no patch was provided'.
    std::array<std::uint8_t, 5> identity{};
    for (std::uint32_t i = 0U; i < 5U; ++i) {
        identity[i] = originalByte(2000U + i, 0U);
    }
    const ComposedPage kSame = composePage(kOriginal.data(), 2000U, identity.data(), 5U);
    s.expect(kSame.ok() && kSame.bytes == kOriginal,
             L"a patch equal to the original bytes yields a page equal to the original");

    // Scan single-byte patches at every offset: each location must modify exactly one byte.
    const std::uint8_t kSingle = 0xCCU;
    bool everyOffsetOk = true;
    bool everyOffsetLands = true;
    bool everyOffsetPreservesRest = true;
    for (std::uint32_t offset = 0U; offset < 4096U; ++offset) {
        const ComposedPage kOne = composePage(kOriginal.data(), offset, &kSingle, 1U);
        if (!kOne.ok()) {
            everyOffsetOk = false;
        }
        if (kOne.bytes[offset] != kSingle) {
            everyOffsetLands = false;
        }
        if (!outsidePatchMatchesOriginal(kOne, kOriginal, offset, 1U)) {
            everyOffsetPreservesRest = false;
        }
    }
    s.expect(everyOffsetOk, L"a single-byte patch is accepted at every offset in the page");
    s.expect(everyOffsetLands, L"a single-byte patch lands at every offset in the page");
    s.expect(everyOffsetPreservesRest, L"a single-byte patch changes nothing else at any offset");

    // Deterministic and side-effect free.
    const Page kOriginalCopy = kOriginal;
    const std::array<std::uint8_t, 5> kPatchCopy = kPatch;
    const ComposedPage kAgain = composePage(kOriginal.data(), 0x100U, kPatch.data(), 5U);
    s.expect(kAgain.bytes == kMid.bytes, L"composing the same request twice yields the same page");
    s.expect(kOriginal == kOriginalCopy, L"compose does not write through the original pointer");
    s.expect(kPatch == kPatchCopy, L"compose does not write through the patch pointer");

    // Two original pages differing by exactly one seed: the difference between the composed pages must exactly match the difference between the original pages.
    const Page kOther = makeOriginal(1U);
    const ComposedPage kFromOther = composePage(kOther.data(), 0x100U, kPatch.data(), 5U);
    bool differsExactlyWhereOriginalsDiffer = true;
    for (std::uint32_t i = 0U; i < 4096U; ++i) {
        if (i >= 0x100U && i < 0x105U) {
            continue;
        }
        if ((kMid.bytes[i] != kFromOther.bytes[i]) != (kOriginal[i] != kOther[i])) {
            differsExactlyWhereOriginalsDiffer = false;
        }
    }
    s.expect(differsExactlyWhereOriginalsDiffer,
             L"outside the patch the composed pages differ exactly where the originals differ");
    s.expect(patchLanded(kFromOther, kPatch.data(), 0x100U, 5U),
             L"the same patch lands identically on a different original page");
}

// ---------------------------------------------------------------------------
// rel32 near jump
// ---------------------------------------------------------------------------
void testRel32Encoding(ksword_tests::Suite& s) {
    // Offset 0: The target is the instruction immediately following this jump.
    const Rel32Jump kZero = encodeRel32Jump(0x1000ULL, 0x1005ULL);
    const std::array<std::uint8_t, 5> kZeroWant = { 0xE9U, 0x00U, 0x00U, 0x00U, 0x00U };
    s.expect(kZero.ok(), L"a jump to the following instruction encodes");
    s.expect(kZero.displacement == 0, L"a jump to the following instruction has displacement zero");
    s.expect(kZero.bytes == kZeroWant, L"a zero displacement encodes as E9 00 00 00 00");

    // Manual calculation: next = 0xFFFFF80000001005, target - next = 0x2000 - 0x1005 = 0xFFB = 4091.
    const Rel32Jump kForward = encodeRel32Jump(0xFFFFF80000001000ULL, 0xFFFFF80000002000ULL);
    const std::array<std::uint8_t, 5> kForwardWant = { 0xE9U, 0xFBU, 0x0FU, 0x00U, 0x00U };
    s.expect(kForward.ok() && kForward.displacement == 4091,
             L"a forward jump displacement is measured from the next instruction");
    s.expect(kForward.bytes == kForwardWant, L"a forward displacement of 4091 encodes as FB 0F 00 00");

    // Manual calculation: next = 0xFFFFF80000002005, target - next = 0x1000 - 0x2005 = -0x1005 = -4101.
    // -4101's 32-bit two's complement is 0xFFFFEFFB, little-endian: FB EF FF FF.
    const Rel32Jump kBackward = encodeRel32Jump(0xFFFFF80000002000ULL, 0xFFFFF80000001000ULL);
    const std::array<std::uint8_t, 5> kBackwardWant = { 0xE9U, 0xFBU, 0xEFU, 0xFFU, 0xFFU };
    s.expect(kBackward.ok() && kBackward.displacement == -4101,
             L"a backward jump displacement is negative and includes the instruction length");
    s.expect(kBackward.bytes == kBackwardWant, L"a displacement of -4101 encodes as FB EF FF FF");

    // Jump to self: displacement = -5, which is exactly where the 'instruction length' term appears alone. Undercounting
    // by 5 would make this assertion 0, and a jump with displacement 0 moves forward rather than looping in place.
    const Rel32Jump kSelfJump = encodeRel32Jump(0xFFFFF80000003000ULL, 0xFFFFF80000003000ULL);
    const std::array<std::uint8_t, 5> kSelfWant = { 0xE9U, 0xFBU, 0xFFU, 0xFFU, 0xFFU };
    s.expect(kSelfJump.ok() && kSelfJump.displacement == -5,
             L"a jump to its own address has displacement minus the instruction length");
    s.expect(kSelfJump.bytes == kSelfWant, L"a displacement of -5 encodes as FB FF FF FF");

    // ±1: Sign handling is most prone to errors when written together at these two locations.
    const std::uint64_t kUnitSrc = 0xFFFFF80000004000ULL;
    const Rel32Jump kPlusOne = encodeRel32Jump(kUnitSrc, kUnitSrc + 6ULL);
    const Rel32Jump kMinusOne = encodeRel32Jump(kUnitSrc, kUnitSrc + 4ULL);
    const std::array<std::uint8_t, 5> kPlusOneWant = { 0xE9U, 0x01U, 0x00U, 0x00U, 0x00U };
    const std::array<std::uint8_t, 5> kMinusOneWant = { 0xE9U, 0xFFU, 0xFFU, 0xFFU, 0xFFU };
    s.expect(kPlusOne.ok() && kPlusOne.displacement == 1 && kPlusOne.bytes == kPlusOneWant,
             L"a displacement of +1 encodes as 01 00 00 00");
    s.expect(kMinusOne.ok() && kMinusOne.displacement == -1 && kMinusOne.bytes == kMinusOneWant,
             L"a displacement of -1 encodes as FF FF FF FF");

    // Displacement with all four bytes distinct, locking the little-endian order byte-by-byte.
    const Rel32Jump kOrdered = encodeRel32Jump(0x0000000000100000ULL, 0x000000001244567DULL);
    s.expect(kOrdered.ok() && kOrdered.displacement == 0x12345678,
             L"the sample chosen for byte order really has displacement 0x12345678");
    s.expect(kOrdered.bytes[1] == 0x78U && kOrdered.bytes[2] == 0x56U &&
                 kOrdered.bytes[3] == 0x34U && kOrdered.bytes[4] == 0x12U,
             L"the displacement is stored little endian");
    // - The 32-bit two's complement of -0x12345678 is 0xEDCBA988, which is 88 A9 CB ED in little-endian order.
    const Rel32Jump kOrderedNegative = encodeRel32Jump(0x0000000020000000ULL, 0x000000000DCBA98DULL);
    s.expect(kOrderedNegative.ok() && kOrderedNegative.displacement == -0x12345678,
             L"the negative byte-order sample really has displacement -0x12345678");
    s.expect(kOrderedNegative.bytes[1] == 0x88U && kOrderedNegative.bytes[2] == 0xA9U &&
                 kOrderedNegative.bytes[3] == 0xCBU && kOrderedNegative.bytes[4] == 0xEDU,
             L"a negative displacement is stored little endian in two's complement");

    // --- Positive boundary ---
    const Rel32Jump kMaxPositive = encodeRel32Jump(0x0000000000010000ULL, 0x0000000080010004ULL);
    const std::array<std::uint8_t, 5> kMaxPositiveWant = { 0xE9U, 0xFFU, 0xFFU, 0xFFU, 0x7FU };
    s.expect(kMaxPositive.ok(), L"a displacement of +0x7FFFFFFF is inside the encodable range");
    s.expect(kMaxPositive.displacement == 0x7FFFFFFF,
             L"the positive boundary sample really has displacement +0x7FFFFFFF");
    s.expect(kMaxPositive.bytes == kMaxPositiveWant,
             L"the maximum positive displacement encodes as FF FF FF 7F");

    const Rel32Jump kOverPositive = encodeRel32Jump(0x0000000000010000ULL, 0x0000000080010005ULL);
    s.expect(!kOverPositive.ok() &&
                 kOverPositive.status == JumpEncodeStatus::kDisplacementOutOfRange,
             L"one byte past +0x7FFFFFFF is refused");
    s.expect(kOverPositive.displacement == 0x80000000LL,
             L"the refused positive displacement is reported so the reason can name it");
    s.expect(allZero(kOverPositive.bytes.data(), 5U),
             L"a refused near jump leaves all five bytes zero rather than a truncated jump");

    // --- Negative boundary ---
    const Rel32Jump kMaxNegative = encodeRel32Jump(0x0000000100000000ULL, 0x0000000080000005ULL);
    const std::array<std::uint8_t, 5> kMaxNegativeWant = { 0xE9U, 0x00U, 0x00U, 0x00U, 0x80U };
    s.expect(kMaxNegative.ok(), L"a displacement of -0x80000000 is inside the encodable range");
    s.expect(kMaxNegative.displacement == -0x80000000LL,
             L"the negative boundary sample really has displacement -0x80000000");
    s.expect(kMaxNegative.bytes == kMaxNegativeWant,
             L"the most negative displacement encodes as 00 00 00 80");

    const Rel32Jump kOverNegative = encodeRel32Jump(0x0000000100000000ULL, 0x0000000080000004ULL);
    s.expect(!kOverNegative.ok(), L"one byte past -0x80000000 is refused");
    s.expect(kOverNegative.displacement == -0x80000001LL,
             L"the refused negative displacement is reported exactly");
    s.expect(allZero(kOverNegative.bytes.data(), 5U),
             L"a refused negative near jump also leaves all five bytes zero");

    // Modulo 2^64: src + 5 wraps exactly to 0, so the displacement for target 0x10 is 0x10.
    const Rel32Jump kWrapped = encodeRel32Jump(0xFFFFFFFFFFFFFFFBULL, 0x0000000000000010ULL);
    const std::array<std::uint8_t, 5> kWrappedWant = { 0xE9U, 0x10U, 0x00U, 0x00U, 0x00U };
    s.expect(kWrapped.ok() && kWrapped.bytes == kWrappedWant,
             L"address arithmetic wraps modulo 2^64 exactly like the hardware does");

    // A user-to-kernel address pair spanning a non-canonical hole: displacement is 0xFFFF000000000FFB, rejected as-is.
    const Rel32Jump kAcrossHole = encodeRel32Jump(0x00007FFFFFFFF000ULL, 0xFFFF800000000000ULL);
    s.expect(!kAcrossHole.ok(),
             L"a user-to-kernel pair is refused instead of folding into a small displacement");

    const Rel32Jump kDefaulted{};
    s.expect(!kDefaulted.ok() && allZero(kDefaulted.bytes.data(), 5U),
             L"a default-constructed near jump is a failure carrying zero bytes");

    // Iterate through valid shifts: encoding then decoding must result in bitwise equality.
    const std::int64_t kLegal[] = {
        0, 1, -1, 2, -2, 0x7F, -0x80, 0x100, -0x100, 0x7FFF, -0x8000,
        0x40000000LL, -0x40000000LL, 0x7FFFFFFELL, -0x7FFFFFFFLL,
        0x7FFFFFFFLL, -0x80000000LL, 0x12345678LL, -0x12345678LL,
    };
    const std::uint64_t kSrc = 0xFFFFF80000100000ULL;
    bool allLegalOk = true;
    bool allRoundTrip = true;
    bool allOpcodes = true;
    for (const std::int64_t kDelta : kLegal) {
        const Rel32Jump kJump = encodeRel32Jump(kSrc, targetForDisplacement(kSrc, kDelta));
        if (!kJump.ok()) {
            allLegalOk = false;
        }
        if (static_cast<std::int64_t>(readDisplacement(kJump.bytes)) != kDelta ||
            kJump.displacement != kDelta) {
            allRoundTrip = false;
        }
        if (kJump.bytes[0] != 0xE9U) {
            allOpcodes = false;
        }
    }
    s.expect(allLegalOk, L"every displacement inside the int32 range encodes");
    s.expect(allRoundTrip, L"every encoded displacement reads back bit for bit");
    s.expect(allOpcodes, L"every encoded near jump starts with the E9 opcode");

    // Test every out-of-range shift: reject all of them without producing any bytes.
    const std::int64_t kIllegal[] = {
        0x80000000LL, 0x80000001LL, 0xFFFFFFFFLL, 0x100000000LL, 0x123456789LL,
        -0x80000001LL, -0x80000002LL, -0x100000000LL, -0x123456789LL,
    };
    bool allIllegalRefused = true;
    bool allIllegalZeroed = true;
    bool allIllegalReported = true;
    for (const std::int64_t kDelta : kIllegal) {
        const Rel32Jump kJump = encodeRel32Jump(kSrc, targetForDisplacement(kSrc, kDelta));
        if (kJump.ok() || kJump.status != JumpEncodeStatus::kDisplacementOutOfRange) {
            allIllegalRefused = false;
        }
        if (!allZero(kJump.bytes.data(), 5U)) {
            allIllegalZeroed = false;
        }
        if (kJump.displacement != kDelta) {
            allIllegalReported = false;
        }
    }
    s.expect(allIllegalRefused, L"every displacement outside the int32 range is refused");
    s.expect(allIllegalZeroed, L"no refused displacement leaves any byte behind");
    s.expect(allIllegalReported, L"every refused displacement is reported at its true value");
}

// ---------------------------------------------------------------------------
// FF25 far jump.
// ---------------------------------------------------------------------------
void testAbsoluteJumpEncoding(ksword_tests::Suite& s) {
    // For a target with all eight bytes distinct, lock the order byte-by-byte.
    const auto kJump = encodeAbsoluteJump(0x0123456789ABCDEFULL);
    s.expect(kJump.size() == 14U, L"an absolute jump occupies fourteen bytes");
    s.expect(kJump[0] == 0xFFU, L"byte 0 is the FF opcode");
    s.expect(kJump[1] == 0x25U, L"byte 1 is the RIP-relative ModRM byte");
    s.expect(kJump[2] == 0x00U, L"disp32 byte 0 is zero");
    s.expect(kJump[3] == 0x00U, L"disp32 byte 1 is zero");
    s.expect(kJump[4] == 0x00U, L"disp32 byte 2 is zero");
    s.expect(kJump[5] == 0x00U, L"disp32 byte 3 is zero");
    s.expect(kJump[6] == 0xEFU, L"target byte 0 is the least significant byte");
    s.expect(kJump[7] == 0xCDU, L"target byte 1 follows in little-endian order");
    s.expect(kJump[8] == 0xABU, L"target byte 2 follows in little-endian order");
    s.expect(kJump[9] == 0x89U, L"target byte 3 follows in little-endian order");
    s.expect(kJump[10] == 0x67U, L"target byte 4 follows in little-endian order");
    s.expect(kJump[11] == 0x45U, L"target byte 5 follows in little-endian order");
    s.expect(kJump[12] == 0x23U, L"target byte 6 follows in little-endian order");
    s.expect(kJump[13] == 0x01U, L"target byte 7 is the most significant byte");

    // disp32 must be 0: the operand is the trailing 8 bytes. Any non-zero value targets elsewhere.
    s.expect(allZero(kJump.data() + 2U, 4U),
             L"the RIP-relative displacement is zero so the operand is the trailing eight bytes");

    const auto kZeroTarget = encodeAbsoluteJump(0ULL);
    const std::array<std::uint8_t, 14> kZeroWant = {
        0xFFU, 0x25U, 0x00U, 0x00U, 0x00U, 0x00U,
        0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U,
    };
    s.expect(kZeroTarget == kZeroWant, L"a zero target encodes as FF 25 and eight zero bytes");

    const auto kAllOnes = encodeAbsoluteJump(0xFFFFFFFFFFFFFFFFULL);
    const std::array<std::uint8_t, 14> kAllOnesWant = {
        0xFFU, 0x25U, 0x00U, 0x00U, 0x00U, 0x00U,
        0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU,
    };
    s.expect(kAllOnes == kAllOnesWant, L"an all-ones target fills only the trailing eight bytes");

    // Target with only the top bit set: only byte 13 is 0x80, the other seven address bytes
    // are all zero. Writing the shift as 32-bit would discard the entire high half here.
    const auto kHighBit = encodeAbsoluteJump(0x8000000000000000ULL);
    s.expect(kHighBit[13] == 0x80U && allZero(kHighBit.data() + 6U, 7U),
             L"a target with only the top bit set survives the full 64-bit shift");
    // For targets with only the low 32 bits: the high four address bytes must be zero and must not be sign-extended to FF.
    const auto kLowHalf = encodeAbsoluteJump(0x00000000FFFFFFFFULL);
    s.expect(kLowHalf[6] == 0xFFU && kLowHalf[7] == 0xFFU && kLowHalf[8] == 0xFFU &&
                 kLowHalf[9] == 0xFFU && allZero(kLowHalf.data() + 10U, 4U),
             L"a 32-bit target is zero extended rather than sign extended");

    // A real kernel address shape: 0xFFFFF80312345678 in little-endian is 78 56 34 12 03 F8 FF FF.
    const auto kKernel = encodeAbsoluteJump(0xFFFFF80312345678ULL);
    const std::array<std::uint8_t, 14> kKernelWant = {
        0xFFU, 0x25U, 0x00U, 0x00U, 0x00U, 0x00U,
        0x78U, 0x56U, 0x34U, 0x12U, 0x03U, 0xF8U, 0xFFU, 0xFFU,
    };
    s.expect(kKernel == kKernelWant, L"a kernel-shaped target encodes little endian in full");
    s.expect(readAbsoluteTarget(kKernel) == 0xFFFFF80312345678ULL,
             L"the encoded kernel target reads back bit for bit");

    // Target sweep: first six bytes are constant, last eight bytes are precisely restored.
    const std::uint64_t kTargets[] = {
        0ULL, 1ULL, 0xFFULL, 0x100ULL, 0x80000000ULL, 0x100000000ULL,
        0x00007FFFFFFFF000ULL, 0xFFFF800000000000ULL, 0xFFFFF80000001000ULL,
        0xFFFFFFFFFFFFFFFFULL, 0x8000000000000000ULL, 0x0123456789ABCDEFULL,
    };
    bool prefixStable = true;
    bool targetsRoundTrip = true;
    for (const std::uint64_t kTarget : kTargets) {
        const auto kEncoded = encodeAbsoluteJump(kTarget);
        if (kEncoded[0] != 0xFFU || kEncoded[1] != 0x25U || !allZero(kEncoded.data() + 2U, 4U)) {
            prefixStable = false;
        }
        if (readAbsoluteTarget(kEncoded) != kTarget) {
            targetsRoundTrip = false;
        }
    }
    s.expect(prefixStable, L"the six-byte prefix never depends on the target");
    s.expect(targetsRoundTrip, L"every target reads back bit for bit");

    // The two differ only in the last 8 bytes of the target.
    const auto kA = encodeAbsoluteJump(0xFFFFF80000001000ULL);
    const auto kB = encodeAbsoluteJump(0xFFFFF80000002000ULL);
    bool differsOnlyInTarget = true;
    for (std::uint32_t i = 0U; i < 6U; ++i) {
        if (kA[i] != kB[i]) {
            differsOnlyInTarget = false;
        }
    }
    s.expect(differsOnlyInTarget && kA != kB,
             L"two different targets differ only in the trailing eight bytes");
}

// ---------------------------------------------------------------------------
// Combined: encode the jump and place it into one page.
// ---------------------------------------------------------------------------
void testJumpPatchesInPage(ksword_tests::Suite& s) {
    const Page kOriginal = makeOriginal(0U);
    const std::uint64_t kPageVa = 0xFFFFF80000010000ULL;

    // Far jump installed at the last valid start point.
    const auto kFarJump = encodeAbsoluteJump(0xFFFFF80312345678ULL);
    const ComposedPage kFarAtLast = composePage(kOriginal.data(), 4082U, kFarJump.data(), 14U);
    const ComposedPage kFarPastEnd = composePage(kOriginal.data(), 4083U, kFarJump.data(), 14U);
    s.expect(kFarAtLast.ok(), L"a 14-byte absolute jump is accepted at offset 4082");
    s.expect(patchLanded(kFarAtLast, kFarJump.data(), 4082U, 14U),
             L"the absolute jump bytes land unchanged inside the page");
    s.expect(outsidePatchMatchesOriginal(kFarAtLast, kOriginal, 4082U, 14U),
             L"the shadow page equals the original outside the absolute jump");
    s.expect(kFarPastEnd.status == PatchComposeStatus::kCrossesPageBoundary,
             L"the same absolute jump one byte later is refused rather than split in two views");

    // Near jump: src is the virtual address of the patch within the page; target is 0x100 bytes after the same page.
    const std::uint64_t kSrcVa = kPageVa + 4091ULL;
    const std::uint64_t kTargetVa = kPageVa + 0x10000ULL;
    // Manual calculation: next = pageVa + 4096 = pageVa + 0x1000, displacement = 0x10000 - 0x1000 = 0xF000.
    const Rel32Jump kNearJump = encodeRel32Jump(kSrcVa, kTargetVa);
    s.expect(kNearJump.ok() && kNearJump.displacement == 0xF000,
             L"a near jump from the page tail measures from the first byte of the next page");
    const ComposedPage kNearAtLast = composePage(kOriginal.data(), 4091U, kNearJump.bytes.data(), 5U);
    const ComposedPage kNearPastEnd = composePage(kOriginal.data(), 4092U, kNearJump.bytes.data(), 5U);
    s.expect(kNearAtLast.ok() && patchLanded(kNearAtLast, kNearJump.bytes.data(), 4091U, 5U),
             L"a 5-byte near jump is accepted at offset 4091 and lands there");
    s.expect(outsidePatchMatchesOriginal(kNearAtLast, kOriginal, 4091U, 5U),
             L"the shadow page equals the original outside the near jump");
    s.expect(kNearPastEnd.status == PatchComposeStatus::kCrossesPageBoundary,
             L"the same near jump one byte later is refused");

    // Shadow page invariant: the number of bytes differing from the original page must not exceed the patch length.
    std::uint32_t differing = 0U;
    for (std::uint32_t i = 0U; i < 4096U; ++i) {
        if (kFarAtLast.bytes[i] != kOriginal[i]) {
            ++differing;
        }
    }
    s.expect(differing <= 14U,
             L"a shadow page differs from the original in at most the patched bytes");

    // Rationale for far jumps: when module spacing exceeds ±2 GiB, relative jumps have no valid range.
    const std::uint64_t kFarTarget = kPageVa + (8ULL << 30U);  // Beyond 8 GiB
    const Rel32Jump kTooFar = encodeRel32Jump(kSrcVa, kFarTarget);
    const auto kReachable = encodeAbsoluteJump(kFarTarget);
    s.expect(!kTooFar.ok(), L"a target 8 GiB away has no near-jump encoding");
    s.expect(readAbsoluteTarget(kReachable) == kFarTarget,
             L"the absolute form reaches the same target the near jump could not");
    s.expect(composePage(kOriginal.data(), 4082U, kReachable.data(), 14U).ok(),
             L"the absolute form still fits in the page it patches");

    // Both forms are usable for targets reachable by a near jump — this is a prerequisite for upper-layer selection, not an either/or choice.
    const std::uint64_t kNearTarget = kPageVa + 0x1000ULL;
    s.expect(encodeRel32Jump(kSrcVa, kNearTarget).ok() &&
                 readAbsoluteTarget(encodeAbsoluteJump(kNearTarget)) == kNearTarget,
             L"a nearby target encodes both ways so the caller really has a choice");
}

} // namespace

int runHookPatchComposeTests() {
    ksword_tests::Suite suite(L"HOOK patch compose");
    testArchitecturalLiterals(suite);
    testStatusNames(suite);
    testCrossPageGeometry(suite);
    testComposeGeometryAndOrder(suite);
    testExactFitLengths(suite);
    testComposedBytes(suite);
    testRel32Encoding(suite);
    testAbsoluteJumpEncoding(suite);
    testJumpPatchesInPage(suite);
    suite.report();
    return suite.failures();
}
