# Running in guest: start hidden mode resident -> take baseline -> launch VMware VM -> collect readings.
#
# Append to C:\ksword\vmwarerun.log and close the handle immediately at each step; the last entry remains when the entire machine hangs.
# Logs are the scene of the crime — failure on this line results in a BSOD, which wipes the memory buffers.
$log = 'C:\ksword\vmwarerun.log'
function Note($s) {
    $line = ('[{0:HH:mm:ss}] {1}' -f (Get-Date), $s)
    [IO.File]::AppendAllText($log, $line + [Environment]::NewLine)
}
function Run($a) {
    $o = 'C:\ksword\ro.txt'
    $e = 'C:\ksword\re.txt'
    $p = Start-Process 'C:\ksword\hvm_ctl.exe' -ArgumentList $a -NoNewWindow -Wait -PassThru -RedirectStandardOutput $o -RedirectStandardError $e
    $out = ''
    if (Test-Path $o) { $out = [IO.File]::ReadAllText($o) }
    return @{ Exit = $p.ExitCode; Out = $out }
}

[IO.File]::WriteAllText($log, '')
Note '=== Start ==='

$r = Run @('--json','status')
$st = $null
try { $st = $r.Out | ConvertFrom-Json } catch { }
Note ('status exit=' + $r.Exit + ' status bit=' + ($st.stateNames -join ' '))

# If resident mode is already running, stop it first. 'nested' and 'hidehv' are identical in status bits; reuse one from an unknown source.
# Resident: equivalent to running the entire measurement in an unselected mode and reporting the reading.
if ($st.stateNames -contains 'RESIDENT_ACTIVE') {
    $r = Run @('stop'); Note ('stop (clear the resident hypervisor whose mode is unknown) exit=' + $r.Exit)
    $r = Run @('--json','status')
    try { $st = $r.Out | ConvertFrom-Json } catch { }
}
if ($st.stateNames -contains 'FAULTED' -or $st.stateNames -contains 'ROLLBACK_REQUIRED') {
    $r = Run @('reset-fault'); Note ('reset-fault exit=' + $r.Exit)
}
if (-not ($st.stateNames -contains 'RESOURCES_READY')) {
    $r = Run @('prepare'); Note ('prepare exit=' + $r.Exit)
    $r = Run @('--json','status')
    try { $st = $r.Out | ConvertFrom-Json } catch { }
}
if (-not ($st.stateNames -contains 'SELF_TEST_PASSED')) {
    $r = Run @('self-test'); Note ('self-test exit=' + $r.Exit)
    $r = Run @('--json','status')
    try { $st = $r.Out | ConvertFrom-Json } catch { }
}
Note ('State bits before becoming resident ' + ($st.stateNames -join ' '))
$r = Run @('resident-nested-hidehv')
Note ('resident-nested-hidehv exit=' + $r.Exit)
if ($r.Exit -ne 0) { Note 'Resident hypervisor failed to start, stopping'; exit 1 }

$r = Run @('--json','cpuid-view')
Note ('cpuid-view ' + $r.Out.Trim())

$r = Run @('--json','status')
[IO.File]::WriteAllText('C:\ksword\base.json', $r.Out)
$b = $null
try { $b = $r.Out | ConvertFrom-Json } catch { }
Note ('baseline vmExits=' + $b.vmExitCount + ' denied=' + $b.nestedL2LaunchRefusedCount + ' fuse=' + $b.nestedFuseTripCount)

# The tested virtual machine is the one created by VMware's own wizard.
#
# The previous run used a hand-written .vmx with the CD-ROM attached to IDE, no disk controller, and no USB HID devices,
# The result was `Operating System not found`—a failure completely outside the virtualization chain, yet
# Spent a long time troubleshooting this as a link failure. The VM generated by the wizard, using the same ISO and residing in the same persistent location, boots successfully.
# isolinux menu, so it is the known good item on this line.
$vmDir = 'C:\Users\felix\Documents\Virtual Machines\Other Linux 6.x kernel 64-bit'
$vmLog = Join-Path $vmDir 'vmware.log'

foreach ($f in @($vmLog, 'C:\vmware\vmrun_start.txt')) {
    if (Test-Path $f) { [IO.File]::Delete($f) }
}
Get-ChildItem 'C:\Users\felix\AppData\Local\Temp\vmware-felix' -File -ErrorAction SilentlyContinue | ForEach-Object { try { [IO.File]::Delete($_.FullName) } catch { } }

# Force the VMware driver to re-sample the capability MSRs.
#
# vmx86.sys caches IA32_VMX_* values when the guest boots, before our resident component existed,
# Therefore, vmware-vmx receives the **original host capabilities** (measured as 0x48b=0x065018AE, which includes VPID
# And with an unrestricted guest, configuring the VMCS according to it will inevitably hit features we haven't implemented.
# Our capability filter is not wrong; it was never queried. Restarting this driver is the only way to force it to query again.
Note '--- Restart vmx86 to resample capability MSR ---'
foreach ($svc in @('VMAuthdService','VMwareHostd','VMnetDHCP','VMware NAT Service')) {
    $s = Get-Service -Name $svc -ErrorAction SilentlyContinue
    if ($s -and $s.Status -eq 'Running') { try { Stop-Service -Name $svc -Force -ErrorAction Stop; Note ('  Stop ' + $svc) } catch { Note ('  Stop ' + $svc + ' Failed: ' + $_.Exception.Message) } }
}
foreach ($drv in @('vmx86')) {
    $r1 = & sc.exe stop $drv 2>&1
    Start-Sleep -Seconds 2
    $r2 = & sc.exe start $drv 2>&1
    $st = (Get-Service -Name $drv -ErrorAction SilentlyContinue).Status
    Note ('  ' + $drv + '  Status after reboot=' + $st)
}
foreach ($svc in @('VMAuthdService')) {
    try { Start-Service -Name $svc -ErrorAction Stop; Note ('  Starting ' + $svc) } catch { Note ('  Starting ' + $svc + ' failed: ' + $_.Exception.Message) }
}

# Clear the lock directory left over from the previous round, **but only after confirming no vmware-vmx is running**.
#
# We rely on restarting the guest each round to unload the resident component. Since VMware is hard-powered off, lock directories remain in the VM directory.
# In the next vmrun cycle, it only returns `Error: Unknown error`, while sampling continues and readings are still output,
# The `vmx process count = 0` is hidden in a single line—this entire measurement cycle is unrelated to VMware.
#
# The gate must be here: last time I printed the process count but didn't use it for the check, directly deleting a **live** one.
# Locks held by vmware-vmx. Check first, then delete.
$live = @(Get-Process -Name 'vmware-vmx' -ErrorAction SilentlyContinue)
if ($live.Count -ne 0) {
    Note ('  There are ' + $live.Count + ' vmware-vmx processes running, do not lock the directory')
} else {
    $locks = @(Get-ChildItem -LiteralPath $vmDir -Filter '*.lck' -Directory -ErrorAction SilentlyContinue)
    foreach ($lock in $locks) {
        try { [IO.Directory]::Delete($lock.FullName, $true); Note ('  Delete residual lock ' + $lock.Name) }
        catch { Note ('  Failed to delete lock ' + $lock.Name + ': ' + $_.Exception.Message) }
    }
    if ($locks.Count -eq 0) { Note '  No residual lock directories' }
}

Note '>>> Start VMware virtual machine'
# Start-ScheduledTask performs a silent no-op when no interactive session is present — the previous run took a full 60 seconds.
# Sampling was performed on a VMware instance that was not started. Record the session first, then capture the actual execution after completion.
# Verify the retrieved time.
$expl = @(Get-Process -Name explorer -ErrorAction SilentlyContinue)
Note ('  Interactive desktop explorer=' + $expl.Count + ' session=' + $(if ($expl.Count) { $expl[0].SessionId } else { 'N/A' }))
$before = (Get-ScheduledTaskInfo -TaskName 'KswordVmStart').LastRunTime
Start-ScheduledTask -TaskName 'KswordVmStart'

# VMware crashed the machine within **2 seconds** after boot in the previous round, yielding no log lines. So, capture logs first.
# Resampling: it gives up faster than any sampling window, and its own logs are the only explanation for "why it gave up".
function DumpVmwareLogs($tag) {
    Note ('--- VMware log (' + $tag + ') ---')
    if (Test-Path 'C:\vmware\vmrun_start.txt') { Note ('  vmrun: ' + ([IO.File]::ReadAllText('C:\vmware\vmrun_start.txt')).Trim()) }
    if (Test-Path $vmLog) {
        (([IO.File]::ReadAllText($vmLog)) -split "`r?`n" |
            Select-String -Pattern 'Hyper-V|VT-x|VMX|MONITOR|Monitor Mode|msg\.|IOPL|not compatible|PowerOn|poweredOn|EPT|MMU|monitor|Failed|unsupported|Unsupported') |
            Select-Object -First 40 | ForEach-Object { Note ('  ' + $_) }
    } else { Note ' vmware.log does not exist yet' }
    $vx = Get-ChildItem 'C:\Users\felix\AppData\Local\Temp\vmware-felix' -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -match 'vmx' } | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($vx) {
        Note ('  --- ' + $vx.Name + ' ---')
        (([IO.File]::ReadAllText($vx.FullName)) -split "`r?`n" |
            Select-String -Pattern 'Hyper-V|VT-x|MONITOR|msg\.|IOPL|not compatible|Failed|monitor|MMU|unsupported') |
            Select-Object -First 30 | ForEach-Object { Note ('  ' + $_) }
    }
}

Start-Sleep -Seconds 8
DumpVmwareLogs '8 seconds after boot'

for ($i = 1; $i -le 6; $i++) {
    Start-Sleep -Seconds 5
    $r = Run @('--json','status')
    $s = $null
    try { $s = $r.Out | ConvertFrom-Json } catch { }
    $vmx = @(Get-Process -Name 'vmware-vmx' -ErrorAction SilentlyContinue)
    $rc = ($s.exitReasonCount.PSObject.Properties | Where-Object { [int]$_.Name -ge 19 -and [int]$_.Name -le 27 } | ForEach-Object { $_.Name + '=' + $_.Value }) -join ' '
    Note ('Sample' + $i + ' vmExits=' + $s.vmExitCount + ' Refused=' + $s.nestedL2LaunchRefusedCount + ' FuseTrip=' + $s.nestedFuseTripCount + ' LastError=' + $s.lastVmInstructionError + ' vmxProcess=' + $vmx.Count + ' VMXFamily[' + $rc + ']')
}

$r = Run @('--json','status')
[IO.File]::WriteAllText('C:\ksword\final.json', $r.Out)
Note '=== Sampling ended ==='

# Whether the task actually ran. If LastRunTime is unchanged, Start-ScheduledTask was a no-op.
# All readings in that round are unrelated to VMware — this check must be performed before reading the counter.
$after = (Get-ScheduledTaskInfo -TaskName 'KswordVmStart')
Note ('Task LastRunTime ' + $before + ' -> ' + $after.LastRunTime + ' LastTaskResult=0x' + ('{0:X}' -f $after.LastTaskResult))
if ($after.LastRunTime -eq $before) { Note '**Task did not execute —— unrelated to VMware this round**' }
# Task completion does not mean the VM started: vmrun can return `Error: Unknown error` while the task still counts as completed
# Executed. The criterion is whether the process exists, and this line must be prominent, not buried at the end of a sampling line.
if (@(Get-Process -Name 'vmware-vmx' -ErrorAction SilentlyContinue).Count -eq 0) {
    Note '**No vmware-vmx process found — all readings in this round are unrelated to VMware, do not draw conclusions based on this**'
}

DumpVmwareLogs 'Cleanup'

# Tail of the event loop; read in two calls.
#
# The previous version read in batches of 64 lines, up to 200 batches, spawning a new process for each batch—on a guest that is 50 times slower.
# That was a few minutes ago. We only need the last segment: first query the latest sequence number, then read once from 'latest minus N'.
Note '--- End of Event Ring ---'
$r = Run @('--json','events','0')
$head = $null
try { $head = $r.Out | ConvertFrom-Json } catch { }
if ($head -eq $null) {
    Note ('events header read failed exit=' + $r.Exit)
} else {
    $newest = [int64]$head.newestSequence
    $from = [Math]::Max(0, $newest - 400)
    Note ('newestSequence=' + $newest + ' available=' + $head.availableRows + ' dropped=' + $head.droppedRows + ' read from ' + $from + ' onward')
    $r = Run @('--json','events',"$from")
    [IO.File]::WriteAllText('C:\ksword\events.json', $r.Out)
    $ev = $null
    try { $ev = $r.Out | ConvertFrom-Json } catch { }
    if ($ev -ne $null) {
        Note ('Retrieving ' + $ev.returnedRows + ' rows')
        # Log only the specific rows to be processed in this round; leave the rest in events.json.
        foreach ($row in $ev.rows) {
            $rid = $row.ruleId
            if ($rid -eq $null) { continue }
            # This CLI's numeric fields may or may not have a 0x prefix; both formats must be recognized: those with the prefix
            # This is the only approach that correctly interprets '243' as decimal rather than 0x243 when the input is hexadecimal or lacks a prefix.
            $txt = ([string]$rid).Trim()
            if ($txt -match '^0[xX]') {
                $id = [Convert]::ToInt64($txt.Substring(2), 16)
            } else {
                $id = [int64]$txt
            }
            if ($id -lt 0xF3 -or $id -gt 0xF9) { continue }
            Note ('  rule=0x' + ('{0:X2}' -f $id) +
                ' reason=' + $row.exitReason +
                ' qual=' + $row.qualification +
                ' gpa=' + $row.guestPhysicalAddress +
                ' gla=' + $row.guestLinearAddress +
                ' rip=' + $row.guestRip +
                ' status=' + $row.status +
                ' cpu=' + $row.access)
        }
    } else {
        Note ('events tail read failed exit=' + $r.Exit)
    }
}
Note '=== Done ==='
