/*++

Module Name:

    research_topic_ioctl.c

Abstract:

    Read-only evidence orchestrator for the 'Second Plan' topic. This processor collects the
    current WDF/WDM request chain and CPU/time context, then verifies the actual R0 collection
    source for each topic in real-time via the central IOCTL registry. It never invokes
    modification processors and never guesses private layouts when DynData/PDB are missing.

Environment:

    Kernel-mode Driver Framework

--*/

#include "ark/ark_driver.h"
#include "ark/ark_ioctl.h"
#include "../../dispatch/ioctl_registry.h"

typedef struct KswResearchTopicDescriptor
{
    ULONG topicId;
    ULONG responseFlags;
    ULONG sourceMask;
    ULONG ioctlCount;
    ULONG ioctls[KSWORD_ARK_RESEARCH_MAX_TOPIC_IOCTLS];
} KswResearchTopicDescriptor;

#define KSW_TOPIC1(Id, Flags, Sources, A) \
    { Id, Flags, Sources, 1UL, { A, 0UL, 0UL, 0UL } }
#define KSW_TOPIC2(Id, Flags, Sources, A, B) \
    { Id, Flags, Sources, 2UL, { A, B, 0UL, 0UL } }
#define KSW_TOPIC3(Id, Flags, Sources, A, B, C) \
    { Id, Flags, Sources, 3UL, { A, B, C, 0UL } }
#define KSW_TOPIC4(Id, Flags, Sources, A, B, C, D) \
    { Id, Flags, Sources, 4UL, { A, B, C, D } }

#define KSW_RUNTIME_FLAGS \
    KSWORD_ARK_RESEARCH_RESPONSE_RUNTIME_DEPENDENT
#define KSW_CROSSVIEW_FLAGS \
    (KSW_RUNTIME_FLAGS | KSWORD_ARK_RESEARCH_RESPONSE_R3_CROSS_VIEW)
#define KSW_PRIVATE_FLAGS \
    (KSW_CROSSVIEW_FLAGS | KSWORD_ARK_RESEARCH_RESPONSE_DYNDATA_DEPENDENT | \
        KSWORD_ARK_RESEARCH_RESPONSE_PRIVATE_LAYOUT)
#define KSW_FIRMWARE_FLAGS \
    (KSW_RUNTIME_FLAGS | KSWORD_ARK_RESEARCH_RESPONSE_FIRMWARE_EVIDENCE)
#define KSW_PRIVACY_FLAGS \
    (KSW_CROSSVIEW_FLAGS | KSWORD_ARK_RESEARCH_RESPONSE_PRIVACY_GUARDED)

#define KSW_LIVE_SOURCES \
    (KSWORD_ARK_RESEARCH_SOURCE_PUBLIC_KERNEL_API | \
        KSWORD_ARK_RESEARCH_SOURCE_RUNTIME_SNAPSHOT)
#define KSW_PUBLIC_SOURCES \
    (KSW_LIVE_SOURCES | \
        KSWORD_ARK_RESEARCH_SOURCE_IOCTL_REGISTRY)
#define KSW_WDF_SOURCES \
    (KSW_PUBLIC_SOURCES | KSWORD_ARK_RESEARCH_SOURCE_WDF)
#define KSW_CROSSVIEW_SOURCES \
    (KSW_PUBLIC_SOURCES | KSWORD_ARK_RESEARCH_SOURCE_R3_PUBLIC_API)
#define KSW_PRIVATE_SOURCES \
    (KSW_CROSSVIEW_SOURCES | KSWORD_ARK_RESEARCH_SOURCE_DYNDATA_PDB)
#define KSW_FIRMWARE_SOURCES \
    (KSW_PUBLIC_SOURCES | KSWORD_ARK_RESEARCH_SOURCE_FIRMWARE)
#define KSW_EVENT_SOURCES \
    (KSW_CROSSVIEW_SOURCES | KSWORD_ARK_RESEARCH_SOURCE_EVENT_STREAM)

// Each row corresponds in order to a shared topic ID. The mapping only declares the real business entry point for that topic.
// Actual invocation is still initiated by the R3 typed wrapper or the corresponding page; this query does not serially trigger a scan.
static const KswResearchTopicDescriptor kGKswResearchTopics[] = {
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_EXECUTION_CHAIN, KSW_CROSSVIEW_FLAGS, KSW_WDF_SOURCES, IOCTL_KSWORD_ARK_QUERY_DRIVER_CAPABILITIES, IOCTL_KSWORD_ARK_QUERY_IOCTL_REGISTRY, IOCTL_KSWORD_ARK_QUERY_PROCESS_DETAIL),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_ADDRESS_SPACES, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_TRANSLATE_VIRTUAL_ADDRESS, IOCTL_KSWORD_ARK_QUERY_PAGE_TABLE_ENTRY, IOCTL_KSWORD_ARK_QUERY_SLAT_IOMMU_AUDIT),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_HANDLES_REFERENCES, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_ENUM_PROCESS_HANDLES, IOCTL_KSWORD_ARK_QUERY_HANDLE_OBJECT, IOCTL_KSWORD_ARK_QUERY_KERNEL_OBJECT_SUMMARY),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_STATUS_CODES, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_PREFLIGHT, IOCTL_KSWORD_ARK_QUERY_IOCTL_REGISTRY),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_IRQL_CONTEXT, KSW_RUNTIME_FLAGS, KSW_PUBLIC_SOURCES, IOCTL_KSWORD_ARK_ENUM_TIMER_DPC, IOCTL_KSWORD_ARK_ENUM_WORK_QUEUE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_SYNCHRONIZATION, KSW_RUNTIME_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_GET_CALLBACK_RUNTIME_STATE, IOCTL_KSWORD_ARK_ENUM_TIMER_DPC, IOCTL_KSWORD_ARK_ENUM_WORK_QUEUE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_DRIVER_LIFECYCLE, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_DRIVER_OBJECT, IOCTL_KSWORD_ARK_QUERY_UNLOADED_DRIVERS, IOCTL_KSWORD_ARK_QUERY_DRIVER_INTEGRITY),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_WDM_KMDF, KSW_RUNTIME_FLAGS, KSW_WDF_SOURCES, IOCTL_KSWORD_ARK_QUERY_PLATFORM_AUDIT, IOCTL_KSWORD_ARK_QUERY_DEVICE_STACK_AUDIT, IOCTL_KSWORD_ARK_QUERY_IOCTL_REGISTRY),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_IOCTL_CHAIN, KSW_RUNTIME_FLAGS, KSW_WDF_SOURCES, IOCTL_KSWORD_ARK_QUERY_IOCTL_REGISTRY, IOCTL_KSWORD_ARK_FILE_IRP_SUBMIT, IOCTL_KSWORD_ARK_QUERY_DRIVER_CAPABILITIES),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_DEBUGGING_DUMPS, KSW_RUNTIME_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_DEBUG_OUTPUT_DRAIN, IOCTL_KSWORD_ARK_CONFIGURE_BUGCHECK_GUARD, IOCTL_KSWORD_ARK_QUERY_SYSTEM_TIME),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_OBJECT_MANAGER, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_KERNEL_OBJECT_SUMMARY, IOCTL_KSWORD_ARK_ENUM_OBJECT_TYPE_TABLE, IOCTL_KSWORD_ARK_QUERY_HANDLE_OBJECT),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_OBJECT_DIRECTORIES, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_KERNEL_OBJECT_SUMMARY, IOCTL_KSWORD_ARK_ENUM_OBJECT_TYPE_TABLE),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_SYMBOLIC_LINKS, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_DEVICE_STACK_AUDIT, IOCTL_KSWORD_ARK_QUERY_KERNEL_OBJECT_SUMMARY),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_OBJECT_HEADER, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_HANDLE_OBJECT, IOCTL_KSWORD_ARK_ENUM_OBJECT_TYPE_TABLE, IOCTL_KSWORD_ARK_QUERY_KERNEL_OBJECT_SUMMARY),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_OBJECT_SECURITY, KSW_PRIVACY_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_HANDLE_OBJECT, IOCTL_KSWORD_ARK_QUERY_PROCESS_TOKEN_PRIVILEGES, IOCTL_KSWORD_ARK_QUERY_SECURITY_STATUS),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_PSP_CID_TABLE, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_ENUM_CID_TABLE, IOCTL_KSWORD_ARK_QUERY_PROCESS_CROSSVIEW, IOCTL_KSWORD_ARK_QUERY_THREAD_CROSSVIEW),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_CID_OBJECT_RELATIONS, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_ENUM_CID_TABLE, IOCTL_KSWORD_ARK_QUERY_PROCESS_DETAIL, IOCTL_KSWORD_ARK_QUERY_THREAD_DETAIL),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_HANDLE_TABLE_TABLECODE, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_ENUM_CID_TABLE, IOCTL_KSWORD_ARK_ENUM_PROCESS_HANDLES, IOCTL_KSWORD_ARK_QUERY_HANDLE_OBJECT),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_PROCESS_CROSS_VIEW, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_PROCESS_CROSSVIEW, IOCTL_KSWORD_ARK_ENUM_CID_TABLE, IOCTL_KSWORD_ARK_ENUM_PROCESS),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_PROCESS_VS_CID_HANDLES, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_ENUM_PROCESS_HANDLES, IOCTL_KSWORD_ARK_ENUM_CID_TABLE, IOCTL_KSWORD_ARK_QUERY_PROCESS_CROSSVIEW),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_CROSS_VIEW_VISUALIZATION, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_PROCESS_CROSSVIEW, IOCTL_KSWORD_ARK_QUERY_THREAD_CROSSVIEW, IOCTL_KSWORD_ARK_ENUM_CID_TABLE),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_EXECUTIVE_THREAD_OBJECTS, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_PROCESS_DETAIL, IOCTL_KSWORD_ARK_QUERY_THREAD_DETAIL),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_PROCESS_LIFECYCLE, KSW_PRIVATE_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_QUERY_PROCESS_CROSSVIEW, IOCTL_KSWORD_ARK_ENUM_CALLBACKS, IOCTL_KSWORD_ARK_QUERY_THREAD_CROSSVIEW),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_SCHEDULER, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_THREAD_DETAIL, IOCTL_KSWORD_ARK_QUERY_THREAD_RUNTIME_FIELDS, IOCTL_KSWORD_ARK_ENUM_WORK_QUEUE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_DISPATCHER_OBJECTS, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_ENUM_TIMER_DPC, IOCTL_KSWORD_ARK_ENUM_OBJECT_TYPE_TABLE, IOCTL_KSWORD_ARK_ENUM_WORK_QUEUE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_APC_DPC_WORK_ITEMS, KSW_PRIVATE_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_ENUM_TIMER_DPC, IOCTL_KSWORD_ARK_ENUM_WORK_QUEUE, IOCTL_KSWORD_ARK_QUERY_THREAD_DETAIL),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_PROCESS_ATTACH, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_VIRTUAL_MEMORY, IOCTL_KSWORD_ARK_QUERY_PROCESS_DETAIL),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_SESSION_SILO_PICO, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_WSL_SILO, IOCTL_KSWORD_ARK_QUERY_PROCESS_DETAIL, IOCTL_KSWORD_ARK_ENUM_PROCESS),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_PAGE_TABLES, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_TRANSLATE_VIRTUAL_ADDRESS, IOCTL_KSWORD_ARK_QUERY_PAGE_TABLE_ENTRY, IOCTL_KSWORD_ARK_QUERY_SLAT_IOMMU_AUDIT),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_PAGE_FAULT_WORKING_SET, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_PROCESS_RUNTIME_FIELDS, IOCTL_KSWORD_ARK_QUERY_VIRTUAL_MEMORY, IOCTL_KSWORD_ARK_SCAN_KERNEL_MEMORY_EVIDENCE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_VAD, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_VIRTUAL_MEMORY, IOCTL_KSWORD_ARK_QUERY_PROCESS_SECTION, IOCTL_KSWORD_ARK_SCAN_KERNEL_MEMORY_EVIDENCE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_PFN_DATABASE, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_TRANSLATE_VIRTUAL_ADDRESS, IOCTL_KSWORD_ARK_QUERY_PHYSICAL_MEMORY_LAYOUT, IOCTL_KSWORD_ARK_QUERY_SLAT_IOMMU_AUDIT),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_SECTION_CONTROL_AREA, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_PROCESS_SECTION, IOCTL_KSWORD_ARK_QUERY_FILE_SECTION_MAPPINGS, IOCTL_KSWORD_ARK_SCAN_KERNEL_MEMORY_EVIDENCE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_MDL_DMA, KSW_PRIVATE_FLAGS, KSW_FIRMWARE_SOURCES, IOCTL_KSWORD_ARK_SCAN_KERNEL_MEMORY_EVIDENCE, IOCTL_KSWORD_ARK_QUERY_SLAT_IOMMU_AUDIT, IOCTL_KSWORD_ARK_QUERY_PLATFORM_AUDIT),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_POOL, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_SCAN_KERNEL_EXECUTABLE_MEMORY, IOCTL_KSWORD_ARK_SCAN_KERNEL_MEMORY_EVIDENCE),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_EXECUTABLE_MEMORY_EVIDENCE, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_SCAN_KERNEL_EXECUTABLE_MEMORY, IOCTL_KSWORD_ARK_SCAN_KERNEL_MEMORY_EVIDENCE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_IRP_LIFECYCLE, KSW_RUNTIME_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_FILE_IRP_SUBMIT, IOCTL_KSWORD_ARK_FILE_MONITOR_QUERY_STATUS, IOCTL_KSWORD_ARK_FILE_MONITOR_DRAIN),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_DRIVER_DEVICE_FILE_OBJECTS, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_DRIVER_OBJECT, IOCTL_KSWORD_ARK_QUERY_DEVICE_STACK_AUDIT, IOCTL_KSWORD_ARK_QUERY_FILE_INFO),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_MINIFILTER, KSW_RUNTIME_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_QUERY_MINIFILTER_INVENTORY, IOCTL_KSWORD_ARK_ENUM_CALLBACKS),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_CACHE_MEMORY_MANAGER, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_FILE_SECTION_MAPPINGS, IOCTL_KSWORD_ARK_QUERY_PROCESS_SECTION, IOCTL_KSWORD_ARK_QUERY_FILE_INFO),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_FILESYSTEMS, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_FILESYSTEM_INTEGRITY_AUDIT, IOCTL_KSWORD_ARK_QUERY_VOLUME_STACK_AUDIT, IOCTL_KSWORD_ARK_QUERY_RAW_DISK_BACKEND),
    KSW_TOPIC4(KSWORD_ARK_RESEARCH_TOPIC_STORAGE_STACK, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_VOLUME_STACK_AUDIT, IOCTL_KSWORD_ARK_QUERY_MOUNTMGR_MAPPING_AUDIT, IOCTL_KSWORD_ARK_QUERY_RAW_DISK_BACKEND, IOCTL_KSWORD_ARK_QUERY_BITLOCKER_FVE_AUDIT),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_NETWORK_REDIRECTOR, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_DEVICE_STACK_AUDIT, IOCTL_KSWORD_ARK_NETWORK_QUERY_TCP_ENDPOINTS, IOCTL_KSWORD_ARK_QUERY_IPC_SUMMARY),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_REGISTRY_VIEWS, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_READ_REGISTRY_VALUE, IOCTL_KSWORD_ARK_ENUM_REGISTRY_KEY),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_CONFIGURATION_MANAGER, KSW_PRIVATE_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_ENUM_REGISTRY_KEY, IOCTL_KSWORD_ARK_ENUM_CALLBACKS, IOCTL_KSWORD_ARK_GET_CALLBACK_RUNTIME_STATE),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_REGISTRY_CALLBACKS, KSW_PRIVATE_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_ENUM_CALLBACKS, IOCTL_KSWORD_ARK_GET_CALLBACK_RUNTIME_STATE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_REGISTRY_TRANSACTIONS, KSW_PRIVATE_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_ENUM_REGISTRY_KEY, IOCTL_KSWORD_ARK_GET_CALLBACK_RUNTIME_STATE, IOCTL_KSWORD_ARK_QUERY_SYSTEM_TIME),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_TOKEN, KSW_PRIVACY_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_PROCESS_TOKEN_PRIVILEGES, IOCTL_KSWORD_ARK_QUERY_PROCESS_DETAIL, IOCTL_KSWORD_ARK_QUERY_SECURITY_STATUS),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_AUTHENTICATION_STACK, KSW_PRIVACY_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_SECURITY_STATUS, IOCTL_KSWORD_ARK_QUERY_APP_CONTROL_STATUS, IOCTL_KSWORD_ARK_QUERY_IMAGE_TRUST),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_PROTECTED_PROCESS, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_PROCESS_DETAIL, IOCTL_KSWORD_ARK_ENUM_PROCESS, IOCTL_KSWORD_ARK_QUERY_SECURITY_STATUS),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_CODE_INTEGRITY, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_SECURITY_STATUS, IOCTL_KSWORD_ARK_QUERY_DRIVER_INTEGRITY, IOCTL_KSWORD_ARK_QUERY_IMAGE_TRUST),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_VBS_HVCI, KSW_FIRMWARE_FLAGS, KSW_FIRMWARE_SOURCES, IOCTL_KSWORD_ARK_QUERY_SECURITY_STATUS, IOCTL_KSWORD_ARK_QUERY_HYPERV_SUMMARY, IOCTL_KSWORD_ARK_QUERY_SLAT_IOMMU_AUDIT),
    KSW_TOPIC4(KSWORD_ARK_RESEARCH_TOPIC_PATCHGUARD, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_CPU_HARDWARE, IOCTL_KSWORD_ARK_QUERY_DRIVER_INTEGRITY, IOCTL_KSWORD_ARK_SCAN_INLINE_HOOKS, IOCTL_KSWORD_ARK_ENUM_TIMER_DPC),
    KSW_TOPIC4(KSWORD_ARK_RESEARCH_TOPIC_NETWORK_STACK, KSW_CROSSVIEW_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_NETWORK_QUERY_TCP_ENDPOINTS, IOCTL_KSWORD_ARK_NETWORK_QUERY_UDP_ENDPOINTS, IOCTL_KSWORD_ARK_NETWORK_QUERY_WFP_INVENTORY, IOCTL_KSWORD_ARK_NETWORK_QUERY_NDIS_CHAIN),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_WFP_NDIS, KSW_RUNTIME_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_NETWORK_QUERY_WFP_INVENTORY, IOCTL_KSWORD_ARK_NETWORK_QUERY_NDIS_CHAIN),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_AFD_NSI, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_NETWORK_QUERY_TCP_ENDPOINTS, IOCTL_KSWORD_ARK_NETWORK_QUERY_UDP_ENDPOINTS, IOCTL_KSWORD_ARK_NETWORK_QUERY_NDIS_CHAIN),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_ALPC, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_ALPC_PORT, IOCTL_KSWORD_ARK_QUERY_IPC_SUMMARY),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_IPC, KSW_PRIVATE_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_IPC_SUMMARY, IOCTL_KSWORD_ARK_QUERY_ALPC_PORT, IOCTL_KSWORD_ARK_QUERY_KERNEL_OBJECT_SUMMARY),
    KSW_TOPIC4(KSWORD_ARK_RESEARCH_TOPIC_WIN32K_GUI, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_WIN32K_WINDOWS, IOCTL_KSWORD_ARK_QUERY_WIN32K_GUI_THREADS, IOCTL_KSWORD_ARK_QUERY_WIN32K_HOOKS_PDB, IOCTL_KSWORD_ARK_QUERY_WIN32K_EVENT_HOOKS),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_PNP, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_DEVICE_STACK_AUDIT, IOCTL_KSWORD_ARK_QUERY_PLATFORM_AUDIT, IOCTL_KSWORD_ARK_QUERY_USB_TOPOLOGY_AUDIT),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_DEVICE_STACK, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_DEVICE_STACK_AUDIT, IOCTL_KSWORD_ARK_QUERY_DRIVER_OBJECT),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_ACPI_PCI, KSW_FIRMWARE_FLAGS, KSW_FIRMWARE_SOURCES, IOCTL_KSWORD_ARK_QUERY_PLATFORM_AUDIT, IOCTL_KSWORD_ARK_QUERY_SLAT_IOMMU_AUDIT, IOCTL_KSWORD_ARK_QUERY_DEVICE_STACK_AUDIT),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_USB_HID, KSW_CROSSVIEW_FLAGS, KSW_CROSSVIEW_SOURCES, IOCTL_KSWORD_ARK_QUERY_USB_TOPOLOGY_AUDIT, IOCTL_KSWORD_ARK_QUERY_INPUT_STACK_AUDIT, IOCTL_KSWORD_ARK_QUERY_I8042_AUDIT),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_GPU_TDR, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_QUERY_GPU_DISPLAY_WATCHDOG_AUDIT, IOCTL_KSWORD_ARK_QUERY_DEVICE_STACK_AUDIT),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_POWER_MANAGEMENT, KSW_FIRMWARE_FLAGS, KSW_FIRMWARE_SOURCES, IOCTL_KSWORD_ARK_QUERY_CPU_POWER, IOCTL_KSWORD_ARK_QUERY_PLATFORM_AUDIT, IOCTL_KSWORD_ARK_QUERY_DEVICE_STACK_AUDIT),
    KSW_TOPIC2(KSWORD_ARK_RESEARCH_TOPIC_CALLBACKS, KSW_PRIVATE_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_ENUM_CALLBACKS, IOCTL_KSWORD_ARK_GET_CALLBACK_RUNTIME_STATE),
    KSW_TOPIC3(KSWORD_ARK_RESEARCH_TOPIC_EXTERNAL_CALLBACKS, KSW_PRIVATE_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_ENUM_CALLBACKS, IOCTL_KSWORD_ARK_QUERY_MINIFILTER_INVENTORY, IOCTL_KSWORD_ARK_NETWORK_QUERY_WFP_INVENTORY),
    KSW_TOPIC4(KSWORD_ARK_RESEARCH_TOPIC_HOOK_EVIDENCE, KSW_PRIVATE_FLAGS, KSW_PRIVATE_SOURCES, IOCTL_KSWORD_ARK_SCAN_INLINE_HOOKS, IOCTL_KSWORD_ARK_ENUM_IAT_EAT_HOOKS, IOCTL_KSWORD_ARK_ENUM_SSDT, IOCTL_KSWORD_ARK_ENUM_SHADOW_SSDT),
    KSW_TOPIC4(KSWORD_ARK_RESEARCH_TOPIC_CPU_CONTROL_STATE, KSW_FIRMWARE_FLAGS, KSW_FIRMWARE_SOURCES, IOCTL_KSWORD_ARK_QUERY_CPU_HARDWARE, IOCTL_KSWORD_ARK_QUERY_SLAT_IOMMU_AUDIT, IOCTL_KSWORD_ARK_QUERY_PLATFORM_AUDIT, IOCTL_KSWORD_ARK_QUERY_HVM),
    KSW_TOPIC4(KSWORD_ARK_RESEARCH_TOPIC_TRACING, KSW_PRIVACY_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_DEBUG_OUTPUT_DRAIN, IOCTL_KSWORD_ARK_WAIT_CALLBACK_EVENT, IOCTL_KSWORD_ARK_FILE_MONITOR_DRAIN, IOCTL_KSWORD_ARK_NETWORK_QUERY_WFP_EVENTS),
    KSW_TOPIC4(KSWORD_ARK_RESEARCH_TOPIC_EVIDENCE_TIMELINE, KSW_CROSSVIEW_FLAGS, KSW_EVENT_SOURCES, IOCTL_KSWORD_ARK_QUERY_SYSTEM_TIME, IOCTL_KSWORD_ARK_QUERY_PROCESS_CROSSVIEW, IOCTL_KSWORD_ARK_QUERY_THREAD_CROSSVIEW, IOCTL_KSWORD_ARK_MUTATION_QUERY_AUDIT)
};

#undef KSW_TOPIC4
#undef KSW_TOPIC3
#undef KSW_TOPIC2
#undef KSW_TOPIC1

C_ASSERT(RTL_NUMBER_OF(kGKswResearchTopics) == KSWORD_ARK_RESEARCH_TOPIC_COUNT);
C_ASSERT(sizeof(KSWORD_ARK_QUERY_RESEARCH_TOPIC_REQUEST) == 24UL);
C_ASSERT(sizeof(KSWORD_ARK_RESEARCH_EVIDENCE_ENTRY) == 184UL);
C_ASSERT(KSWORD_ARK_RESEARCH_RESPONSE_HEADER_SIZE == 168UL);
C_ASSERT(KSWORD_ARK_RESEARCH_MAX_TOTAL_ENTRIES <=
    KSWORD_ARK_RESEARCH_HARD_MAX_ENTRIES);

static
const KswResearchTopicDescriptor*
kswResearchFindTopic(
    _In_ ULONG topicId
    )
{
    if (topicId == 0UL || topicId > RTL_NUMBER_OF(kGKswResearchTopics)) {
        return NULL;
    }
    if (kGKswResearchTopics[topicId - 1UL].topicId != topicId) {
        return NULL;
    }
    return &kGKswResearchTopics[topicId - 1UL];
}

static
VOID
kswResearchCopyName(
    _Out_writes_(capacity) CHAR* destination,
    _In_ SIZE_T capacity,
    _In_opt_z_ const CHAR* source
    )
{
    SIZE_T index = 0U;

    if (destination == NULL || capacity == 0U) {
        return;
    }
    RtlZeroMemory(destination, capacity);
    if (source == NULL) {
        return;
    }
    while (index + 1U < capacity && source[index] != '\0') {
        destination[index] = source[index];
        ++index;
    }
}

static
VOID
kswResearchInitializeEntry(
    _Out_ KSWORD_ARK_RESEARCH_EVIDENCE_ENTRY* entry,
    _In_ ULONG kind,
    _In_ ULONG sourceMask,
    _In_ ULONG fieldId,
    _In_z_ const CHAR* name
    )
{
    RtlZeroMemory(entry, sizeof(*entry));
    entry->size = sizeof(*entry);
    entry->kind = kind;
    entry->sourceMask = sourceMask;
    entry->state = KSWORD_ARK_RESEARCH_EVIDENCE_AVAILABLE;
    entry->confidence = KSWORD_ARK_RESEARCH_CONFIDENCE_RUNTIME;
    entry->fieldId = fieldId;
    entry->lastStatus = STATUS_SUCCESS;
    kswResearchCopyName(entry->name, RTL_NUMBER_OF(entry->name), name);
}

NTSTATUS
kswordArkResearchIoctlQueryTopic(
    _In_ WDFDEVICE device,
    _In_ WDFREQUEST request,
    _In_ size_t inputBufferLength,
    _In_ size_t outputBufferLength,
    _Out_ size_t* bytesReturned
    )
{
    PVOID inputBuffer = NULL;
    PVOID outputBuffer = NULL;
    SIZE_T actualInputLength = 0U;
    SIZE_T actualOutputLength = 0U;
    SIZE_T effectiveOutputLength = 0U;
    KSWORD_ARK_QUERY_RESEARCH_TOPIC_REQUEST requestSnapshot = { 0 };
    KSWORD_ARK_QUERY_RESEARCH_TOPIC_RESPONSE* response = NULL;
    KSWORD_ARK_RESEARCH_EVIDENCE_ENTRY localEntries[KSWORD_ARK_RESEARCH_HARD_MAX_ENTRIES] = { 0 };
    const KswResearchTopicDescriptor* descriptor = NULL;
    PDEVICE_OBJECT deviceObject = NULL;
    PDEVICE_OBJECT topDeviceObject = NULL;
    PDRIVER_OBJECT driverObject = NULL;
    PROCESSOR_NUMBER processorNumber = { 0 };
    LARGE_INTEGER systemTime = { 0 };
    LARGE_INTEGER performanceFrequency = { 0 };
    LARGE_INTEGER performanceCounter = { 0 };
    ULONGLONG interruptTime = 0ULL;
    PHYSICAL_ADDRESS devicePhysicalAddress = { 0 };
    KPROCESSOR_MODE requestorMode = KernelMode;
    KIRQL currentIrql = PASSIVE_LEVEL;
    ULONG activeGroupCount = 0UL;
    ULONG activeProcessorCount = 0UL;
    ULONG requestorProcessId = 0UL;
    ULONG requestorThreadId = 0UL;
    ULONG entryCount = 0UL;
    ULONG requestedEntries = 0UL;
    ULONG outputCapacity = 0UL;
    ULONG returnedEntries = 0UL;
    ULONG missingSources = 0UL;
    ULONG index = 0UL;
    NTSTATUS status = STATUS_SUCCESS;

    if (bytesReturned == NULL) {
        return STATUS_INVALID_PARAMETER;
    }
    *bytesReturned = 0U;

    status = WdfRequestRetrieveInputBuffer(
        request,
        sizeof(KSWORD_ARK_QUERY_RESEARCH_TOPIC_REQUEST),
        &inputBuffer,
        &actualInputLength);
    if (!NT_SUCCESS(status) ||
        inputBufferLength < sizeof(KSWORD_ARK_QUERY_RESEARCH_TOPIC_REQUEST) ||
        actualInputLength < sizeof(KSWORD_ARK_QUERY_RESEARCH_TOPIC_REQUEST)) {
        return NT_SUCCESS(status) ? STATUS_INFO_LENGTH_MISMATCH : status;
    }
    RtlCopyMemory(&requestSnapshot, inputBuffer, sizeof(requestSnapshot));
    if (requestSnapshot.size != sizeof(requestSnapshot) ||
        requestSnapshot.version != KSWORD_ARK_RESEARCH_PROTOCOL_VERSION ||
        requestSnapshot.flags != 0UL ||
        requestSnapshot.reserved != 0UL) {
        return STATUS_REVISION_MISMATCH;
    }

    descriptor = kswResearchFindTopic(requestSnapshot.topicId);
    if (descriptor == NULL) {
        return STATUS_INVALID_PARAMETER;
    }

    status = WdfRequestRetrieveOutputBuffer(
        request,
        KSWORD_ARK_RESEARCH_RESPONSE_HEADER_SIZE,
        &outputBuffer,
        &actualOutputLength);
    if (!NT_SUCCESS(status) ||
        outputBufferLength < KSWORD_ARK_RESEARCH_RESPONSE_HEADER_SIZE ||
        actualOutputLength < KSWORD_ARK_RESEARCH_RESPONSE_HEADER_SIZE) {
        return NT_SUCCESS(status) ? STATUS_BUFFER_TOO_SMALL : status;
    }
    effectiveOutputLength = min(actualOutputLength, outputBufferLength);
    RtlZeroMemory(outputBuffer, effectiveOutputLength);
    response = (KSWORD_ARK_QUERY_RESEARCH_TOPIC_RESPONSE*)outputBuffer;

    deviceObject = WdfDeviceWdmGetDeviceObject(device);
    if (deviceObject != NULL) {
        driverObject = deviceObject->DriverObject;
        topDeviceObject = IoGetAttachedDeviceReference(deviceObject);
        devicePhysicalAddress = MmGetPhysicalAddress(deviceObject);
    }
    requestorMode = WdfRequestGetRequestorMode(request);
    KeGetCurrentProcessorNumberEx(&processorNumber);
    currentIrql = KeGetCurrentIrql();
    activeGroupCount = KeQueryActiveGroupCount();
    activeProcessorCount = KeQueryActiveProcessorCountEx(ALL_PROCESSOR_GROUPS);
    requestorProcessId = HandleToULong(PsGetCurrentProcessId());
    requestorThreadId = HandleToULong(PsGetCurrentThreadId());
    KeQuerySystemTimePrecise(&systemTime);
    interruptTime = KeQueryInterruptTime();
    performanceCounter = KeQueryPerformanceCounter(&performanceFrequency);

    kswResearchInitializeEntry(
        &localEntries[entryCount],
        KSWORD_ARK_RESEARCH_ENTRY_REQUEST_CONTEXT,
        KSW_LIVE_SOURCES | KSWORD_ARK_RESEARCH_SOURCE_WDF,
        1UL,
        "request-context");
    localEntries[entryCount].value0 = requestorProcessId;
    localEntries[entryCount].value1 = requestorThreadId;
    localEntries[entryCount].value2 = (ULONG)requestorMode;
    localEntries[entryCount].value3 = (ULONG)requestorMode;
    ++entryCount;

    kswResearchInitializeEntry(
        &localEntries[entryCount],
        KSWORD_ARK_RESEARCH_ENTRY_PROCESSOR_CONTEXT,
        KSW_LIVE_SOURCES,
        2UL,
        "processor-context");
    localEntries[entryCount].value0 = (ULONG)currentIrql;
    localEntries[entryCount].value1 = processorNumber.Group;
    localEntries[entryCount].value2 = processorNumber.Number;
    localEntries[entryCount].value3 = activeProcessorCount;
    ++entryCount;

    kswResearchInitializeEntry(
        &localEntries[entryCount],
        KSWORD_ARK_RESEARCH_ENTRY_CLOCK_SNAPSHOT,
        KSW_LIVE_SOURCES,
        3UL,
        "clock-snapshot");
    localEntries[entryCount].value0 = (ULONGLONG)systemTime.QuadPart;
    localEntries[entryCount].value1 = interruptTime;
    localEntries[entryCount].value2 = (ULONGLONG)performanceCounter.QuadPart;
    localEntries[entryCount].value3 = (ULONGLONG)performanceFrequency.QuadPart;
    ++entryCount;

    kswResearchInitializeEntry(
        &localEntries[entryCount],
        KSWORD_ARK_RESEARCH_ENTRY_WDF_WDM_CHAIN,
        KSW_LIVE_SOURCES | KSWORD_ARK_RESEARCH_SOURCE_WDF,
        4UL,
        "wdf-wdm-chain");
    localEntries[entryCount].value0 = (ULONGLONG)(ULONG_PTR)driverObject;
    localEntries[entryCount].value1 = (ULONGLONG)(ULONG_PTR)deviceObject;
    localEntries[entryCount].value2 = (ULONGLONG)(ULONG_PTR)topDeviceObject;
    localEntries[entryCount].value3 = (ULONGLONG)devicePhysicalAddress.QuadPart;
    ++entryCount;

    for (index = 0UL; index < descriptor->ioctlCount; ++index) {
        const KswordArkIoctlEntry* registryEntry =
            kswordArkLookupIoctlEntry(descriptor->ioctls[index]);
        KSWORD_ARK_RESEARCH_EVIDENCE_ENTRY* evidence = &localEntries[entryCount];

        kswResearchInitializeEntry(
            evidence,
            KSWORD_ARK_RESEARCH_ENTRY_IOCTL_SOURCE,
            KSWORD_ARK_RESEARCH_SOURCE_IOCTL_REGISTRY,
            0x100UL + index,
            registryEntry != NULL ? registryEntry->name : "missing-ioctl-source");
        evidence->ioControlCode = descriptor->ioctls[index];
        evidence->functionNumber = (descriptor->ioctls[index] >> 2U) & 0xFFFUL;
        evidence->method = descriptor->ioctls[index] & 0x3UL;
        evidence->access = (descriptor->ioctls[index] >> 14U) & 0x3UL;
        evidence->confidence = KSWORD_ARK_RESEARCH_CONFIDENCE_REGISTRY;
        if (registryEntry != NULL) {
            evidence->registryFlags = registryEntry->flags;
            evidence->requiredCapability = registryEntry->requiredCapability;
            evidence->value0 = (ULONGLONG)(ULONG_PTR)registryEntry->handler;
            evidence->value1 = descriptor->sourceMask;
            evidence->value2 = descriptor->responseFlags;
        } else {
            evidence->state = KSWORD_ARK_RESEARCH_EVIDENCE_UNAVAILABLE;
            evidence->lastStatus = STATUS_NOT_FOUND;
            ++missingSources;
        }
        ++entryCount;
    }

    requestedEntries = requestSnapshot.maxEntries == 0UL
        ? KSWORD_ARK_RESEARCH_DEFAULT_MAX_ENTRIES
        : min(requestSnapshot.maxEntries, KSWORD_ARK_RESEARCH_HARD_MAX_ENTRIES);
    outputCapacity = (ULONG)((effectiveOutputLength - KSWORD_ARK_RESEARCH_RESPONSE_HEADER_SIZE) /
        sizeof(KSWORD_ARK_RESEARCH_EVIDENCE_ENTRY));
    returnedEntries = min(entryCount, min(requestedEntries, outputCapacity));

    response->size = KSWORD_ARK_RESEARCH_RESPONSE_HEADER_SIZE;
    response->version = KSWORD_ARK_RESEARCH_PROTOCOL_VERSION;
    response->topicId = descriptor->topicId;
    response->responseFlags = descriptor->responseFlags;
    response->totalCount = entryCount;
    response->returnedCount = returnedEntries;
    response->entrySize = sizeof(KSWORD_ARK_RESEARCH_EVIDENCE_ENTRY);
    response->registeredIoctlCount = kswordArkGetRegisteredIoctlCount();
    response->duplicateIoctlCount = kswordArkGetDuplicateIoctlCount();
    response->lastStatus = missingSources != 0UL
        ? STATUS_NOT_FOUND
        : (response->duplicateIoctlCount != 0UL
            ? STATUS_OBJECT_NAME_COLLISION
            : STATUS_SUCCESS);
    response->currentIrql = (ULONG)currentIrql;
    response->requestorMode = (ULONG)requestorMode;
    response->requestorModeMirror = (ULONG)requestorMode;
    response->processorGroup = processorNumber.Group;
    response->processorNumber = processorNumber.Number;
    response->activeGroupCount = activeGroupCount;
    response->activeProcessorCount = activeProcessorCount;
    response->requestorProcessId = requestorProcessId;
    response->requestorThreadId = requestorThreadId;
    response->systemTime100ns = (ULONGLONG)systemTime.QuadPart;
    response->interruptTime100ns = interruptTime;
    response->performanceCounter = (ULONGLONG)performanceCounter.QuadPart;
    response->performanceFrequency = (ULONGLONG)performanceFrequency.QuadPart;
    response->driverObjectAddress = (ULONGLONG)(ULONG_PTR)driverObject;
    response->driverImageBase = driverObject != NULL
        ? (ULONGLONG)(ULONG_PTR)driverObject->DriverStart
        : 0ULL;
    response->driverImageSize = driverObject != NULL
        ? driverObject->DriverSize
        : 0ULL;
    response->deviceObjectAddress = (ULONGLONG)(ULONG_PTR)deviceObject;
    response->topAttachedDeviceAddress = (ULONGLONG)(ULONG_PTR)topDeviceObject;
    response->deviceObjectPhysicalAddress = (ULONGLONG)devicePhysicalAddress.QuadPart;

    if (returnedEntries < entryCount) {
        response->responseFlags |= KSWORD_ARK_RESEARCH_RESPONSE_TRUNCATED;
    }

    if (missingSources != 0UL || response->duplicateIoctlCount != 0UL) {
        response->queryStatus = KSWORD_ARK_RESEARCH_STATUS_SOURCE_MISSING;
    } else if (returnedEntries < entryCount) {
        response->queryStatus = KSWORD_ARK_RESEARCH_STATUS_TRUNCATED;
    } else {
        response->queryStatus = KSWORD_ARK_RESEARCH_STATUS_OK;
    }

    if (returnedEntries != 0UL) {
        RtlCopyMemory(
            response->entries,
            localEntries,
            returnedEntries * sizeof(KSWORD_ARK_RESEARCH_EVIDENCE_ENTRY));
    }
    *bytesReturned = KSWORD_ARK_RESEARCH_RESPONSE_HEADER_SIZE +
        (returnedEntries * sizeof(KSWORD_ARK_RESEARCH_EVIDENCE_ENTRY));

    if (topDeviceObject != NULL) {
        ObDereferenceObject(topDeviceObject);
    }
    return STATUS_SUCCESS;
}

#undef KSW_EVENT_SOURCES
#undef KSW_FIRMWARE_SOURCES
#undef KSW_PRIVATE_SOURCES
#undef KSW_CROSSVIEW_SOURCES
#undef KSW_WDF_SOURCES
#undef KSW_PUBLIC_SOURCES
#undef KSW_LIVE_SOURCES
#undef KSW_PRIVACY_FLAGS
#undef KSW_FIRMWARE_FLAGS
#undef KSW_PRIVATE_FLAGS
#undef KSW_CROSSVIEW_FLAGS
#undef KSW_RUNTIME_FLAGS
