/*++

Module Name:

    dyndata_validate.c

Abstract:

    Field descriptor and capability-gating helpers for Ksword DynData.

Environment:

    Kernel-mode Driver Framework

--*/

#include "ark/ark_dyndata_fields.h"

#include <ntstrsafe.h>

typedef struct KswDynFieldBinding
{
    ULONG fieldId;
    PCSTR fieldName;
    PCSTR featureName;
    ULONG64 capabilityMask;
    BOOLEAN required;
    ULONG source;
    SIZE_T offsetInState;
} KswDynFieldBinding, *PkswDynFieldBinding;

#define KSW_FIELD_BINDING(FieldIdValue, FieldNameText, FeatureText, CapabilityValue, RequiredValue, SourceValue, MemberPath) \
    { FieldIdValue, FieldNameText, FeatureText, CapabilityValue, RequiredValue, SourceValue, FIELD_OFFSET(KswDynState, MemberPath) }

static const KswDynFieldBinding kGKswordDynFieldBindings[] = {
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_OBJECT_TABLE, "EpObjectTable", "Process HandleTable", KSW_CAP_PROCESS_OBJECT_TABLE | KSW_CAP_HANDLE_TABLE_DECODE, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.epObjectTable),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_SECTION_OBJECT, "EpSectionObject", "Section/ControlArea", KSW_CAP_SECTION_CONTROL_AREA, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.epSectionObject),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_UNIQUE_PROCESS_ID, "_EPROCESS.UniqueProcessId", "Process List Fields", KSW_CAP_PROCESS_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epUniqueProcessId),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_ACTIVE_PROCESS_LINKS, "_EPROCESS.ActiveProcessLinks", "Process List Fields", KSW_CAP_PROCESS_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epActiveProcessLinks),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_THREAD_LIST_HEAD, "_EPROCESS.ThreadListHead", "Process List Fields", KSW_CAP_PROCESS_LIST_FIELDS | KSW_CAP_THREAD_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epThreadListHead),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_IMAGE_FILE_NAME, "_EPROCESS.ImageFileName", "Process List Fields", KSW_CAP_PROCESS_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epImageFileName),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_TOKEN, "_EPROCESS.Token", "Process List Fields", KSW_CAP_PROCESS_LIST_FIELDS | KSW_CAP_TOKEN_INTEGRITY_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epToken),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_FLAGS, "_EPROCESS.Flags", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epFlags),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_FLAGS2, "_EPROCESS.Flags2", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epFlags2),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_RUNDOWN_PROTECT, "_EPROCESS.RundownProtect", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epRundownProtect),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PROCESS_LOCK, "_EPROCESS.ProcessLock", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epProcessLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_CREATE_TIME, "_EPROCESS.CreateTime", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epCreateTime),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_EXIT_TIME, "_EPROCESS.ExitTime", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epExitTime),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_EXIT_STATUS, "_EPROCESS.ExitStatus", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epExitStatus),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PEB, "_EPROCESS.Peb", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epPeb),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_SESSION, "_EPROCESS.Session", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epSession),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_WIN32_PROCESS, "_EPROCESS.Win32Process", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epWin32Process),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_WOW64_PROCESS, "_EPROCESS.WoW64Process", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epWow64Process),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_INHERITED_FROM_UNIQUE_PROCESS_ID, "_EPROCESS.InheritedFromUniqueProcessId", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epInheritedFromUniqueProcessId),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_SE_AUDIT_PROCESS_CREATION_INFO, "_EPROCESS.SeAuditProcessCreationInfo", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epSeAuditProcessCreationInfo),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_JOB, "_EPROCESS.Job", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epJob),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_DEVICE_MAP, "_EPROCESS.DeviceMap", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epDeviceMap),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_DEBUG_PORT, "_EPROCESS.DebugPort", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epDebugPort),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_EXCEPTION_PORT_DATA, "_EPROCESS.ExceptionPortData", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epExceptionPortData),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_SECTION_BASE_ADDRESS, "_EPROCESS.SectionBaseAddress", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epSectionBaseAddress),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_IMAGE_FILE_POINTER, "_EPROCESS.ImageFilePointer", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epImageFilePointer),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PRIORITY_CLASS, "_EPROCESS.PriorityClass", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epPriorityClass),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_ACTIVE_THREADS, "_EPROCESS.ActiveThreads", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epActiveThreads),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_VAD_ROOT, "_EPROCESS.VadRoot", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epVadRoot),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_VAD_HINT, "_EPROCESS.VadHint", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epVadHint),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_CLONE_ROOT, "_EPROCESS.CloneRoot", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epCloneRoot),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_NUMBER_OF_PRIVATE_PAGES, "_EPROCESS.NumberOfPrivatePages", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epNumberOfPrivatePages),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_NUMBER_OF_LOCKED_PAGES, "_EPROCESS.NumberOfLockedPages", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epNumberOfLockedPages),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_COMMIT_CHARGE, "_EPROCESS.CommitCharge", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epCommitCharge),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_COMMIT_CHARGE_PEAK, "_EPROCESS.CommitChargePeak", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epCommitChargePeak),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PEAK_VIRTUAL_SIZE, "_EPROCESS.PeakVirtualSize", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epPeakVirtualSize),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_VIRTUAL_SIZE, "_EPROCESS.VirtualSize", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epVirtualSize),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_SESSION_PROCESS_LINKS, "_EPROCESS.SessionProcessLinks", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epSessionProcessLinks),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_MITIGATION_FLAGS, "_EPROCESS.MitigationFlags", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epMitigationFlags),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_MITIGATION_FLAGS2, "_EPROCESS.MitigationFlags2", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epMitigationFlags2),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PROCESS_QUOTA_USAGE, "_EPROCESS.ProcessQuotaUsage", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epProcessQuotaUsage),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PROCESS_QUOTA_PEAK, "_EPROCESS.ProcessQuotaPeak", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epProcessQuotaPeak),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_ADDRESS_CREATION_LOCK, "_EPROCESS.AddressCreationLock", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epAddressCreationLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PAGE_TABLE_COMMITMENT_LOCK, "_EPROCESS.PageTableCommitmentLock", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epPageTableCommitmentLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_ROTATE_IN_PROGRESS, "_EPROCESS.RotateInProgress", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epRotateInProgress),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_FORK_IN_PROGRESS, "_EPROCESS.ForkInProgress", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epForkInProgress),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_COMMIT_CHARGE_JOB, "_EPROCESS.CommitChargeJob", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epCommitChargeJob),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_COOKIE, "_EPROCESS.Cookie", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epCookie),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_WORKING_SET_WATCH, "_EPROCESS.WorkingSetWatch", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epWorkingSetWatch),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_WIN32_WINDOW_STATION, "_EPROCESS.Win32WindowStation", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epWin32WindowStation),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_OWNER_PROCESS_ID, "_EPROCESS.OwnerProcessId", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epOwnerProcessId),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_QUOTA_BLOCK, "_EPROCESS.QuotaBlock", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epQuotaBlock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_ETW_DATA_SOURCE, "_EPROCESS.EtwDataSource", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epEtwDataSource),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PAGE_DIRECTORY_PTE, "_EPROCESS.PageDirectoryPte", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epPageDirectoryPte),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_SECURITY_PORT, "_EPROCESS.SecurityPort", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epSecurityPort),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_JOB_LINKS, "_EPROCESS.JobLinks", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epJobLinks),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_HIGHEST_USER_ADDRESS, "_EPROCESS.HighestUserAddress", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epHighestUserAddress),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_IMAGE_PATH_HASH, "_EPROCESS.ImagePathHash", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epImagePathHash),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_DEFAULT_HARD_ERROR_PROCESSING, "_EPROCESS.DefaultHardErrorProcessing", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epDefaultHardErrorProcessing),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_LAST_THREAD_EXIT_STATUS, "_EPROCESS.LastThreadExitStatus", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epLastThreadExitStatus),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PREFETCH_TRACE, "_EPROCESS.PrefetchTrace", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epPrefetchTrace),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_LOCKED_PAGES_LIST, "_EPROCESS.LockedPagesList", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epLockedPagesList),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_READ_OPERATION_COUNT, "_EPROCESS.ReadOperationCount", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epReadOperationCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_WRITE_OPERATION_COUNT, "_EPROCESS.WriteOperationCount", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epWriteOperationCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_OTHER_OPERATION_COUNT, "_EPROCESS.OtherOperationCount", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epOtherOperationCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_READ_TRANSFER_COUNT, "_EPROCESS.ReadTransferCount", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epReadTransferCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_WRITE_TRANSFER_COUNT, "_EPROCESS.WriteTransferCount", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epWriteTransferCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_OTHER_TRANSFER_COUNT, "_EPROCESS.OtherTransferCount", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epOtherTransferCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_COMMIT_CHARGE_LIMIT, "_EPROCESS.CommitChargeLimit", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epCommitChargeLimit),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_VM, "_EPROCESS.Vm", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epVm),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_MM_PROCESS_LINKS, "_EPROCESS.MmProcessLinks", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epMmProcessLinks),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_MODIFIED_PAGE_COUNT, "_EPROCESS.ModifiedPageCount", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epModifiedPageCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_VAD_COUNT, "_EPROCESS.VadCount", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epVadCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_VAD_PHYSICAL_PAGES, "_EPROCESS.VadPhysicalPages", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epVadPhysicalPages),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_VAD_PHYSICAL_PAGES_LIMIT, "_EPROCESS.VadPhysicalPagesLimit", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epVadPhysicalPagesLimit),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_ALPC_CONTEXT, "_EPROCESS.AlpcContext", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epAlpcContext),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_TIMER_RESOLUTION_LINK, "_EPROCESS.TimerResolutionLink", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epTimerResolutionLink),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_TIMER_RESOLUTION_STACK_RECORD, "_EPROCESS.TimerResolutionStackRecord", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epTimerResolutionStackRecord),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_REQUESTED_TIMER_RESOLUTION, "_EPROCESS.RequestedTimerResolution", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epRequestedTimerResolution),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_SMALLEST_TIMER_RESOLUTION, "_EPROCESS.SmallestTimerResolution", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epSmallestTimerResolution),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_INVERTED_FUNCTION_TABLE, "_EPROCESS.InvertedFunctionTable", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epInvertedFunctionTable),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_INVERTED_FUNCTION_TABLE_LOCK, "_EPROCESS.InvertedFunctionTableLock", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epInvertedFunctionTableLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_ACTIVE_THREADS_HIGH_WATERMARK, "_EPROCESS.ActiveThreadsHighWatermark", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epActiveThreadsHighWatermark),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_LARGE_PRIVATE_VAD_COUNT, "_EPROCESS.LargePrivateVadCount", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epLargePrivateVadCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_THREAD_LIST_LOCK, "_EPROCESS.ThreadListLock", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epThreadListLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_WNF_CONTEXT, "_EPROCESS.WnfContext", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epWnfContext),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_FLAGS3, "_EPROCESS.Flags3", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epFlags3),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_DISK_COUNTERS, "_EPROCESS.DiskCounters", "EPROCESS Optional Fields", KSW_CAP_PROCESS_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.epDiskCounters),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_TOKEN_SOURCE, "_TOKEN.TokenSource", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokTokenSource),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_TOKEN_ID, "_TOKEN.TokenId", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokTokenId),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_AUTHENTICATION_ID, "_TOKEN.AuthenticationId", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokAuthenticationId),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_PARENT_TOKEN_ID, "_TOKEN.ParentTokenId", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokParentTokenId),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_EXPIRATION_TIME, "_TOKEN.ExpirationTime", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokExpirationTime),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_TOKEN_LOCK, "_TOKEN.TokenLock", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokTokenLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_MODIFIED_ID, "_TOKEN.ModifiedId", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokModifiedId),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_PRIVILEGES, "_TOKEN.Privileges", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokPrivileges),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_AUDIT_POLICY, "_TOKEN.AuditPolicy", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokAuditPolicy),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_SESSION_ID, "_TOKEN.SessionId", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokSessionId),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_USER_AND_GROUP_COUNT, "_TOKEN.UserAndGroupCount", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS | KSW_CAP_TOKEN_INTEGRITY_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokUserAndGroupCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_RESTRICTED_SID_COUNT, "_TOKEN.RestrictedSidCount", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokRestrictedSidCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_VARIABLE_LENGTH, "_TOKEN.VariableLength", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokVariableLength),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_DYNAMIC_CHARGED, "_TOKEN.DynamicCharged", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokDynamicCharged),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_DYNAMIC_AVAILABLE, "_TOKEN.DynamicAvailable", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokDynamicAvailable),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_DEFAULT_OWNER_INDEX, "_TOKEN.DefaultOwnerIndex", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokDefaultOwnerIndex),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_USER_AND_GROUPS, "_TOKEN.UserAndGroups", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS | KSW_CAP_TOKEN_INTEGRITY_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokUserAndGroups),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_RESTRICTED_SIDS, "_TOKEN.RestrictedSids", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokRestrictedSids),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_PRIMARY_GROUP, "_TOKEN.PrimaryGroup", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokPrimaryGroup),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_DYNAMIC_PART, "_TOKEN.DynamicPart", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokDynamicPart),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_DEFAULT_DACL, "_TOKEN.DefaultDacl", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokDefaultDacl),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_TOKEN_TYPE, "_TOKEN.TokenType", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokTokenType),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_IMPERSONATION_LEVEL, "_TOKEN.ImpersonationLevel", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokImpersonationLevel),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_TOKEN_FLAGS, "_TOKEN.TokenFlags", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokTokenFlags),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_TOKEN_IN_USE, "_TOKEN.TokenInUse", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokTokenInUse),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_INTEGRITY_LEVEL_INDEX, "_TOKEN.IntegrityLevelIndex", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS | KSW_CAP_TOKEN_INTEGRITY_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokIntegrityLevelIndex),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_MANDATORY_POLICY, "_TOKEN.MandatoryPolicy", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS | KSW_CAP_TOKEN_INTEGRITY_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokMandatoryPolicy),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_LOGON_SESSION, "_TOKEN.LogonSession", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokLogonSession),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_ORIGINATING_LOGON_SESSION, "_TOKEN.OriginatingLogonSession", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokOriginatingLogonSession),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_SID_HASH, "_TOKEN.SidHash", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokSidHash),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_RESTRICTED_SID_HASH, "_TOKEN.RestrictedSidHash", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokRestrictedSidHash),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_P_SECURITY_ATTRIBUTES, "_TOKEN.pSecurityAttributes", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokPSecurityAttributes),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_PACKAGE, "_TOKEN.Package", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokPackage),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_CAPABILITIES, "_TOKEN.Capabilities", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokCapabilities),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_CAPABILITY_COUNT, "_TOKEN.CapabilityCount", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokCapabilityCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_CAPABILITIES_HASH, "_TOKEN.CapabilitiesHash", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokCapabilitiesHash),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_LOWBOX_NUMBER_ENTRY, "_TOKEN.LowboxNumberEntry", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokLowboxNumberEntry),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_LOWBOX_HANDLES_ENTRY, "_TOKEN.LowboxHandlesEntry", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokLowboxHandlesEntry),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_P_CLAIM_ATTRIBUTES, "_TOKEN.pClaimAttributes", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokPClaimAttributes),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_TRUST_LEVEL_SID, "_TOKEN.TrustLevelSid", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokTrustLevelSid),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_TRUST_LINKED_TOKEN, "_TOKEN.TrustLinkedToken", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokTrustLinkedToken),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_INTEGRITY_LEVEL_SID_VALUE, "_TOKEN.IntegrityLevelSidValue", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokIntegrityLevelSidValue),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_TOKEN_SID_VALUES, "_TOKEN.TokenSidValues", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokTokenSidValues),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_SESSION_OBJECT, "_TOKEN.SessionObject", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokSessionObject),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_TOK_VARIABLE_PART, "_TOKEN.VariablePart", "Token Private Fields", KSW_CAP_TOKEN_PRIVATE_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.tokVariablePart),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_HT_HANDLE_CONTENTION_EVENT, "HtHandleContentionEvent", "HandleTable Decode", KSW_CAP_HANDLE_TABLE_DECODE, FALSE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.htHandleContentionEvent),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_HT_TABLE_CODE, "_HANDLE_TABLE.TableCode", "HandleTable Decode", KSW_CAP_HANDLE_TABLE_DECODE | KSW_CAP_CID_TABLE_WALK, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.htTableCode),
    /* _HANDLE_TABLE.HandleCount is diagnostic-only on current decode paths; TableCode/LowValue drive the gated handle-table walks. */
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_HT_HANDLE_COUNT, "_HANDLE_TABLE.HandleCount", "HandleTable Decode", KSW_CAP_HANDLE_TABLE_DECODE, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.htHandleCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_HTE_LOW_VALUE, "_HANDLE_TABLE_ENTRY.LowValue", "HandleTable Decode", KSW_CAP_HANDLE_TABLE_DECODE | KSW_CAP_CID_TABLE_WALK, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.hteLowValue),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_OT_NAME, "OtName", "Object Type", KSW_CAP_OBJECT_TYPE_FIELDS | KSW_CAP_HANDLE_TABLE_DECODE, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.otName),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_OT_INDEX, "OtIndex", "Object Type", KSW_CAP_OBJECT_TYPE_FIELDS | KSW_CAP_HANDLE_TABLE_DECODE, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.otIndex),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_OB_DECODE_SHIFT, "ObDecodeShift", "HandleTable Decode", KSW_CAP_HANDLE_TABLE_DECODE, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.obDecodeShift),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_OB_ATTRIBUTES_SHIFT, "ObAttributesShift", "HandleTable Decode", KSW_CAP_HANDLE_TABLE_DECODE, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.obAttributesShift),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EGE_GUID, "EgeGuid", "ETW GUID Entry", KSW_CAP_ETW_GUID_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.egeGuid),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ERE_GUID_ENTRY, "EreGuidEntry", "ETW Registration Entry", KSW_CAP_ETW_GUID_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ereGuidEntry),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_INITIAL_STACK, "KtInitialStack", "Thread Stack", KSW_CAP_THREAD_STACK_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktInitialStack),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_STACK_LIMIT, "KtStackLimit", "Thread Stack", KSW_CAP_THREAD_STACK_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktStackLimit),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_STACK_BASE, "KtStackBase", "Thread Stack", KSW_CAP_THREAD_STACK_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktStackBase),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_KERNEL_STACK, "KtKernelStack", "Thread Stack", KSW_CAP_THREAD_STACK_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktKernelStack),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_PROCESS, "_KTHREAD.Process", "Thread List Fields", KSW_CAP_THREAD_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.ktProcess),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ET_CID, "_ETHREAD.Cid", "Thread List Fields", KSW_CAP_THREAD_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.etCid),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ET_THREAD_LIST_ENTRY, "_ETHREAD.ThreadListEntry", "Thread List Fields", KSW_CAP_THREAD_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.etThreadListEntry),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ET_START_ADDRESS, "_ETHREAD.StartAddress", "Thread List Fields", KSW_CAP_THREAD_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.etStartAddress),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ET_WIN32_START_ADDRESS, "_ETHREAD.Win32StartAddress", "Thread List Fields", KSW_CAP_THREAD_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.etWin32StartAddress),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_READ_OPERATION_COUNT, "KtReadOperationCount", "Thread I/O Counters", KSW_CAP_THREAD_IO_COUNTERS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktReadOperationCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_WRITE_OPERATION_COUNT, "KtWriteOperationCount", "Thread I/O Counters", KSW_CAP_THREAD_IO_COUNTERS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktWriteOperationCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_OTHER_OPERATION_COUNT, "KtOtherOperationCount", "Thread I/O Counters", KSW_CAP_THREAD_IO_COUNTERS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktOtherOperationCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_READ_TRANSFER_COUNT, "KtReadTransferCount", "Thread I/O Counters", KSW_CAP_THREAD_IO_COUNTERS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktReadTransferCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_WRITE_TRANSFER_COUNT, "KtWriteTransferCount", "Thread I/O Counters", KSW_CAP_THREAD_IO_COUNTERS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktWriteTransferCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KT_OTHER_TRANSFER_COUNT, "KtOtherTransferCount", "Thread I/O Counters", KSW_CAP_THREAD_IO_COUNTERS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.ktOtherTransferCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_MM_SECTION_CONTROL_AREA, "MmSectionControlArea", "Section/ControlArea", KSW_CAP_SECTION_CONTROL_AREA, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.mmSectionControlArea),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_MM_CONTROL_AREA_LIST_HEAD, "MmControlAreaListHead", "Section/ControlArea", KSW_CAP_SECTION_CONTROL_AREA, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.mmControlAreaListHead),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_MM_CONTROL_AREA_LOCK, "MmControlAreaLock", "Section/ControlArea", KSW_CAP_SECTION_CONTROL_AREA, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.mmControlAreaLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_COMMUNICATION_INFO, "AlpcCommunicationInfo", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcCommunicationInfo),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_OWNER_PROCESS, "AlpcOwnerProcess", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcOwnerProcess),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_CONNECTION_PORT, "AlpcConnectionPort", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcConnectionPort),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_SERVER_COMMUNICATION_PORT, "AlpcServerCommunicationPort", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcServerCommunicationPort),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_CLIENT_COMMUNICATION_PORT, "AlpcClientCommunicationPort", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcClientCommunicationPort),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_HANDLE_TABLE, "AlpcHandleTable", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcHandleTable),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_HANDLE_TABLE_LOCK, "AlpcHandleTableLock", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcHandleTableLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_ATTRIBUTES, "AlpcAttributes", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcAttributes),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_ATTRIBUTES_FLAGS, "AlpcAttributesFlags", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcAttributesFlags),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_PORT_CONTEXT, "AlpcPortContext", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcPortContext),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_PORT_OBJECT_LOCK, "AlpcPortObjectLock", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcPortObjectLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_SEQUENCE_NO, "AlpcSequenceNo", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcSequenceNo),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ALPC_STATE, "AlpcState", "ALPC", KSW_CAP_ALPC_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, kernel.alpcState),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_LX_PICO_PROC, "LxPicoProc", "WSL/Lxcore", KSW_CAP_WSL_LXCORE_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, lxcoreOffsets.lxPicoProc),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_LX_PICO_PROC_INFO, "LxPicoProcInfo", "WSL/Lxcore", KSW_CAP_WSL_LXCORE_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, lxcoreOffsets.lxPicoProcInfo),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_LX_PICO_PROC_INFO_PID, "LxPicoProcInfoPID", "WSL/Lxcore", KSW_CAP_WSL_LXCORE_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, lxcoreOffsets.lxPicoProcInfoPid),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_LX_PICO_THRD_INFO, "LxPicoThrdInfo", "WSL/Lxcore", KSW_CAP_WSL_LXCORE_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, lxcoreOffsets.lxPicoThrdInfo),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_LX_PICO_THRD_INFO_TID, "LxPicoThrdInfoTID", "WSL/Lxcore", KSW_CAP_WSL_LXCORE_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER, lxcoreOffsets.lxPicoThrdInfoTid),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_PROTECTION, "EpProtection", "Process Protection Patch", KSW_CAP_PROCESS_PROTECTION_PATCH, TRUE, KSW_DYN_FIELD_SOURCE_RUNTIME_PATTERN, kernel.epProtection),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_SIGNATURE_LEVEL, "EpSignatureLevel", "Process Protection Patch", KSW_CAP_PROCESS_PROTECTION_PATCH, TRUE, KSW_DYN_FIELD_SOURCE_RUNTIME_PATTERN, kernel.epSignatureLevel),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_EP_SECTION_SIGNATURE_LEVEL, "EpSectionSignatureLevel", "Process Protection Patch", KSW_CAP_PROCESS_PROTECTION_PATCH, TRUE, KSW_DYN_FIELD_SOURCE_RUNTIME_PATTERN, kernel.epSectionSignatureLevel),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KLDR_IN_LOAD_ORDER_LINKS, "_KLDR_DATA_TABLE_ENTRY.InLoadOrderLinks", "Kernel Module List Fields", KSW_CAP_KERNEL_MODULE_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.kldrInLoadOrderLinks),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KLDR_DLL_BASE, "_KLDR_DATA_TABLE_ENTRY.DllBase", "Kernel Module List Fields", KSW_CAP_KERNEL_MODULE_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.kldrDllBase),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KLDR_SIZE_OF_IMAGE, "_KLDR_DATA_TABLE_ENTRY.SizeOfImage", "Kernel Module List Fields", KSW_CAP_KERNEL_MODULE_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.kldrSizeOfImage),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KLDR_FULL_DLL_NAME, "_KLDR_DATA_TABLE_ENTRY.FullDllName", "Kernel Module List Fields", KSW_CAP_KERNEL_MODULE_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.kldrFullDllName),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KLDR_BASE_DLL_NAME, "_KLDR_DATA_TABLE_ENTRY.BaseDllName", "Kernel Module List Fields", KSW_CAP_KERNEL_MODULE_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.kldrBaseDllName),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KLDR_FLAGS, "_KLDR_DATA_TABLE_ENTRY.Flags", "Kernel Module List Fields", KSW_CAP_KERNEL_MODULE_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.kldrFlags),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_DO_DRIVER_START, "_DRIVER_OBJECT.DriverStart", "Driver Object Fields", KSW_CAP_DRIVER_OBJECT_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.doDriverStart),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_DO_DRIVER_SIZE, "_DRIVER_OBJECT.DriverSize", "Driver Object Fields", KSW_CAP_DRIVER_OBJECT_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.doDriverSize),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_DO_DRIVER_SECTION, "_DRIVER_OBJECT.DriverSection", "Driver Object Fields", KSW_CAP_DRIVER_OBJECT_FIELDS | KSW_CAP_KERNEL_MODULE_LIST_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.doDriverSection),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_DO_MAJOR_FUNCTION, "_DRIVER_OBJECT.MajorFunction", "Driver Object Fields", KSW_CAP_DRIVER_OBJECT_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.doMajorFunction),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_DO_FAST_IO_DISPATCH, "_DRIVER_OBJECT.FastIoDispatch", "Driver Object Fields", KSW_CAP_DRIVER_OBJECT_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.doFastIoDispatch),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_DO_DRIVER_UNLOAD, "_DRIVER_OBJECT.DriverUnload", "Driver Object Fields", KSW_CAP_DRIVER_OBJECT_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.doDriverUnload),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ULD_NAME, "_UNLOADED_DRIVERS.Name", "Unloaded Driver Trace Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.uldName),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ULD_START_ADDRESS, "_UNLOADED_DRIVERS.StartAddress", "Unloaded Driver Trace Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.uldStartAddress),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ULD_END_ADDRESS, "_UNLOADED_DRIVERS.EndAddress", "Unloaded Driver Trace Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.uldEndAddress),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ULD_CURRENT_TIME, "_UNLOADED_DRIVERS.CurrentTime", "Unloaded Driver Trace Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.uldCurrentTime),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_ULD_TYPE_SIZE, "_UNLOADED_DRIVERS.TypeSize", "Unloaded Driver Trace Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.uldTypeSize),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_RTL_AVL_BALANCED_ROOT, "_RTL_AVL_TABLE.BalancedRoot", "PiDDB AVL Table Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.rtlAvlBalancedRoot),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_RTL_AVL_ORDERED_POINTER, "_RTL_AVL_TABLE.OrderedPointer", "PiDDB AVL Table Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.rtlAvlOrderedPointer),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_RTL_AVL_WHICH_ORDERED_ELEMENT, "_RTL_AVL_TABLE.WhichOrderedElement", "PiDDB AVL Table Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.rtlAvlWhichOrderedElement),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_RTL_AVL_NUMBER_GENERIC_TABLE_ELEMENTS, "_RTL_AVL_TABLE.NumberGenericTableElements", "PiDDB AVL Table Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.rtlAvlNumberGenericTableElements),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_RTL_AVL_DEPTH_OF_TREE, "_RTL_AVL_TABLE.DepthOfTree", "PiDDB AVL Table Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.rtlAvlDepthOfTree),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_RTL_AVL_RESTART_KEY, "_RTL_AVL_TABLE.RestartKey", "PiDDB AVL Table Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.rtlAvlRestartKey),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_RTL_AVL_DELETE_COUNT, "_RTL_AVL_TABLE.DeleteCount", "PiDDB AVL Table Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.rtlAvlDeleteCount),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_RTL_AVL_TYPE_SIZE, "_RTL_AVL_TABLE.TypeSize", "PiDDB AVL Table Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.rtlAvlTypeSize),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_PIDDB_DRIVER_NAME, "_PIDDB_CACHE_ENTRY.DriverName", "PiDDB Cache Entry Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.piDdbDriverName),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_PIDDB_TIME_DATE_STAMP, "_PIDDB_CACHE_ENTRY.TimeDateStamp", "PiDDB Cache Entry Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.piDdbTimeDateStamp),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_PIDDB_LOAD_STATUS, "_PIDDB_CACHE_ENTRY.LoadStatus", "PiDDB Cache Entry Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.piDdbLoadStatus),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_PIDDB_TYPE_SIZE, "_PIDDB_CACHE_ENTRY.TypeSize", "PiDDB Cache Entry Fields", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernel.piDdbTypeSize),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KG_PSP_CID_TABLE, "PspCidTable", "Kernel Globals", KSW_CAP_KERNEL_GLOBALS | KSW_CAP_CID_TABLE_WALK, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernelGlobals.pspCidTable),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KG_PS_LOADED_MODULE_LIST, "PsLoadedModuleList", "Kernel Globals", KSW_CAP_KERNEL_GLOBALS | KSW_CAP_KERNEL_MODULE_LIST_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernelGlobals.psLoadedModuleList),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KG_MM_UNLOADED_DRIVERS, "MmUnloadedDrivers", "Kernel Globals", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernelGlobals.mmUnloadedDrivers),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KG_PIDDB_CACHE_TABLE, "PiDDBCacheTable", "Kernel Globals", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernelGlobals.piDdbCacheTable),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KG_PIDDB_LOCK, "PiDDBLock", "Kernel Globals", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernelGlobals.piDdbLock),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KG_KE_SERVICE_DESCRIPTOR_TABLE_SHADOW, "KeServiceDescriptorTableShadow", "Kernel Globals", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernelGlobals.keServiceDescriptorTableShadow),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_KG_MM_LAST_UNLOADED_DRIVER, "MmLastUnloadedDriver", "Kernel Globals", KSW_CAP_KERNEL_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, kernelGlobals.mmLastUnloadedDriver),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_PSP_CREATE_PROCESS_NOTIFY_ROUTINE, "PspCreateProcessNotifyRoutine", "Callback Notify Globals", KSW_CAP_CALLBACK_NOTIFY_GLOBALS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackGlobals.pspCreateProcessNotifyRoutine),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_PSP_CREATE_THREAD_NOTIFY_ROUTINE, "PspCreateThreadNotifyRoutine", "Callback Notify Globals", KSW_CAP_CALLBACK_NOTIFY_GLOBALS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackGlobals.pspCreateThreadNotifyRoutine),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_PSP_LOAD_IMAGE_NOTIFY_ROUTINE, "PspLoadImageNotifyRoutine", "Callback Notify Globals", KSW_CAP_CALLBACK_NOTIFY_GLOBALS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackGlobals.pspLoadImageNotifyRoutine),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_PSP_NOTIFY_ENABLE_MASK, "PspNotifyEnableMask", "Callback Notify Globals", KSW_CAP_CALLBACK_NOTIFY_GLOBALS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackGlobals.pspNotifyEnableMask),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_CM_CALLBACK_LIST_HEAD, "CmCallbackListHead", "Callback Registry Globals", KSW_CAP_CALLBACK_REGISTRY_GLOBALS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackGlobals.cmCallbackListHead),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_OBJECT_TYPE_CALLBACK_LIST, "_OBJECT_TYPE.CallbackList", "Callback Object Fields", KSW_CAP_CALLBACK_OBJECT_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackOffsets.objectTypeCallbackList),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_ENTRY_LIST, "_CALLBACK_ENTRY_ITEM.EntryList", "Callback Object Fields", KSW_CAP_CALLBACK_OBJECT_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackOffsets.callbackEntryItemEntryList),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_PRE_OPERATION, "_CALLBACK_ENTRY_ITEM.PreOperation", "Callback Object Fields", KSW_CAP_CALLBACK_OBJECT_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackOffsets.callbackEntryItemPreOperation),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_POST_OPERATION, "_CALLBACK_ENTRY_ITEM.PostOperation", "Callback Object Fields", KSW_CAP_CALLBACK_OBJECT_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackOffsets.callbackEntryItemPostOperation),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_OPERATIONS, "_CALLBACK_ENTRY_ITEM.Operations", "Callback Object Fields", KSW_CAP_CALLBACK_OBJECT_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackOffsets.callbackEntryItemOperations),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_CALLBACK_ENTRY, "_CALLBACK_ENTRY_ITEM.CallbackEntry", "Callback Object Fields", KSW_CAP_CALLBACK_OBJECT_FIELDS, TRUE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackOffsets.callbackEntryItemCallbackEntry),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ALTITUDE, "_CALLBACK_ENTRY.Altitude", "Callback Object Fields", KSW_CAP_CALLBACK_OBJECT_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackOffsets.callbackEntryAltitude),
    KSW_FIELD_BINDING(KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_REGISTRATION_CONTEXT, "_CALLBACK_ENTRY.RegistrationContext", "Callback Object Fields", KSW_CAP_CALLBACK_OBJECT_FIELDS, FALSE, KSW_DYN_FIELD_SOURCE_PDB_PROFILE, callbackOffsets.callbackEntryRegistrationContext)
};

static ULONG
kswordArkDynDataReadBoundOffset(
    _In_ const KswDynState* state,
    _In_ const KswDynFieldBinding* binding
    )
/*++

Routine Description:

    Read a bound offset from a DynData state snapshot. Bindings use FIELD_OFFSET
    so query and capability code can share one field list.

Arguments:

    State - State snapshot that owns all offsets.
    Binding - Field binding row to read.

Return Value:

    Offset value, or KSW_DYN_OFFSET_UNAVAILABLE on invalid input.

--*/
{
    const UCHAR* stateBytes = (const UCHAR*)state;

    if (state == NULL || binding == NULL || binding->offsetInState > sizeof(KswDynState) - sizeof(ULONG)) {
        return KSW_DYN_OFFSET_UNAVAILABLE;
    }

    return *(const ULONG*)(stateBytes + binding->offsetInState);
}

static ULONG
kswordArkDynDataReadBoundSource(
    _In_ const KswDynState* state,
    _In_ const KswDynFieldBinding* binding
    )
/*++

Routine Description:

    Read the runtime provenance for one bound offset. Offset descriptors keep
    static metadata, while the source lives in KswDynState so PDB profile
    merges can override System Informer or runtime-pattern provenance precisely.

Arguments:

    State - State snapshot that owns all source fields.
    Binding - Field binding row whose FieldId selects a source field.

Return Value:

    KSW_DYN_FIELD_SOURCE_* value. Unknown bindings return UNAVAILABLE.

--*/
{
    if (state == NULL || binding == NULL) {
        return KSW_DYN_FIELD_SOURCE_UNAVAILABLE;
    }

    switch (binding->fieldId) {
    case KSW_DYN_FIELD_ID_EP_OBJECT_TABLE:
        return state->kernelSources.epObjectTable;
    case KSW_DYN_FIELD_ID_EP_SECTION_OBJECT:
        return state->kernelSources.epSectionObject;
    case KSW_DYN_FIELD_ID_EP_UNIQUE_PROCESS_ID:
        return state->kernelSources.epUniqueProcessId;
    case KSW_DYN_FIELD_ID_EP_ACTIVE_PROCESS_LINKS:
        return state->kernelSources.epActiveProcessLinks;
    case KSW_DYN_FIELD_ID_EP_THREAD_LIST_HEAD:
        return state->kernelSources.epThreadListHead;
    case KSW_DYN_FIELD_ID_EP_IMAGE_FILE_NAME:
        return state->kernelSources.epImageFileName;
    case KSW_DYN_FIELD_ID_EP_TOKEN:
        return state->kernelSources.epToken;
    case KSW_DYN_FIELD_ID_EP_FLAGS:
        return state->kernelSources.epFlags;
    case KSW_DYN_FIELD_ID_EP_FLAGS2:
        return state->kernelSources.epFlags2;
    case KSW_DYN_FIELD_ID_EP_RUNDOWN_PROTECT:
        return state->kernelSources.epRundownProtect;
    case KSW_DYN_FIELD_ID_EP_PROCESS_LOCK:
        return state->kernelSources.epProcessLock;
    case KSW_DYN_FIELD_ID_EP_CREATE_TIME:
        return state->kernelSources.epCreateTime;
    case KSW_DYN_FIELD_ID_EP_EXIT_TIME:
        return state->kernelSources.epExitTime;
    case KSW_DYN_FIELD_ID_EP_EXIT_STATUS:
        return state->kernelSources.epExitStatus;
    case KSW_DYN_FIELD_ID_EP_PEB:
        return state->kernelSources.epPeb;
    case KSW_DYN_FIELD_ID_EP_SESSION:
        return state->kernelSources.epSession;
    case KSW_DYN_FIELD_ID_EP_WIN32_PROCESS:
        return state->kernelSources.epWin32Process;
    case KSW_DYN_FIELD_ID_EP_WOW64_PROCESS:
        return state->kernelSources.epWow64Process;
    case KSW_DYN_FIELD_ID_EP_INHERITED_FROM_UNIQUE_PROCESS_ID:
        return state->kernelSources.epInheritedFromUniqueProcessId;
    case KSW_DYN_FIELD_ID_EP_SE_AUDIT_PROCESS_CREATION_INFO:
        return state->kernelSources.epSeAuditProcessCreationInfo;
    case KSW_DYN_FIELD_ID_EP_JOB:
        return state->kernelSources.epJob;
    case KSW_DYN_FIELD_ID_EP_DEVICE_MAP:
        return state->kernelSources.epDeviceMap;
    case KSW_DYN_FIELD_ID_EP_DEBUG_PORT:
        return state->kernelSources.epDebugPort;
    case KSW_DYN_FIELD_ID_EP_EXCEPTION_PORT_DATA:
        return state->kernelSources.epExceptionPortData;
    case KSW_DYN_FIELD_ID_EP_SECTION_BASE_ADDRESS:
        return state->kernelSources.epSectionBaseAddress;
    case KSW_DYN_FIELD_ID_EP_IMAGE_FILE_POINTER:
        return state->kernelSources.epImageFilePointer;
    case KSW_DYN_FIELD_ID_EP_PRIORITY_CLASS:
        return state->kernelSources.epPriorityClass;
    case KSW_DYN_FIELD_ID_EP_ACTIVE_THREADS:
        return state->kernelSources.epActiveThreads;
    case KSW_DYN_FIELD_ID_EP_VAD_ROOT:
        return state->kernelSources.epVadRoot;
    case KSW_DYN_FIELD_ID_EP_VAD_HINT:
        return state->kernelSources.epVadHint;
    case KSW_DYN_FIELD_ID_EP_CLONE_ROOT:
        return state->kernelSources.epCloneRoot;
    case KSW_DYN_FIELD_ID_EP_NUMBER_OF_PRIVATE_PAGES:
        return state->kernelSources.epNumberOfPrivatePages;
    case KSW_DYN_FIELD_ID_EP_NUMBER_OF_LOCKED_PAGES:
        return state->kernelSources.epNumberOfLockedPages;
    case KSW_DYN_FIELD_ID_EP_COMMIT_CHARGE:
        return state->kernelSources.epCommitCharge;
    case KSW_DYN_FIELD_ID_EP_COMMIT_CHARGE_PEAK:
        return state->kernelSources.epCommitChargePeak;
    case KSW_DYN_FIELD_ID_EP_PEAK_VIRTUAL_SIZE:
        return state->kernelSources.epPeakVirtualSize;
    case KSW_DYN_FIELD_ID_EP_VIRTUAL_SIZE:
        return state->kernelSources.epVirtualSize;
    case KSW_DYN_FIELD_ID_EP_SESSION_PROCESS_LINKS:
        return state->kernelSources.epSessionProcessLinks;
    case KSW_DYN_FIELD_ID_EP_MITIGATION_FLAGS:
        return state->kernelSources.epMitigationFlags;
    case KSW_DYN_FIELD_ID_EP_MITIGATION_FLAGS2:
        return state->kernelSources.epMitigationFlags2;
    case KSW_DYN_FIELD_ID_EP_PROCESS_QUOTA_USAGE:
        return state->kernelSources.epProcessQuotaUsage;
    case KSW_DYN_FIELD_ID_EP_PROCESS_QUOTA_PEAK:
        return state->kernelSources.epProcessQuotaPeak;
    case KSW_DYN_FIELD_ID_EP_ADDRESS_CREATION_LOCK:
        return state->kernelSources.epAddressCreationLock;
    case KSW_DYN_FIELD_ID_EP_PAGE_TABLE_COMMITMENT_LOCK:
        return state->kernelSources.epPageTableCommitmentLock;
    case KSW_DYN_FIELD_ID_EP_ROTATE_IN_PROGRESS:
        return state->kernelSources.epRotateInProgress;
    case KSW_DYN_FIELD_ID_EP_FORK_IN_PROGRESS:
        return state->kernelSources.epForkInProgress;
    case KSW_DYN_FIELD_ID_EP_COMMIT_CHARGE_JOB:
        return state->kernelSources.epCommitChargeJob;
    case KSW_DYN_FIELD_ID_EP_COOKIE:
        return state->kernelSources.epCookie;
    case KSW_DYN_FIELD_ID_EP_WORKING_SET_WATCH:
        return state->kernelSources.epWorkingSetWatch;
    case KSW_DYN_FIELD_ID_EP_WIN32_WINDOW_STATION:
        return state->kernelSources.epWin32WindowStation;
    case KSW_DYN_FIELD_ID_EP_OWNER_PROCESS_ID:
        return state->kernelSources.epOwnerProcessId;
    case KSW_DYN_FIELD_ID_EP_QUOTA_BLOCK:
        return state->kernelSources.epQuotaBlock;
    case KSW_DYN_FIELD_ID_EP_ETW_DATA_SOURCE:
        return state->kernelSources.epEtwDataSource;
    case KSW_DYN_FIELD_ID_EP_PAGE_DIRECTORY_PTE:
        return state->kernelSources.epPageDirectoryPte;
    case KSW_DYN_FIELD_ID_EP_SECURITY_PORT:
        return state->kernelSources.epSecurityPort;
    case KSW_DYN_FIELD_ID_EP_JOB_LINKS:
        return state->kernelSources.epJobLinks;
    case KSW_DYN_FIELD_ID_EP_HIGHEST_USER_ADDRESS:
        return state->kernelSources.epHighestUserAddress;
    case KSW_DYN_FIELD_ID_EP_IMAGE_PATH_HASH:
        return state->kernelSources.epImagePathHash;
    case KSW_DYN_FIELD_ID_EP_DEFAULT_HARD_ERROR_PROCESSING:
        return state->kernelSources.epDefaultHardErrorProcessing;
    case KSW_DYN_FIELD_ID_EP_LAST_THREAD_EXIT_STATUS:
        return state->kernelSources.epLastThreadExitStatus;
    case KSW_DYN_FIELD_ID_EP_PREFETCH_TRACE:
        return state->kernelSources.epPrefetchTrace;
    case KSW_DYN_FIELD_ID_EP_LOCKED_PAGES_LIST:
        return state->kernelSources.epLockedPagesList;
    case KSW_DYN_FIELD_ID_EP_READ_OPERATION_COUNT:
        return state->kernelSources.epReadOperationCount;
    case KSW_DYN_FIELD_ID_EP_WRITE_OPERATION_COUNT:
        return state->kernelSources.epWriteOperationCount;
    case KSW_DYN_FIELD_ID_EP_OTHER_OPERATION_COUNT:
        return state->kernelSources.epOtherOperationCount;
    case KSW_DYN_FIELD_ID_EP_READ_TRANSFER_COUNT:
        return state->kernelSources.epReadTransferCount;
    case KSW_DYN_FIELD_ID_EP_WRITE_TRANSFER_COUNT:
        return state->kernelSources.epWriteTransferCount;
    case KSW_DYN_FIELD_ID_EP_OTHER_TRANSFER_COUNT:
        return state->kernelSources.epOtherTransferCount;
    case KSW_DYN_FIELD_ID_EP_COMMIT_CHARGE_LIMIT:
        return state->kernelSources.epCommitChargeLimit;
    case KSW_DYN_FIELD_ID_EP_VM:
        return state->kernelSources.epVm;
    case KSW_DYN_FIELD_ID_EP_MM_PROCESS_LINKS:
        return state->kernelSources.epMmProcessLinks;
    case KSW_DYN_FIELD_ID_EP_MODIFIED_PAGE_COUNT:
        return state->kernelSources.epModifiedPageCount;
    case KSW_DYN_FIELD_ID_EP_VAD_COUNT:
        return state->kernelSources.epVadCount;
    case KSW_DYN_FIELD_ID_EP_VAD_PHYSICAL_PAGES:
        return state->kernelSources.epVadPhysicalPages;
    case KSW_DYN_FIELD_ID_EP_VAD_PHYSICAL_PAGES_LIMIT:
        return state->kernelSources.epVadPhysicalPagesLimit;
    case KSW_DYN_FIELD_ID_EP_ALPC_CONTEXT:
        return state->kernelSources.epAlpcContext;
    case KSW_DYN_FIELD_ID_EP_TIMER_RESOLUTION_LINK:
        return state->kernelSources.epTimerResolutionLink;
    case KSW_DYN_FIELD_ID_EP_TIMER_RESOLUTION_STACK_RECORD:
        return state->kernelSources.epTimerResolutionStackRecord;
    case KSW_DYN_FIELD_ID_EP_REQUESTED_TIMER_RESOLUTION:
        return state->kernelSources.epRequestedTimerResolution;
    case KSW_DYN_FIELD_ID_EP_SMALLEST_TIMER_RESOLUTION:
        return state->kernelSources.epSmallestTimerResolution;
    case KSW_DYN_FIELD_ID_EP_INVERTED_FUNCTION_TABLE:
        return state->kernelSources.epInvertedFunctionTable;
    case KSW_DYN_FIELD_ID_EP_INVERTED_FUNCTION_TABLE_LOCK:
        return state->kernelSources.epInvertedFunctionTableLock;
    case KSW_DYN_FIELD_ID_EP_ACTIVE_THREADS_HIGH_WATERMARK:
        return state->kernelSources.epActiveThreadsHighWatermark;
    case KSW_DYN_FIELD_ID_EP_LARGE_PRIVATE_VAD_COUNT:
        return state->kernelSources.epLargePrivateVadCount;
    case KSW_DYN_FIELD_ID_EP_THREAD_LIST_LOCK:
        return state->kernelSources.epThreadListLock;
    case KSW_DYN_FIELD_ID_EP_WNF_CONTEXT:
        return state->kernelSources.epWnfContext;
    case KSW_DYN_FIELD_ID_EP_FLAGS3:
        return state->kernelSources.epFlags3;
    case KSW_DYN_FIELD_ID_EP_DISK_COUNTERS:
        return state->kernelSources.epDiskCounters;
    case KSW_DYN_FIELD_ID_TOK_TOKEN_SOURCE:
        return state->kernelSources.tokTokenSource;
    case KSW_DYN_FIELD_ID_TOK_TOKEN_ID:
        return state->kernelSources.tokTokenId;
    case KSW_DYN_FIELD_ID_TOK_AUTHENTICATION_ID:
        return state->kernelSources.tokAuthenticationId;
    case KSW_DYN_FIELD_ID_TOK_PARENT_TOKEN_ID:
        return state->kernelSources.tokParentTokenId;
    case KSW_DYN_FIELD_ID_TOK_EXPIRATION_TIME:
        return state->kernelSources.tokExpirationTime;
    case KSW_DYN_FIELD_ID_TOK_TOKEN_LOCK:
        return state->kernelSources.tokTokenLock;
    case KSW_DYN_FIELD_ID_TOK_MODIFIED_ID:
        return state->kernelSources.tokModifiedId;
    case KSW_DYN_FIELD_ID_TOK_PRIVILEGES:
        return state->kernelSources.tokPrivileges;
    case KSW_DYN_FIELD_ID_TOK_AUDIT_POLICY:
        return state->kernelSources.tokAuditPolicy;
    case KSW_DYN_FIELD_ID_TOK_SESSION_ID:
        return state->kernelSources.tokSessionId;
    case KSW_DYN_FIELD_ID_TOK_USER_AND_GROUP_COUNT:
        return state->kernelSources.tokUserAndGroupCount;
    case KSW_DYN_FIELD_ID_TOK_RESTRICTED_SID_COUNT:
        return state->kernelSources.tokRestrictedSidCount;
    case KSW_DYN_FIELD_ID_TOK_VARIABLE_LENGTH:
        return state->kernelSources.tokVariableLength;
    case KSW_DYN_FIELD_ID_TOK_DYNAMIC_CHARGED:
        return state->kernelSources.tokDynamicCharged;
    case KSW_DYN_FIELD_ID_TOK_DYNAMIC_AVAILABLE:
        return state->kernelSources.tokDynamicAvailable;
    case KSW_DYN_FIELD_ID_TOK_DEFAULT_OWNER_INDEX:
        return state->kernelSources.tokDefaultOwnerIndex;
    case KSW_DYN_FIELD_ID_TOK_USER_AND_GROUPS:
        return state->kernelSources.tokUserAndGroups;
    case KSW_DYN_FIELD_ID_TOK_RESTRICTED_SIDS:
        return state->kernelSources.tokRestrictedSids;
    case KSW_DYN_FIELD_ID_TOK_PRIMARY_GROUP:
        return state->kernelSources.tokPrimaryGroup;
    case KSW_DYN_FIELD_ID_TOK_DYNAMIC_PART:
        return state->kernelSources.tokDynamicPart;
    case KSW_DYN_FIELD_ID_TOK_DEFAULT_DACL:
        return state->kernelSources.tokDefaultDacl;
    case KSW_DYN_FIELD_ID_TOK_TOKEN_TYPE:
        return state->kernelSources.tokTokenType;
    case KSW_DYN_FIELD_ID_TOK_IMPERSONATION_LEVEL:
        return state->kernelSources.tokImpersonationLevel;
    case KSW_DYN_FIELD_ID_TOK_TOKEN_FLAGS:
        return state->kernelSources.tokTokenFlags;
    case KSW_DYN_FIELD_ID_TOK_TOKEN_IN_USE:
        return state->kernelSources.tokTokenInUse;
    case KSW_DYN_FIELD_ID_TOK_INTEGRITY_LEVEL_INDEX:
        return state->kernelSources.tokIntegrityLevelIndex;
    case KSW_DYN_FIELD_ID_TOK_MANDATORY_POLICY:
        return state->kernelSources.tokMandatoryPolicy;
    case KSW_DYN_FIELD_ID_TOK_LOGON_SESSION:
        return state->kernelSources.tokLogonSession;
    case KSW_DYN_FIELD_ID_TOK_ORIGINATING_LOGON_SESSION:
        return state->kernelSources.tokOriginatingLogonSession;
    case KSW_DYN_FIELD_ID_TOK_SID_HASH:
        return state->kernelSources.tokSidHash;
    case KSW_DYN_FIELD_ID_TOK_RESTRICTED_SID_HASH:
        return state->kernelSources.tokRestrictedSidHash;
    case KSW_DYN_FIELD_ID_TOK_P_SECURITY_ATTRIBUTES:
        return state->kernelSources.tokPSecurityAttributes;
    case KSW_DYN_FIELD_ID_TOK_PACKAGE:
        return state->kernelSources.tokPackage;
    case KSW_DYN_FIELD_ID_TOK_CAPABILITIES:
        return state->kernelSources.tokCapabilities;
    case KSW_DYN_FIELD_ID_TOK_CAPABILITY_COUNT:
        return state->kernelSources.tokCapabilityCount;
    case KSW_DYN_FIELD_ID_TOK_CAPABILITIES_HASH:
        return state->kernelSources.tokCapabilitiesHash;
    case KSW_DYN_FIELD_ID_TOK_LOWBOX_NUMBER_ENTRY:
        return state->kernelSources.tokLowboxNumberEntry;
    case KSW_DYN_FIELD_ID_TOK_LOWBOX_HANDLES_ENTRY:
        return state->kernelSources.tokLowboxHandlesEntry;
    case KSW_DYN_FIELD_ID_TOK_P_CLAIM_ATTRIBUTES:
        return state->kernelSources.tokPClaimAttributes;
    case KSW_DYN_FIELD_ID_TOK_TRUST_LEVEL_SID:
        return state->kernelSources.tokTrustLevelSid;
    case KSW_DYN_FIELD_ID_TOK_TRUST_LINKED_TOKEN:
        return state->kernelSources.tokTrustLinkedToken;
    case KSW_DYN_FIELD_ID_TOK_INTEGRITY_LEVEL_SID_VALUE:
        return state->kernelSources.tokIntegrityLevelSidValue;
    case KSW_DYN_FIELD_ID_TOK_TOKEN_SID_VALUES:
        return state->kernelSources.tokTokenSidValues;
    case KSW_DYN_FIELD_ID_TOK_SESSION_OBJECT:
        return state->kernelSources.tokSessionObject;
    case KSW_DYN_FIELD_ID_TOK_VARIABLE_PART:
        return state->kernelSources.tokVariablePart;
    case KSW_DYN_FIELD_ID_HT_HANDLE_CONTENTION_EVENT:
        return state->kernelSources.htHandleContentionEvent;
    case KSW_DYN_FIELD_ID_HT_TABLE_CODE:
        return state->kernelSources.htTableCode;
    case KSW_DYN_FIELD_ID_HT_HANDLE_COUNT:
        return state->kernelSources.htHandleCount;
    case KSW_DYN_FIELD_ID_HTE_LOW_VALUE:
        return state->kernelSources.hteLowValue;
    case KSW_DYN_FIELD_ID_OT_NAME:
        return state->kernelSources.otName;
    case KSW_DYN_FIELD_ID_OT_INDEX:
        return state->kernelSources.otIndex;
    case KSW_DYN_FIELD_ID_OB_DECODE_SHIFT:
        return state->kernelSources.obDecodeShift;
    case KSW_DYN_FIELD_ID_OB_ATTRIBUTES_SHIFT:
        return state->kernelSources.obAttributesShift;
    case KSW_DYN_FIELD_ID_EGE_GUID:
        return state->kernelSources.egeGuid;
    case KSW_DYN_FIELD_ID_ERE_GUID_ENTRY:
        return state->kernelSources.ereGuidEntry;
    case KSW_DYN_FIELD_ID_KT_INITIAL_STACK:
        return state->kernelSources.ktInitialStack;
    case KSW_DYN_FIELD_ID_KT_STACK_LIMIT:
        return state->kernelSources.ktStackLimit;
    case KSW_DYN_FIELD_ID_KT_STACK_BASE:
        return state->kernelSources.ktStackBase;
    case KSW_DYN_FIELD_ID_KT_KERNEL_STACK:
        return state->kernelSources.ktKernelStack;
    case KSW_DYN_FIELD_ID_KT_PROCESS:
        return state->kernelSources.ktProcess;
    case KSW_DYN_FIELD_ID_ET_CID:
        return state->kernelSources.etCid;
    case KSW_DYN_FIELD_ID_ET_THREAD_LIST_ENTRY:
        return state->kernelSources.etThreadListEntry;
    case KSW_DYN_FIELD_ID_ET_START_ADDRESS:
        return state->kernelSources.etStartAddress;
    case KSW_DYN_FIELD_ID_ET_WIN32_START_ADDRESS:
        return state->kernelSources.etWin32StartAddress;
    case KSW_DYN_FIELD_ID_KT_READ_OPERATION_COUNT:
        return state->kernelSources.ktReadOperationCount;
    case KSW_DYN_FIELD_ID_KT_WRITE_OPERATION_COUNT:
        return state->kernelSources.ktWriteOperationCount;
    case KSW_DYN_FIELD_ID_KT_OTHER_OPERATION_COUNT:
        return state->kernelSources.ktOtherOperationCount;
    case KSW_DYN_FIELD_ID_KT_READ_TRANSFER_COUNT:
        return state->kernelSources.ktReadTransferCount;
    case KSW_DYN_FIELD_ID_KT_WRITE_TRANSFER_COUNT:
        return state->kernelSources.ktWriteTransferCount;
    case KSW_DYN_FIELD_ID_KT_OTHER_TRANSFER_COUNT:
        return state->kernelSources.ktOtherTransferCount;
    case KSW_DYN_FIELD_ID_MM_SECTION_CONTROL_AREA:
        return state->kernelSources.mmSectionControlArea;
    case KSW_DYN_FIELD_ID_MM_CONTROL_AREA_LIST_HEAD:
        return state->kernelSources.mmControlAreaListHead;
    case KSW_DYN_FIELD_ID_MM_CONTROL_AREA_LOCK:
        return state->kernelSources.mmControlAreaLock;
    case KSW_DYN_FIELD_ID_ALPC_COMMUNICATION_INFO:
        return state->kernelSources.alpcCommunicationInfo;
    case KSW_DYN_FIELD_ID_ALPC_OWNER_PROCESS:
        return state->kernelSources.alpcOwnerProcess;
    case KSW_DYN_FIELD_ID_ALPC_CONNECTION_PORT:
        return state->kernelSources.alpcConnectionPort;
    case KSW_DYN_FIELD_ID_ALPC_SERVER_COMMUNICATION_PORT:
        return state->kernelSources.alpcServerCommunicationPort;
    case KSW_DYN_FIELD_ID_ALPC_CLIENT_COMMUNICATION_PORT:
        return state->kernelSources.alpcClientCommunicationPort;
    case KSW_DYN_FIELD_ID_ALPC_HANDLE_TABLE:
        return state->kernelSources.alpcHandleTable;
    case KSW_DYN_FIELD_ID_ALPC_HANDLE_TABLE_LOCK:
        return state->kernelSources.alpcHandleTableLock;
    case KSW_DYN_FIELD_ID_ALPC_ATTRIBUTES:
        return state->kernelSources.alpcAttributes;
    case KSW_DYN_FIELD_ID_ALPC_ATTRIBUTES_FLAGS:
        return state->kernelSources.alpcAttributesFlags;
    case KSW_DYN_FIELD_ID_ALPC_PORT_CONTEXT:
        return state->kernelSources.alpcPortContext;
    case KSW_DYN_FIELD_ID_ALPC_PORT_OBJECT_LOCK:
        return state->kernelSources.alpcPortObjectLock;
    case KSW_DYN_FIELD_ID_ALPC_SEQUENCE_NO:
        return state->kernelSources.alpcSequenceNo;
    case KSW_DYN_FIELD_ID_ALPC_STATE:
        return state->kernelSources.alpcState;
    case KSW_DYN_FIELD_ID_LX_PICO_PROC:
        return state->lxcoreSources.lxPicoProc;
    case KSW_DYN_FIELD_ID_LX_PICO_PROC_INFO:
        return state->lxcoreSources.lxPicoProcInfo;
    case KSW_DYN_FIELD_ID_LX_PICO_PROC_INFO_PID:
        return state->lxcoreSources.lxPicoProcInfoPid;
    case KSW_DYN_FIELD_ID_LX_PICO_THRD_INFO:
        return state->lxcoreSources.lxPicoThrdInfo;
    case KSW_DYN_FIELD_ID_LX_PICO_THRD_INFO_TID:
        return state->lxcoreSources.lxPicoThrdInfoTid;
    case KSW_DYN_FIELD_ID_EP_PROTECTION:
        return state->kernelSources.epProtection;
    case KSW_DYN_FIELD_ID_EP_SIGNATURE_LEVEL:
        return state->kernelSources.epSignatureLevel;
    case KSW_DYN_FIELD_ID_EP_SECTION_SIGNATURE_LEVEL:
        return state->kernelSources.epSectionSignatureLevel;
    case KSW_DYN_FIELD_ID_KLDR_IN_LOAD_ORDER_LINKS:
        return state->kernelSources.kldrInLoadOrderLinks;
    case KSW_DYN_FIELD_ID_KLDR_DLL_BASE:
        return state->kernelSources.kldrDllBase;
    case KSW_DYN_FIELD_ID_KLDR_SIZE_OF_IMAGE:
        return state->kernelSources.kldrSizeOfImage;
    case KSW_DYN_FIELD_ID_KLDR_FULL_DLL_NAME:
        return state->kernelSources.kldrFullDllName;
    case KSW_DYN_FIELD_ID_KLDR_BASE_DLL_NAME:
        return state->kernelSources.kldrBaseDllName;
    case KSW_DYN_FIELD_ID_KLDR_FLAGS:
        return state->kernelSources.kldrFlags;
    case KSW_DYN_FIELD_ID_DO_DRIVER_START:
        return state->kernelSources.doDriverStart;
    case KSW_DYN_FIELD_ID_DO_DRIVER_SIZE:
        return state->kernelSources.doDriverSize;
    case KSW_DYN_FIELD_ID_DO_DRIVER_SECTION:
        return state->kernelSources.doDriverSection;
    case KSW_DYN_FIELD_ID_DO_MAJOR_FUNCTION:
        return state->kernelSources.doMajorFunction;
    case KSW_DYN_FIELD_ID_DO_FAST_IO_DISPATCH:
        return state->kernelSources.doFastIoDispatch;
    case KSW_DYN_FIELD_ID_DO_DRIVER_UNLOAD:
        return state->kernelSources.doDriverUnload;
    case KSW_DYN_FIELD_ID_ULD_NAME:
        return state->kernelSources.uldName;
    case KSW_DYN_FIELD_ID_ULD_START_ADDRESS:
        return state->kernelSources.uldStartAddress;
    case KSW_DYN_FIELD_ID_ULD_END_ADDRESS:
        return state->kernelSources.uldEndAddress;
    case KSW_DYN_FIELD_ID_ULD_CURRENT_TIME:
        return state->kernelSources.uldCurrentTime;
    case KSW_DYN_FIELD_ID_ULD_TYPE_SIZE:
        return state->kernelSources.uldTypeSize;
    case KSW_DYN_FIELD_ID_RTL_AVL_BALANCED_ROOT:
        return state->kernelSources.rtlAvlBalancedRoot;
    case KSW_DYN_FIELD_ID_RTL_AVL_ORDERED_POINTER:
        return state->kernelSources.rtlAvlOrderedPointer;
    case KSW_DYN_FIELD_ID_RTL_AVL_WHICH_ORDERED_ELEMENT:
        return state->kernelSources.rtlAvlWhichOrderedElement;
    case KSW_DYN_FIELD_ID_RTL_AVL_NUMBER_GENERIC_TABLE_ELEMENTS:
        return state->kernelSources.rtlAvlNumberGenericTableElements;
    case KSW_DYN_FIELD_ID_RTL_AVL_DEPTH_OF_TREE:
        return state->kernelSources.rtlAvlDepthOfTree;
    case KSW_DYN_FIELD_ID_RTL_AVL_RESTART_KEY:
        return state->kernelSources.rtlAvlRestartKey;
    case KSW_DYN_FIELD_ID_RTL_AVL_DELETE_COUNT:
        return state->kernelSources.rtlAvlDeleteCount;
    case KSW_DYN_FIELD_ID_RTL_AVL_TYPE_SIZE:
        return state->kernelSources.rtlAvlTypeSize;
    case KSW_DYN_FIELD_ID_PIDDB_DRIVER_NAME:
        return state->kernelSources.piDdbDriverName;
    case KSW_DYN_FIELD_ID_PIDDB_TIME_DATE_STAMP:
        return state->kernelSources.piDdbTimeDateStamp;
    case KSW_DYN_FIELD_ID_PIDDB_LOAD_STATUS:
        return state->kernelSources.piDdbLoadStatus;
    case KSW_DYN_FIELD_ID_PIDDB_TYPE_SIZE:
        return state->kernelSources.piDdbTypeSize;
    case KSW_DYN_FIELD_ID_KG_PSP_CID_TABLE:
        return state->kernelGlobalSources.pspCidTable;
    case KSW_DYN_FIELD_ID_KG_PS_LOADED_MODULE_LIST:
        return state->kernelGlobalSources.psLoadedModuleList;
    case KSW_DYN_FIELD_ID_KG_MM_UNLOADED_DRIVERS:
        return state->kernelGlobalSources.mmUnloadedDrivers;
    case KSW_DYN_FIELD_ID_KG_PIDDB_CACHE_TABLE:
        return state->kernelGlobalSources.piDdbCacheTable;
    case KSW_DYN_FIELD_ID_KG_PIDDB_LOCK:
        return state->kernelGlobalSources.piDdbLock;
    case KSW_DYN_FIELD_ID_KG_KE_SERVICE_DESCRIPTOR_TABLE_SHADOW:
        return state->kernelGlobalSources.keServiceDescriptorTableShadow;
    case KSW_DYN_FIELD_ID_KG_MM_LAST_UNLOADED_DRIVER:
        return state->kernelGlobalSources.mmLastUnloadedDriver;
    case KSW_DYN_FIELD_ID_CB_PSP_CREATE_PROCESS_NOTIFY_ROUTINE:
        return state->callbackGlobalSources.pspCreateProcessNotifyRoutine;
    case KSW_DYN_FIELD_ID_CB_PSP_CREATE_THREAD_NOTIFY_ROUTINE:
        return state->callbackGlobalSources.pspCreateThreadNotifyRoutine;
    case KSW_DYN_FIELD_ID_CB_PSP_LOAD_IMAGE_NOTIFY_ROUTINE:
        return state->callbackGlobalSources.pspLoadImageNotifyRoutine;
    case KSW_DYN_FIELD_ID_CB_PSP_NOTIFY_ENABLE_MASK:
        return state->callbackGlobalSources.pspNotifyEnableMask;
    case KSW_DYN_FIELD_ID_CB_CM_CALLBACK_LIST_HEAD:
        return state->callbackGlobalSources.cmCallbackListHead;
    case KSW_DYN_FIELD_ID_CB_OBJECT_TYPE_CALLBACK_LIST:
        return state->callbackOffsetSources.objectTypeCallbackList;
    case KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_ENTRY_LIST:
        return state->callbackOffsetSources.callbackEntryItemEntryList;
    case KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_PRE_OPERATION:
        return state->callbackOffsetSources.callbackEntryItemPreOperation;
    case KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_POST_OPERATION:
        return state->callbackOffsetSources.callbackEntryItemPostOperation;
    case KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_OPERATIONS:
        return state->callbackOffsetSources.callbackEntryItemOperations;
    case KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ITEM_CALLBACK_ENTRY:
        return state->callbackOffsetSources.callbackEntryItemCallbackEntry;
    case KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_ALTITUDE:
        return state->callbackOffsetSources.callbackEntryAltitude;
    case KSW_DYN_FIELD_ID_CB_CALLBACK_ENTRY_REGISTRATION_CONTEXT:
        return state->callbackOffsetSources.callbackEntryRegistrationContext;
    default:
        return KSW_DYN_FIELD_SOURCE_UNAVAILABLE;
    }
}

static VOID
kswordArkDynDataCopyAnsi(
    _Out_writes_bytes_(destinationBytes) CHAR* destination,
    _In_ size_t destinationBytes,
    _In_opt_z_ PCSTR source
    )
/*++

Routine Description:

    Copy a small descriptor string into an IOCTL response row while guaranteeing
    NUL termination.

Arguments:

    Destination - Output char buffer.
    DestinationBytes - Size of Destination in bytes.
    Source - Optional source string.

Return Value:

    None.

--*/
{
    if (destination == NULL || destinationBytes == 0U) {
        return;
    }

    destination[0] = '\0';
    if (source == NULL) {
        return;
    }

    (VOID)RtlStringCbCopyNA(destination, destinationBytes, source, destinationBytes - 1U);
    destination[destinationBytes - 1U] = '\0';
}

static PCSTR
kswordArkDynDataSourceName(
    _In_ ULONG source
    )
/*++

Routine Description:

    Convert a field source code into a stable short diagnostic label.

Arguments:

    Source - KSW_DYN_FIELD_SOURCE_* value.

Return Value:

    Static string label.

--*/
{
    switch (source) {
    case KSW_DYN_FIELD_SOURCE_SYSTEM_INFORMER:
        return "System Informer";
    case KSW_DYN_FIELD_SOURCE_RUNTIME_PATTERN:
        return "Runtime pattern";
    case KSW_DYN_FIELD_SOURCE_KSWORD_EXTRA_TABLE:
        return "Ksword extra";
    case KSW_DYN_FIELD_SOURCE_PDB_PROFILE:
        return "PDB profile";
    default:
        return "Unavailable";
    }
}

static BOOLEAN
kswordArkDynDataIsOffsetPresent(
    _In_ ULONG offset
    )
/*++

Routine Description:

    normalize DynData field availability. System Informer marks missing fields
    as 0xffff; Ksword stores unavailable fields as ULONG_MAX.

Arguments:

    Offset - Offset value to test.

Return Value:

    TRUE when usable, FALSE when unavailable.

--*/
{
    return (offset != KSW_DYN_OFFSET_UNAVAILABLE && offset != 0x0000FFFFUL) ? TRUE : FALSE;
}

ULONG
kswordArkDynDataCountFieldDescriptors(
    VOID
    )
/*++

Routine Description:

    Return the number of field descriptors exported to user mode.

Arguments:

    None.

Return Value:

    descriptor count.

--*/
{
    return (ULONG)(sizeof(kGKswordDynFieldBindings) / sizeof(kGKswordDynFieldBindings[0]));
}

ULONG
kswordArkDynDataCopyFieldDescriptors(
    _In_ const KswDynState* state,
    _Out_writes_opt_(entryCapacity) KSW_DYN_FIELD_ENTRY* entries,
    _In_ ULONG entryCapacity
    )
/*++

Routine Description:

    Build the public field table from the active state and static descriptor
    metadata. The caller may pass NULL Entries to query only total count.

Arguments:

    State - DynData state snapshot.
    Entries - Optional output entry array.
    EntryCapacity - Number of writable output entries.

Return Value:

    Number of entries copied to Entries.

--*/
{
    ULONG index = 0;
    ULONG copied = 0;
    ULONG totalCount = kswordArkDynDataCountFieldDescriptors();

    if (state == NULL || entries == NULL || entryCapacity == 0U) {
        return 0U;
    }

    for (index = 0; index < totalCount && copied < entryCapacity; ++index) {
        const KswDynFieldBinding* binding = &kGKswordDynFieldBindings[index];
        const ULONG kOffset = kswordArkDynDataReadBoundOffset(state, binding);
        const ULONG kSource = kswordArkDynDataReadBoundSource(state, binding);
        KSW_DYN_FIELD_ENTRY* entry = &entries[copied];

        RtlZeroMemory(entry, sizeof(*entry));
        entry->fieldId = binding->fieldId;
        entry->offset = kOffset;
        entry->source = kswordArkDynDataIsOffsetPresent(kOffset) ? kSource : KSW_DYN_FIELD_SOURCE_UNAVAILABLE;
        entry->capabilityMask = binding->capabilityMask;
        entry->flags = binding->required ? KSW_DYN_FIELD_FLAG_REQUIRED : KSW_DYN_FIELD_FLAG_OPTIONAL;
        if (kswordArkDynDataIsOffsetPresent(kOffset)) {
            entry->flags |= KSW_DYN_FIELD_FLAG_PRESENT;
        }

        kswordArkDynDataCopyAnsi(entry->fieldName, sizeof(entry->fieldName), binding->fieldName);
        kswordArkDynDataCopyAnsi(entry->featureName, sizeof(entry->featureName), binding->featureName);
        kswordArkDynDataCopyAnsi(entry->sourceName, sizeof(entry->sourceName), kswordArkDynDataSourceName(entry->source));
        copied += 1U;
    }

    return copied;
}

static BOOLEAN
kswordArkDynDataHasAll(
    _In_ const ULONG* offsets,
    _In_ ULONG count
    )
/*++

Routine Description:

    Test a small dependency list for all-required field availability.

Arguments:

    Offsets - Dependency offset array.
    Count - Number of offsets in the array.

Return Value:

    TRUE when all fields are present; otherwise FALSE.

--*/
{
    ULONG index = 0;

    if (offsets == NULL || count == 0U) {
        return FALSE;
    }

    for (index = 0; index < count; ++index) {
        if (!kswordArkDynDataIsOffsetPresent(offsets[index])) {
            return FALSE;
        }
    }

    return TRUE;
}

static BOOLEAN
kswordArkDynDataHasAny(
    _In_ const ULONG* offsets,
    _In_ ULONG count
    )
/*++

Routine Description:

    Test whether at least one offset in a small optional dependency list is
    present.

Arguments:

    Offsets - Optional dependency offset array.
    Count - Number of offsets in the array.

Return Value:

    TRUE when one or more offsets are present; otherwise FALSE.

--*/
{
    ULONG index = 0;

    if (offsets == NULL || count == 0U) {
        return FALSE;
    }

    for (index = 0; index < count; ++index) {
        if (kswordArkDynDataIsOffsetPresent(offsets[index])) {
            return TRUE;
        }
    }

    return FALSE;
}

ULONG64
kswordArkDynDataComputeCapabilities(
    _In_ const KswDynState* state
    )
/*++

Routine Description:

    Compute feature capability flags from field availability. Capabilities are
    strict: a missing required field disables the dependent feature.

Arguments:

    State - DynData state snapshot with converted offsets.

Return Value:

    KSW_CAP_* bit mask.

--*/
{
    ULONG64 capabilities = KSW_DYN_CAPABILITY_NONE;

    if (state == NULL) {
        return KSW_DYN_CAPABILITY_NONE;
    }

    const ULONG kObjectTypeFields[] = { state->kernel.otName, state->kernel.otIndex };
    const ULONG kProcessListFields[] = { state->kernel.epUniqueProcessId, state->kernel.epActiveProcessLinks, state->kernel.epThreadListHead, state->kernel.epImageFileName, state->kernel.epToken };
    const ULONG kHandleTableFields[] = { state->kernel.epObjectTable, state->kernel.obDecodeShift, state->kernel.obAttributesShift, state->kernel.otName, state->kernel.otIndex };
    const ULONG kCidTableFields[] = { state->kernelGlobals.pspCidTable, state->kernel.htTableCode, state->kernel.hteLowValue };
    const ULONG kThreadStackFields[] = { state->kernel.ktInitialStack, state->kernel.ktStackLimit, state->kernel.ktStackBase, state->kernel.ktKernelStack };
    const ULONG kThreadListFields[] = { state->kernel.epThreadListHead, state->kernel.ktProcess, state->kernel.etCid, state->kernel.etThreadListEntry, state->kernel.etStartAddress };
    const ULONG kThreadIoFields[] = { state->kernel.ktReadOperationCount, state->kernel.ktWriteOperationCount, state->kernel.ktOtherOperationCount, state->kernel.ktReadTransferCount, state->kernel.ktWriteTransferCount, state->kernel.ktOtherTransferCount };
    const ULONG kAlpcFields[] = { state->kernel.alpcCommunicationInfo, state->kernel.alpcOwnerProcess, state->kernel.alpcConnectionPort, state->kernel.alpcServerCommunicationPort, state->kernel.alpcClientCommunicationPort, state->kernel.alpcHandleTable, state->kernel.alpcHandleTableLock, state->kernel.alpcAttributes, state->kernel.alpcAttributesFlags, state->kernel.alpcPortContext, state->kernel.alpcPortObjectLock, state->kernel.alpcSequenceNo, state->kernel.alpcState };
    const ULONG kSectionFields[] = { state->kernel.epSectionObject, state->kernel.mmSectionControlArea, state->kernel.mmControlAreaListHead, state->kernel.mmControlAreaLock };
    const ULONG kKernelModuleListFields[] = { state->kernel.kldrInLoadOrderLinks, state->kernel.kldrDllBase, state->kernel.kldrSizeOfImage, state->kernel.kldrFullDllName, state->kernel.kldrBaseDllName };
    const ULONG kDriverObjectFields[] = { state->kernel.doDriverStart, state->kernel.doDriverSize, state->kernel.doDriverSection, state->kernel.doMajorFunction, state->kernel.doDriverUnload };
    const ULONG kProtectionFields[] = { state->kernel.epProtection, state->kernel.epSignatureLevel, state->kernel.epSectionSignatureLevel };
    const ULONG kEtwFields[] = { state->kernel.egeGuid, state->kernel.ereGuidEntry };
    const ULONG kLxcoreFields[] = { state->lxcoreOffsets.lxPicoProc, state->lxcoreOffsets.lxPicoProcInfo, state->lxcoreOffsets.lxPicoProcInfoPid, state->lxcoreOffsets.lxPicoThrdInfo, state->lxcoreOffsets.lxPicoThrdInfoTid };
    const ULONG kKernelGlobalFields[] = { state->kernelGlobals.pspCidTable, state->kernelGlobals.psLoadedModuleList, state->kernelGlobals.mmUnloadedDrivers, state->kernelGlobals.piDdbCacheTable, state->kernelGlobals.piDdbLock, state->kernelGlobals.keServiceDescriptorTableShadow };
    const ULONG kCallbackNotifyGlobals[] = { state->callbackGlobals.pspCreateProcessNotifyRoutine, state->callbackGlobals.pspCreateThreadNotifyRoutine, state->callbackGlobals.pspLoadImageNotifyRoutine };
    const ULONG kCallbackRegistryGlobals[] = { state->callbackGlobals.cmCallbackListHead };
    const ULONG kCallbackObjectFields[] = { state->callbackOffsets.objectTypeCallbackList, state->callbackOffsets.callbackEntryItemPreOperation, state->callbackOffsets.callbackEntryItemPostOperation, state->callbackOffsets.callbackEntryItemOperations, state->callbackOffsets.callbackEntryItemCallbackEntry };
    const ULONG kTokenIntegrityFields[] = { state->kernel.epToken, state->kernel.tokUserAndGroupCount, state->kernel.tokUserAndGroups, state->kernel.tokIntegrityLevelIndex, state->kernel.tokMandatoryPolicy };
    const ULONG kTokenPrivateFields[] = { state->kernel.tokTokenSource, state->kernel.tokTokenId, state->kernel.tokAuthenticationId, state->kernel.tokParentTokenId, state->kernel.tokExpirationTime, state->kernel.tokTokenLock, state->kernel.tokModifiedId, state->kernel.tokPrivileges, state->kernel.tokAuditPolicy, state->kernel.tokSessionId, state->kernel.tokUserAndGroupCount, state->kernel.tokRestrictedSidCount, state->kernel.tokVariableLength, state->kernel.tokDynamicCharged, state->kernel.tokDynamicAvailable, state->kernel.tokDefaultOwnerIndex, state->kernel.tokUserAndGroups, state->kernel.tokRestrictedSids, state->kernel.tokPrimaryGroup, state->kernel.tokDynamicPart, state->kernel.tokDefaultDacl, state->kernel.tokTokenType, state->kernel.tokImpersonationLevel, state->kernel.tokTokenFlags, state->kernel.tokTokenInUse, state->kernel.tokIntegrityLevelIndex, state->kernel.tokMandatoryPolicy, state->kernel.tokLogonSession, state->kernel.tokOriginatingLogonSession, state->kernel.tokSidHash, state->kernel.tokRestrictedSidHash, state->kernel.tokPSecurityAttributes, state->kernel.tokPackage, state->kernel.tokCapabilities, state->kernel.tokCapabilityCount, state->kernel.tokCapabilitiesHash, state->kernel.tokLowboxNumberEntry, state->kernel.tokLowboxHandlesEntry, state->kernel.tokPClaimAttributes, state->kernel.tokTrustLevelSid, state->kernel.tokTrustLinkedToken, state->kernel.tokIntegrityLevelSidValue, state->kernel.tokTokenSidValues, state->kernel.tokSessionObject, state->kernel.tokVariablePart };

    if (state->ntosActive) {
        capabilities |= KSW_CAP_DYN_NTOS_ACTIVE;
    }
    if (state->lxcoreActive) {
        capabilities |= KSW_CAP_DYN_LXCORE_ACTIVE;
    }
    if (kswordArkDynDataHasAll(kObjectTypeFields, RTL_NUMBER_OF(kObjectTypeFields))) {
        capabilities |= KSW_CAP_OBJECT_TYPE_FIELDS;
    }
    if (kswordArkDynDataHasAll(kProcessListFields, RTL_NUMBER_OF(kProcessListFields))) {
        capabilities |= KSW_CAP_PROCESS_LIST_FIELDS;
    }
    if (kswordArkDynDataHasAll(kHandleTableFields, RTL_NUMBER_OF(kHandleTableFields))) {
        capabilities |= KSW_CAP_HANDLE_TABLE_DECODE | KSW_CAP_PROCESS_OBJECT_TABLE;
    }
    if (kswordArkDynDataHasAll(kCidTableFields, RTL_NUMBER_OF(kCidTableFields))) {
        capabilities |= KSW_CAP_CID_TABLE_WALK;
    }
    if (kswordArkDynDataHasAll(kThreadStackFields, RTL_NUMBER_OF(kThreadStackFields))) {
        capabilities |= KSW_CAP_THREAD_STACK_FIELDS;
    }
    if (kswordArkDynDataHasAll(kThreadListFields, RTL_NUMBER_OF(kThreadListFields))) {
        capabilities |= KSW_CAP_THREAD_LIST_FIELDS;
    }
    if (kswordArkDynDataHasAll(kThreadIoFields, RTL_NUMBER_OF(kThreadIoFields))) {
        capabilities |= KSW_CAP_THREAD_IO_COUNTERS;
    }
    if (kswordArkDynDataHasAll(kAlpcFields, RTL_NUMBER_OF(kAlpcFields))) {
        capabilities |= KSW_CAP_ALPC_FIELDS;
    }
    if (kswordArkDynDataHasAll(kSectionFields, RTL_NUMBER_OF(kSectionFields))) {
        capabilities |= KSW_CAP_SECTION_CONTROL_AREA;
    }
    if (kswordArkDynDataHasAll(kKernelModuleListFields, RTL_NUMBER_OF(kKernelModuleListFields))) {
        capabilities |= KSW_CAP_KERNEL_MODULE_LIST_FIELDS;
    }
    if (kswordArkDynDataHasAll(kDriverObjectFields, RTL_NUMBER_OF(kDriverObjectFields))) {
        capabilities |= KSW_CAP_DRIVER_OBJECT_FIELDS;
    }
    if (kswordArkDynDataHasAll(kProtectionFields, RTL_NUMBER_OF(kProtectionFields))) {
        capabilities |= KSW_CAP_PROCESS_PROTECTION_PATCH;
    }
    if (kswordArkDynDataHasAll(kEtwFields, RTL_NUMBER_OF(kEtwFields))) {
        capabilities |= KSW_CAP_ETW_GUID_FIELDS;
    }
    if (state->lxcoreActive && kswordArkDynDataHasAll(kLxcoreFields, RTL_NUMBER_OF(kLxcoreFields))) {
        capabilities |= KSW_CAP_WSL_LXCORE_FIELDS;
    }
    if (state->callbackProfileActive && kswordArkDynDataHasAll(kCallbackNotifyGlobals, RTL_NUMBER_OF(kCallbackNotifyGlobals))) {
        capabilities |= KSW_CAP_CALLBACK_NOTIFY_GLOBALS;
    }
    if (state->callbackProfileActive && kswordArkDynDataHasAll(kCallbackRegistryGlobals, RTL_NUMBER_OF(kCallbackRegistryGlobals))) {
        capabilities |= KSW_CAP_CALLBACK_REGISTRY_GLOBALS;
    }
    if (state->callbackProfileActive && kswordArkDynDataHasAll(kCallbackObjectFields, RTL_NUMBER_OF(kCallbackObjectFields))) {
        capabilities |= KSW_CAP_CALLBACK_OBJECT_FIELDS;
    }
    if (kswordArkDynDataHasAny(kKernelGlobalFields, RTL_NUMBER_OF(kKernelGlobalFields))) {
        capabilities |= KSW_CAP_KERNEL_GLOBALS;
    }

    if (kswordArkDynDataHasAll(kTokenIntegrityFields, RTL_NUMBER_OF(kTokenIntegrityFields))) {
        capabilities |= KSW_CAP_TOKEN_INTEGRITY_FIELDS;
    }
    if (kswordArkDynDataHasAll(kTokenPrivateFields, RTL_NUMBER_OF(kTokenPrivateFields))) {
        capabilities |= KSW_CAP_TOKEN_PRIVATE_FIELDS;
    }
    return capabilities;
}
