/*++

Module Name:

    callback_external_safe.c

Abstract:

    Safe handling for callback classes that require version-gated private data.

Environment:

    Kernel-mode Driver Framework

--*/

#include "callback_external_safe.h"
#include "ark/ark_dyndata.h"

VOID
kswordArkCallbackExternalSafeAddCallbacks(
    _Inout_ KswordArkCallbackEnumBuilder* builder
    )
/*++

Routine Description:

    Add documentation for external removal capabilities of ETW/Object/Registry. Note: The actual enumeration rows for Object and
    Registry are generated by the existing private read-only scan phase. ETW currently only supports DynData offset capabilities
    and cannot safely locate global table entries; thus, this section only adds an explicit state for 'unsafe, do not remove'.

Arguments:

    Builder: Input/output enumeration response builder.

Return Value:

    No return value.

--*/
{
    KSWORD_ARK_CALLBACK_ENUM_ENTRY* entry = NULL;
    KswDynState dynState;

    if (builder == NULL) {
        return;
    }

    RtlZeroMemory(&dynState, sizeof(dynState));
    kswordArkDynDataSnapshot(&dynState);

    entry = kswordArkCallbackEnumReserveEntry(builder);
    if (entry != NULL) {
        entry->callbackClass = KSWORD_ARK_CALLBACK_ENUM_CLASS_ETW_PROVIDER;
        entry->source = KSWORD_ARK_CALLBACK_ENUM_SOURCE_ETW_DYNDATA;
        entry->status = KSWORD_ARK_CALLBACK_ENUM_STATUS_UNSUPPORTED;
        entry->lastStatus = STATUS_NOT_SUPPORTED;
        entry->fieldFlags = KSWORD_ARK_CALLBACK_ENUM_FIELD_NAME |
            KSWORD_ARK_CALLBACK_ENUM_FIELD_CONTEXT_ADDRESS;
        entry->contextAddress = ((ULONG64)dynState.kernel.egeGuid << 32) |
            (ULONG64)dynState.kernel.ereGuidEntry;
        kswordArkCallbackEnumCopyWide(
            entry->name,
            RTL_NUMBER_OF(entry->name),
            L"ETW callback external capability");
        (VOID)RtlStringCbPrintfW(
            entry->detail,
            sizeof(entry->detail),
            L"ETW 仅检测到 DynData 能力位 cap=0x%llX；未安全定位 ETW 全局 Guid 表，枚举/移除均返回 STATUS_NOT_SUPPORTED。",
            dynState.capabilityMask);
    }

    kswordArkCallbackEnumAddUnsupportedRow(
        builder,
        KSWORD_ARK_CALLBACK_ENUM_CLASS_OBJECT,
        L"Object callback external removal",
        L"Object callback 可由现有私有只读枚举展示候选项；缺少公开按外部 registration handle 卸载 API，移除返回 STATUS_NOT_SUPPORTED。");
    kswordArkCallbackEnumAddUnsupportedRow(
        builder,
        KSWORD_ARK_CALLBACK_ENUM_CLASS_REGISTRY,
        L"Registry callback external removal",
        L"Registry callback 可由现有 CmCallbackListHead 只读枚举展示候选项；无法从函数地址安全恢复 cookie，移除返回 STATUS_NOT_SUPPORTED。");
}

NTSTATUS
kswordArkCallbackExternalSafeRemove(
    _In_ const KSWORD_ARK_REMOVE_EXTERNAL_CALLBACK_REQUEST* requestPacket,
    _Inout_ KSWORD_ARK_REMOVE_EXTERNAL_CALLBACK_RESPONSE* responsePacket
    )
/*++

Routine Description:

    Handles external callback categories that require internal structures for removal. Note: This
    function performs only parameter validation and kernel module range gating. It does not blindly
    write to Object/Registry/ETW private lists, nor does it disable PatchGuard or any system protection.

Arguments:

    RequestPacket - Input removal request.
    ResponsePacket - Input/output removal response.

Return Value:

    Return STATUS_INVALID_PARAMETER if the address is invalid; return STATUS_NOT_SUPPORTED
    if the category requires internal structures but no safe path exists.

--*/
{
    NTSTATUS status = STATUS_SUCCESS;
    KswordArkCallbackModuleCache moduleCache;
    WCHAR modulePath[KSWORD_ARK_EXTERNAL_CALLBACK_MODULE_NAME_MAX_CHARS];
    ULONG64 moduleBase = 0ULL;
    ULONG moduleSize = 0UL;

    if (requestPacket == NULL || responsePacket == NULL) {
        return STATUS_INVALID_PARAMETER;
    }
    if (requestPacket->callbackAddress == 0ULL) {
        return STATUS_INVALID_PARAMETER;
    }

    switch (requestPacket->callbackClass) {
    case KSWORD_ARK_EXTERNAL_CALLBACK_REMOVE_TYPE_OBJECT:
    case KSWORD_ARK_EXTERNAL_CALLBACK_REMOVE_TYPE_REGISTRY:
    case KSWORD_ARK_EXTERNAL_CALLBACK_REMOVE_TYPE_ETW_PROVIDER:
        break;

    default:
        return STATUS_INVALID_PARAMETER;
    }

    RtlZeroMemory(modulePath, sizeof(modulePath));
    kswordArkCallbackEnumInitModuleCache(&moduleCache);
    status = kswordArkCallbackEnumResolveModuleByAddressCached(
        &moduleCache,
        requestPacket->callbackAddress,
        modulePath,
        RTL_NUMBER_OF(modulePath),
        &moduleBase,
        &moduleSize);
    kswordArkCallbackEnumFreeModuleCache(&moduleCache);
    if (!NT_SUCCESS(status)) {
        return STATUS_INVALID_PARAMETER;
    }

    responsePacket->mappingFlags |= KSWORD_ARK_EXTERNAL_CALLBACK_MAPPING_FLAG_MODULE;
    responsePacket->moduleBase = moduleBase;
    responsePacket->moduleSize = moduleSize;
    kswordArkCallbackEnumCopyWide(
        responsePacket->modulePath,
        RTL_NUMBER_OF(responsePacket->modulePath),
        modulePath);

    return STATUS_NOT_SUPPORTED;
}
