#pragma once

#include <QString>
#include <QStringList>
#include <QWidget>

#include <atomic>
#include <cstdint>
#include <memory>
#include <string>

class QCheckBox;
class QEvent;
class QLabel;
class QLineEdit;
class QPushButton;
class QTabWidget;
class QTableWidget;
struct ScannerAsyncState;

namespace ks::scanner
{
    struct AtomicPatchResult;
    struct BinaryScanResult;
}

// ScannerDock:
// - Provide structured scanning and attack path detection pages for PE/ELF/Mach-O/ISO9660;
// - Provide a safe editing page for regular files featuring 'raw byte comparison + equal-length replacement + atomic commit'.
// - Both scanning and large file copying are executed in a thread pool to avoid blocking the main interface.
class ScannerDock final : public QWidget
{
public:
    // Constructor: Creates the scanner interface and enters the 'waiting for file selection' state.
    // Parameter parent: Qt parent widget; return value: none.
    explicit ScannerDock(QWidget* parent = nullptr);

    // Destructor purpose: invalidate asynchronous results that have not yet returned to the UI thread.
    ~ScannerDock() override;

protected:
    // changeEvent: Re-translate fixed controls and displayed scan results when the language is switched.
    // Parameter event: Qt event; Return value: None.
    void changeEvent(QEvent* event) override;

private:
    // The following functions are responsible for building/translating the UI, selecting targets, and starting asynchronous scanning or writing.
    void buildUi();
    void retranslateUi();
    void chooseFile();
    void beginScan();
    void beginPatch();

    // finishScan/finishPatch purpose: accept only background results for the current generation and update the UI.
    // generation: task generation; scannedPath/patchedPath: actual target paths used by the task.
    void finishScan(
        std::uint64_t generation,
        const QString& scannedPath,
        std::shared_ptr<ks::scanner::BinaryScanResult> result);
    void finishPatch(
        std::uint64_t generation,
        const QString& patchedPath,
        std::shared_ptr<ks::scanner::AtomicPatchResult> result);

    // renderResult: Renders the format-neutral model into a summary, header, structure table, and diagnostic page.
    void renderResult(const ks::scanner::BinaryScanResult& result);
    void clearResultTabs();

    // createReadOnlyTable purpose: Creates a unified read-only table; the caller is responsible for populating rows and columns.
    QTableWidget* createReadOnlyTable(QWidget* parent = nullptr) const;

    // createStructuredTablePage purpose: Create complementary A/B/C column groups and header column menus for wide tables.
    QWidget* createStructuredTablePage(QTableWidget* table, int columnCount) const;

    // createAttackPathPage purpose: Displays rule conclusions, scores, and itemized verifiable evidence.
    QWidget* createAttackPathPage(const ks::scanner::BinaryScanResult& result) const;

    // The following helper functions uniformly handle localization, diagnostic level, and status bar state.
    QString translated(const char* key, const char* fallback) const;
    QString localizedTableTitle(const std::string& tableId, const std::string& fallback) const;
    QString localizedColumnTitle(const std::string& fallback) const;
    QString localizedTableValue(
        const std::string& tableId,
        int column,
        const std::string& fallback) const;
    QString localizedDiagnosticMessage(
        const std::string& code,
        const std::string& fallback) const;
    QString diagnosticSeverityText(int severity) const;
    QString attackPathSeverityText(int severity) const;
    QString attackPathStageText(const std::string& stage) const;
    QString attackPathEvidenceText(const std::string& code) const;
    void setStatus(const char* key, const char* fallback, const QStringList& arguments = {});
    void refreshStatus();
    void setScanBusy(bool busy);
    void setPatchBusy(bool busy);

    QLabel* pathLabel_ = nullptr; // m_pathLabel: Target path field title.
    QLineEdit* pathEdit_ = nullptr; // m_pathEdit: Current scan/edit target path.
    QPushButton* browseButton_ = nullptr; // m_browseButton: Open standard file picker.
    QPushButton* scanButton_ = nullptr; // m_scanButton: Start structured scan.
    QLabel* statusLabel_ = nullptr; // m_statusLabel: Display the current task and final result.

    QTabWidget* mainTabs_ = nullptr; // m_mainTabs: Tabs for scanning and security editing functions.
    QTabWidget* resultTabs_ = nullptr; // m_resultTabs: Structured sub-pages generated by this scan.
    QWidget* inspectionPage_ = nullptr; // m_inspectionPage: Read-only parsing page container.
    QWidget* editorPage_ = nullptr; // m_editorPage: Container for the equal-length byte editing page.

    QLabel* offsetLabel_ = nullptr; // m_offsetLabel: File offset field header.
    QLineEdit* offsetEdit_ = nullptr; // m_offsetEdit: Decimal/hexadecimal file offset.
    QLabel* replacementLabel_ = nullptr; // m_replacementLabel: Replacement byte field title.
    QLineEdit* replacementEdit_ = nullptr; // m_replacementEdit: Hexadecimal replacement content.
    QCheckBox* backupCheckBox_ = nullptr; // m_backupCheckBox: Whether to retain timestamp backups.
    QCheckBox* riskCheckBox_ = nullptr; // m_riskCheckBox: Risk verification before final confirmation.
    QPushButton* applyPatchButton_ = nullptr; // m_applyPatchButton: Execute secure write.

    std::shared_ptr<ks::scanner::BinaryScanResult> lastResult_; // m_lastResult: The most recent result for repainting during language switching.
    QString statusKey_; // m_statusKey: Language pack key for the current status.
    QString statusFallback_; // m_statusFallback: Chinese text used when language packs are missing.
    QStringList statusArguments_; // m_statusArguments: Placeholders in the status text replaced in order.
    std::atomic<std::uint64_t> scanGeneration_{ 0 }; // m_scanGeneration: Evict expired scan callbacks.
    std::atomic<std::uint64_t> patchGeneration_{ 0 }; // m_patchGeneration: Discards expired write callbacks.
    std::shared_ptr<ScannerAsyncState> asyncState_; // m_asyncState: Protects the owner's lifetime during cross-thread dispatch.
    bool scanBusy_ = false; // m_scanBusy: Indicates whether the scan task is running.
    bool patchBusy_ = false; // m_patchBusy: Whether the atomic write task is running.
};
