#pragma once

// ============================================================
// core/MonitorConfig.h
// Purpose:
// 1) Define the session configuration structure used by the Agent at runtime.
// 2) Responsible for reading monitoring parameters from Temp\KswordApiMon\config_<pid>.ini;
// 3) Provide a stop marker file for background threads to poll for exit.
// ============================================================

#include "pch.h"
#include "../WinApiMonitorProtocol.h"

namespace apimon
{
    enum class FakeSuccessReturnType : std::uint32_t
    {
        kScalar = 0,
        kBool = 1,
        kHandle = 2,
        kDword = 3,
        kNtStatus = 4,
        kHResult = 5,
        kLStatus = 6,
        kSocketInt = 7
    };

    enum class FakeSuccessLastErrorKind : std::uint32_t
    {
        kNone = 0,
        kWin32 = 1,
        kWsa = 2
    };

    struct FakeSuccessRule
    {
        std::wstring moduleName;                                    // moduleName: The module name for rule matching; the matching layer can normalize names with or without .dll.
        std::wstring apiName;                                       // apiName: exported API name for rule matching, case-insensitive.
        FakeSuccessReturnType returnType = FakeSuccessReturnType::kScalar; // returnType: Return semantics after UI template selection.
        std::uint64_t returnValue = 0;                              // returnValue: Scalar return value written to RAX.
        FakeSuccessLastErrorKind lastErrorKind = FakeSuccessLastErrorKind::kNone; // lastErrorKind: Whether to set Win32/WSA error codes.
        std::uint32_t lastErrorValue = 0;                           // lastErrorValue: Value from SetLastError/WSASetLastError.
    };

    // MonitorConfig：
    // - Purpose: Store the API monitoring configuration for the current target process.
    // - Fields: Override named pipe name, stop marker path, enable/disable flags for each category, and maximum detail length.
    struct MonitorConfig
    {
        std::uint32_t targetPid = 0;            // targetPid: PID of the currently injected process.
        std::wstring configPath;                // configPath: Full path to the INI configuration file.
        std::wstring pipeName;                  // pipeName: Named pipe name.
        std::wstring stopFlagPath;              // stopFlagPath: Path to the stop flag file.
        std::wstring sessionId;                 // sessionId: a unique session ID generated by the UI for each startup, used to capture transient stop/start configuration switches.
        std::wstring agentDllPath;              // agentDllPath: path of the current APIMonitor_x64.dll, for automatic injection reuse by child processes.
        bool enableFile = true;                 // enableFile: Whether to enable file API hooking.
        bool enableRegistry = true;             // enableRegistry: Whether to enable Registry API Hooking.
        bool enableNetwork = true;              // enableNetwork: Whether to enable network API Hook.
        bool enableProcess = true;              // enableProcess: Whether to enable process API hooking.
        bool enableLoader = true;               // enableLoader: Whether to enable loader API Hook.
        bool autoInjectChild = false;           // autoInjectChild: Whether to automatically inject into new child processes after CreateProcessW succeeds.
        bool enableRawFallback = false;         // enableRawFallback: Whether to install a Raw ABI fallback hook for exports outside the strongly typed table.
        bool rawUseDefaultDenyList = true;      // rawUseDefaultDenyList: Whether to enable the built-in high-frequency/high-risk API deny list.
        std::vector<std::wstring> rawModuleList;// rawModuleList: Module name directory for Raw fallback scanning.
        std::vector<std::wstring> rawDenyList;  // rawDenyList: user-provided additional Raw Hook blacklist; the default blacklist is controlled separately by rawUseDefaultDenyList.
        bool fakeSuccessEnabled = false;        // fakeSuccessEnabled: Whether to enable the Fake Success rule to skip the original function for matched APIs.
        bool fakeSuccessRawFallback = false;    // fakeSuccessRawFallback: Whether to allow non-strongly-typed API overrides to use the generic RAX fake-return stub.
        std::vector<FakeSuccessRule> fakeSuccessRules; // fakeSuccessRules: Pseudo-return rules matching exactly by module!api.
        std::wstring fakeSuccessRulesText;      // fakeSuccessRulesText: original rule text used for automatic injection into child process inheritance.
        std::size_t detailLimitChars = 256;     // detailLimitChars: Truncation length for detail text.
        bool valid = false;                     // valid: Whether the current configuration passes basic validation.
    };

    bool loadMonitorConfigForCurrentProcess(MonitorConfig* configOut, std::wstring* errorTextOut);
    bool isStopFlagPresent(const MonitorConfig& configValue);
}
