#pragma once

// ============================================================
// WinAPIDock.h
// Purpose:
// 1) Provide the standalone 'WinAPI' Dock page;
// 2) Responsible for selecting the target process, configuring the Agent DLL path, and starting API monitoring;
// 3) Receive API events returned by the APIMonitor_x64 DLL via named pipes.
// ============================================================

#include "../Framework.h"
#include "WinApiMonitorProtocol.h"

#include <QString>  // QString: Event text, style text, and session path cache.
#include <QWidget>  // QWidget: Direct base class of WinAPIDock.

#include <atomic>   // std::atomic_bool/std::atomic_uintptr_t: controls session thread and pipe handle states.
#include <cstddef>  // std::size_t: Capacity of the event queue to be displayed and the refresh batch size.
#include <cstdint>  // std::uint32_t/std::uintptr_t: Bridges PID and handle values.
#include <deque>    // std::deque: Bounded FIFO queue for high-frequency events.
#include <memory>   // std::unique_ptr: manages the background thread object.
#include <mutex>    // std::mutex: Protect pending event queue for flushing.
#include <thread>   // std::thread: Process refresh and named pipe read thread.
#include <vector>   // std::vector: stores process snapshots and pending refresh event cache.

class QCheckBox;
class QComboBox;
class QLineEdit;
class QLabel;
class QPlainTextEdit;
class QPushButton;
class QSplitter;
class QTableWidget;
class QTableWidgetItem;
class QTimer;
class QToolButton;
class QVBoxLayout;
class QWidget;
class QPoint;

class WinAPIDock final : public QWidget
{
public:
    // Constructor:
    // - Purpose: initialize the WinAPI monitoring page UI, connections, and background refresh timer.
    // - Parameter parent: Qt parent widget.
    explicit WinAPIDock(QWidget* parent = nullptr);

    // Destructor:
    // - Purpose: Stop the named pipe thread to ensure no background callbacks access members after object destruction.
    ~WinAPIDock() override;

    // notifyPageActivated：
    // - Purpose: Trigger lightweight activation logic when the tab actually switches to the WinAPI page.
    // - Call: Invoked when MonitorDock switches to the WinAPI sub-page to refresh process snapshots on demand.
    void notifyPageActivated();

public:
    // EventColumn：
    // - Purpose: Define the column index for the API event table.
    // - Call: Access columns uniformly when inserting events, exporting, or handling right-click menus.
    enum EventColumn
    {
        kEventColumnTime100ns = 0,
        kEventColumnCategory,
        kEventColumnApi,
        kEventColumnResult,
        kEventColumnPidTid,
        kEventColumnDetail,
        kEventColumnCount
    };

    // FakeRuleColumn:
    // - Purpose: keep the Fake Success rule table column indexes stable across UI, validation, and INI serialization.
    // - Use: add/remove/serialize code reads table cells by these constants rather than repeating numeric indexes.
    enum FakeRuleColumn
    {
        kFakeRuleColumnModule = 0,
        kFakeRuleColumnApi,
        kFakeRuleColumnReturnType,
        kFakeRuleColumnReturnValue,
        kFakeRuleColumnLastErrorKind,
        kFakeRuleColumnLastErrorValue,
        kFakeRuleColumnCount
    };

    // EventRow：
    // - Purpose: Cache one row of API events pending UI flush.
    // - internalEvent: whether this is an internal state event generated by the UI or Agent.
    struct EventRow
    {
        QString time100nsText;
        QString categoryText;
        QString apiText;
        QString resultText;
        QString pidTidText;
        QString detailText;
        bool internalEvent = false;
    };

private:
    void initializeUi();
    void initializeConnections();
    void updateActionState();
    void updateStatusLabel();

    void refreshProcessListAsync();
    void populateProcessSelector(const std::vector<ks::process::ProcessRecord>& processList);
    void updateProcessSelectorStatus();
    bool currentSelectedPid(std::uint32_t* pidOut) const;
    void browseAgentDllPath();

    void startMonitoring();
    void stopMonitoring();
    void stopMonitoringInternal(bool waitForThread);
    void terminateHooksForSelectedProcess();
    bool prepareSessionArtifacts(std::uint32_t pidValue, QString* errorTextOut);
    bool writeSessionConfigFile(QString* errorTextOut) const;

    // hasResidentAgentForProcess：
    // - Purpose: Confirm whether the same process instance can reuse the loaded Agent based on PID and creation time.
    // - Returns: true if reusable; clears the cache if the identity does not match.
    bool hasResidentAgentForProcess(std::uint32_t pidValue);

    // rememberResidentAgentForProcess：
    // - Purpose: Record the target process identity after a successful injection to avoid repeated LoadLibraryW calls in subsequent sessions within the same Dock.
    void rememberResidentAgentForProcess(std::uint32_t pidValue);
    void appendInternalEvent(const QString& categoryText, const QString& apiText, const QString& detailText);
    QString fakeSuccessRulesIniText() const;
    bool validateFakeSuccessRules(QString* errorTextOut) const;
    void addFakeSuccessRuleFromInputs();
    void removeSelectedFakeSuccessRule();

    void startPipeReadThread();
    void startChildPipeReadThread(std::uint32_t childPidValue);
    void closeChildPipeHandles();
    void joinChildPipeThreads();
    void writeChildStopFlags();
    void enqueuePendingRow(EventRow rowValue);
    void flushPendingRows();
    void appendEventRow(const EventRow& rowValue);

    void applyEventFilter();
    void clearEventFilter();
    void exportVisibleRowsToTsv();
    void showEventContextMenu(const QPoint& position);
    void showEventDetailDialog(int rowValue);

    static QString blueButtonStyle();
    static QString blueInputStyle();
    static QString blueHeaderStyle();
    static QString eventCategoryText(std::uint32_t categoryValue);
    static QString defaultDllPathHint();
    static QString defaultRawHookModulesText();
    static QString defaultRawHookDenyListText();
    static QString resultCodeText(std::int32_t resultCodeValue);
    static QString now100nsText();
    static bool tryParseUint32Text(const QString& textValue, std::uint32_t* valueOut);
    static QTableWidgetItem* createReadOnlyItem(const QString& textValue);

private:
    QVBoxLayout* rootLayout_ = nullptr;               // m_rootLayout: Root layout.
    QToolButton* sessionCollapseButton_ = nullptr;    // m_sessionCollapseButton: The sole configuration button for collapsing the header, unifying the target process, Agent, and Fake Success.
    QWidget* sessionCollapseContent_ = nullptr;       // m_sessionCollapseContent: The single collapsible content area, with process selection at the top and left/right configurations at the bottom.
    QSplitter* topSplitter_ = nullptr;                // m_topSplitter: Left-right splitter for Agent session and Fake Success.
    QWidget* processPanel_ = nullptr;                 // m_processPanel: Top process drop-down selection panel.
    QWidget* sessionPanel_ = nullptr;                 // m_sessionPanel: Left-side WinAPI Agent session configuration panel.
    QWidget* filterPanel_ = nullptr;                  // m_filterPanel: Bottom event filter panel.

    QLabel* processIconLabel_ = nullptr;              // m_processIconLabel: Displays the system icon for the current candidate/selected process.
    QComboBox* processCombo_ = nullptr;               // m_processCombo: Editable process dropdown; user enters a process name or PID to select from candidates.
    QPushButton* processRefreshButton_ = nullptr;     // m_processRefreshButton: Button to refresh the process list.
    QLabel* processStatusLabel_ = nullptr;            // m_processStatusLabel: Status text for process dropdown box matching/selection.

    QLineEdit* manualPidEdit_ = nullptr;              // m_manualPidEdit: Advanced fallback text box for manually entering a PID.
    QLineEdit* agentDllPathEdit_ = nullptr;           // m_agentDllPathEdit: Text box for the Agent DLL path.
    QPushButton* browseAgentDllButton_ = nullptr;     // m_browseAgentDllButton: Browse DLL button.
    QCheckBox* hookFileCheck_ = nullptr;              // m_hookFileCheck: Enable file API monitoring.
    QCheckBox* hookRegistryCheck_ = nullptr;          // m_hookRegistryCheck: Whether to enable registry API monitoring.
    QCheckBox* hookNetworkCheck_ = nullptr;           // m_hookNetworkCheck: Enable network API monitoring.
    QCheckBox* hookProcessCheck_ = nullptr;           // m_hookProcessCheck: Whether to enable process API monitoring.
    QCheckBox* hookLoaderCheck_ = nullptr;            // m_hookLoaderCheck: Enable loader API monitoring.
    QCheckBox* autoInjectChildCheck_ = nullptr;       // m_autoInjectChildCheck: whether to automatically inject child processes after CreateProcessW succeeds.
    QCheckBox* rawFallbackCheck_ = nullptr;           // m_rawFallbackCheck: Whether to enable the fallback hook for untyped exported Raw ABI.
    QCheckBox* rawDefaultDenyListCheck_ = nullptr;    // m_rawDefaultDenyListCheck: Whether to enable the default high-frequency/high-risk Raw deny list.
    QPlainTextEdit* rawModuleListEdit_ = nullptr;     // m_rawModuleListEdit: Raw fallback module list scan, multi-line editor.
    QPlainTextEdit* rawDenyListEdit_ = nullptr;       // m_rawDenyListEdit: User-provided additional Raw deny list; multi-line editor, independent of the built-in default deny list.
    QLineEdit* fakeModuleEdit_ = nullptr;             // m_fakeModuleEdit: Fake Success module name exact match.
    QLineEdit* fakeApiEdit_ = nullptr;                // m_fakeApiEdit: Exact match for exported API names in Fake Success.
    QComboBox* fakeReturnTypeCombo_ = nullptr;        // m_fakeReturnTypeCombo: Fake Success return value template.
    QLineEdit* fakeReturnValueEdit_ = nullptr;        // m_fakeReturnValueEdit: Return value written to RAX for Fake Success.
    QComboBox* fakeLastErrorKindCombo_ = nullptr;     // m_fakeLastErrorKindCombo: Whether Fake Success sets LastError/WSAError.
    QLineEdit* fakeLastErrorValueEdit_ = nullptr;     // m_fakeLastErrorValueEdit: Fake Success error code value.
    QCheckBox* fakeRawFallbackCheck_ = nullptr;       // m_fakeRawFallbackCheck: Whether to allow Fake Success to use Raw scalar return stubs for untyped APIs.
    QPushButton* fakeAddRuleButton_ = nullptr;        // m_fakeAddRuleButton: Apply input area content to the rule table.
    QPushButton* fakeRemoveRuleButton_ = nullptr;     // m_fakeRemoveRuleButton: Delete the currently selected row in the rule table.
    QPushButton* fakeApplyRuleButton_ = nullptr;      // m_fakeApplyRuleButton: Starts and applies a Fake Success session based on the current rule table.
    QPushButton* fakeStopRuleButton_ = nullptr;       // m_fakeStopRuleButton: Stops the current Fake Success/WinAPI Agent session.
    QLabel* fakeRuleStatusLabel_ = nullptr;           // m_fakeRuleStatusLabel: Fake Success rule count/limit description.
    QTableWidget* fakeRuleTable_ = nullptr;           // m_fakeRuleTable: Fake Success precise rule table.
    QPushButton* startButton_ = nullptr;              // m_startButton: Start WinAPI monitoring button.
    QPushButton* stopButton_ = nullptr;               // m_stopButton: Stop WinAPI monitoring button.
    QPushButton* terminateHookButton_ = nullptr;      // m_terminateHookButton: Button to manually terminate the target process's hooks.
    QPushButton* exportButton_ = nullptr;             // m_exportButton: Button to export currently visible events.
    QPushButton* clearEventButton_ = nullptr;         // m_clearEventButton: Clear events table button.
    QLabel* sessionStatusLabel_ = nullptr;            // m_sessionStatusLabel: Session status text.

    QLineEdit* eventFilterEdit_ = nullptr;            // m_eventFilterEdit: Full-field event filter input.
    QPushButton* eventFilterClearButton_ = nullptr;   // m_eventFilterClearButton: Clear event filter button.
    QCheckBox* eventKeepBottomCheck_ = nullptr;       // m_eventKeepBottomCheck: Whether to automatically scroll to the bottom.
    QLabel* eventFilterStatusLabel_ = nullptr;        // m_eventFilterStatusLabel: Filter result status text.
    QTableWidget* eventTable_ = nullptr;              // m_eventTable: API event results table.

    std::vector<ks::process::ProcessRecord> processList_; // m_processList: Current system process snapshot.
    static constexpr std::size_t kPendingRowCapacity = 24000; // Background queue upper limit; drop oldest events when backlog occurs to protect memory and latency.
    static constexpr std::size_t kUiFlushRowLimit = 160;      // Maximum number of events rendered per GUI tick.
    static constexpr int kUiFlushBudgetMs = 4;                // Rendering time budget per GUI tick.
    static constexpr std::uint32_t kPipeReconnectLimit = 3;  // The number of transient disconnections the read end can tolerate during old session switching, to prevent the UI from giving up reading before the new Agent establishes the pipe.

    std::deque<EventRow> pendingRows_;                    // m_pendingRows: Bounded FIFO event queue pending flush by the background thread.
    std::mutex pendingMutex_;                             // m_pendingMutex: Protects the pending event queue for flushing.
    std::size_t pendingDroppedRows_ = 0;                   // m_pendingDroppedRows: Number of events dropped due to queue or rendering budget.
    std::unique_ptr<std::thread> pipeThread_;             // m_pipeThread: Named pipe reader thread.
    std::vector<std::unique_ptr<std::thread>> childPipeThreads_; // m_childPipeThreads: Child pipe reader threads after automatic injection into child processes.
    std::vector<std::uintptr_t> childPipeHandleValues_;   // m_childPipeHandleValues: Snapshot of child pipe handles, used to interrupt blocking ReadFile calls during shutdown.
    std::vector<std::uint32_t> childSessionPids_;          // m_childSessionPids: Automatically injected child process PIDs discovered, used for writing stop markers.
    std::mutex childPipeMutex_;                           // m_childPipeMutex: Protects child pipe threads/handles/PID containers.
    std::atomic_bool processRefreshPending_{ false };     // m_processRefreshPending: Whether process refresh is in progress.
    std::atomic_bool pipeRunning_{ false };               // m_pipeRunning: Whether the current monitoring session is running.
    std::atomic_bool pipeConnected_{ false };             // m_pipeConnected: Whether the Agent pipe connection was successfully established.
    std::atomic_bool pipeStopFlag_{ false };              // m_pipeStopFlag: Pipe thread stop signal.
    std::atomic_uintptr_t pipeHandleValue_{ 0 };          // m_pipeHandleValue: Pipe handle value held by the background thread.
    std::atomic_uint32_t pipeReconnectAttempts_{ 0 };     // m_pipeReconnectAttempts: Number of read-end transient disconnection reconnection attempts used in the current session.
    QTimer* uiFlushTimer_ = nullptr;                      // m_uiFlushTimer: Timer for batch refreshing the event table.
    int sessionProgressPid_ = 0;                          // m_sessionProgressPid: kPro task card ID.
    std::uint32_t currentSessionPid_ = 0;                 // m_currentSessionPid: Target PID currently under monitoring.
    std::uint32_t residentAgentPid_ = 0;                  // m_residentAgentPid: PID of the successfully injected Agent that may still be resident.
    std::uint64_t residentAgentCreationTime100ns_ = 0;    // m_residentAgentCreationTime100ns: Creation time of the process instance for the resident Agent, used to prevent PID reuse.
    QString currentPipeName_;                             // m_currentPipeName: current named pipe name.
    QString currentConfigPath_;                           // m_currentConfigPath: current session configuration file path.
    QString currentStopFlagPath_;                         // m_currentStopFlagPath: Path to the current stop flag file.
    QString currentSessionId_;                            // m_currentSessionId: Unique identifier for each startup, preventing missed stop markers when stop/start cycles occur too rapidly.
    qint64 lastProcessRefreshMs_ = 0;                     // m_lastProcessRefreshMs: timestamp of the last completed process snapshot (ms).
    bool eventFilterActive_ = false;                      // m_eventFilterActive: Whether to perform full-table filtering when an event arrives.
    bool hasActivatedOnce_ = false;                       // m_hasActivatedOnce: Whether the page has been activated at least once.
};
