#include "cpu_power_runtime.h"

#include <intrin.h>

// ============================================================
// cpu_power_runtime.c
// Purpose:
// - Provides structured read/write only for whitelisted Intel power management MSRs.
// - All MSR accesses are executed on the target logical processor and protected by SEH.
// - Caller is not allowed to provide MSR number, mask, or arbitrary raw write values.
// ============================================================

// Fixed MSR numbers defined by Intel architecture and RAPL/HWP documentation.
#define KSW_CPU_POWER_MSR_PLATFORM_INFO       0x000000CEUL
#define KSW_CPU_POWER_MSR_PERF_STATUS         0x00000198UL
#define KSW_CPU_POWER_MSR_PERF_CONTROL        0x00000199UL
#define KSW_CPU_POWER_MSR_MISC_ENABLE         0x000001A0UL
#define KSW_CPU_POWER_MSR_TURBO_RATIO_LIMIT   0x000001ADUL
#define KSW_CPU_POWER_MSR_RAPL_POWER_UNIT     0x00000606UL
#define KSW_CPU_POWER_MSR_PACKAGE_POWER_LIMIT 0x00000610UL
#define KSW_CPU_POWER_MSR_PACKAGE_POWER_INFO  0x00000614UL
#define KSW_CPU_POWER_MSR_PM_ENABLE           0x00000770UL
#define KSW_CPU_POWER_MSR_HWP_CAPABILITIES    0x00000771UL
#define KSW_CPU_POWER_MSR_HWP_REQUEST         0x00000774UL

// Fixed mask and bit positions used for Intel MSR fields.
#define KSW_CPU_POWER_LIMIT_VALUE_MASK       0x0000000000007FFFULL
#define KSW_CPU_POWER_LIMIT_ENABLE_BIT       15UL
#define KSW_CPU_POWER_LIMIT_CLAMP_BIT        16UL
#define KSW_CPU_POWER_LIMIT_SECOND_SHIFT     32UL
#define KSW_CPU_POWER_LIMIT_SECOND_ENABLE    47UL
#define KSW_CPU_POWER_LIMIT_SECOND_CLAMP     48UL
#define KSW_CPU_POWER_LIMIT_LOCK_BIT         63UL
#define KSW_CPU_POWER_MISC_TURBO_DISABLE_BIT 38UL
#define KSW_CPU_POWER_PLATFORM_RATIO_BIT     28UL
#define KSW_CPU_POWER_PLATFORM_TDP_BIT       29UL
#define KSW_CPU_POWER_PERF_RATIO_SHIFT        8UL
#define KSW_CPU_POWER_PERF_RATIO_MASK         0x000000000000FF00ULL

// HWP and architecture capability bits used by CPUID.06H.
#define KSW_CPU_POWER_CPUID1_EIST_BIT  7UL
#define KSW_CPU_POWER_CPUID6_TURBO_BIT 1UL
#define KSW_CPU_POWER_CPUID6_HWP_BIT   7UL
#define KSW_CPU_POWER_CPUID6_EPP_BIT   10UL

// g_KswordCpuPowerLock: Serializes queries and modifications to prevent two UI requests from interleaving and overwriting the same MSR.
static EX_PUSH_LOCK gKswordCpuPowerLock;

// kswordArkCpuPowerReadMsr: Read a compile-time whitelisted MSR on the current logical processor.
static NTSTATUS
kswordArkCpuPowerReadMsr(
    _In_ ULONG msrIndex,
    _Out_ ULONGLONG* value
    )
{
    // Output pointer must be valid to avoid writing to a null address in an exception path.
    if (value == NULL) {
        return STATUS_INVALID_PARAMETER;
    }

    // Clear output first so callers do not see stale stack values on failure.
    *value = 0ULL;
    __try {
        // __readmsr accepts only whitelisted IDs passed from fixed call sites within this file.
        *value = __readmsr(msrIndex);
    }
    __except (EXCEPTION_EXECUTE_HANDLER) {
        // Preserve precise synchronous exception status when virtualization filtering applies or the model is unsupported.
        return GetExceptionCode();
    }

    // Return success after a complete 64-bit read.
    return STATUS_SUCCESS;
}

// kswordArkCpuPowerWriteMsr: Writes a compile-time whitelist MSR to the current logical processor.
static NTSTATUS
kswordArkCpuPowerWriteMsr(
    _In_ ULONG msrIndex,
    _In_ ULONGLONG value
    )
{
    __try {
        // The MsrIndex and final value for __writemsr are generated by this module based on fields.
        __writemsr(msrIndex, value);
    }
    __except (EXCEPTION_EXECUTE_HANDLER) {
        // Return synchronous exception status when locked, virtualization filtered, or model unsupported.
        return GetExceptionCode();
    }

    // Return success when the write instruction completes without an exception; the caller must still read back and verify the result.
    return STATUS_SUCCESS;
}

// kswordArkCpuPowerCopyCpuidText: copies CPUID register bytes into a fixed-protocol text buffer.
static VOID
kswordArkCpuPowerCopyCpuidText(
    _Out_writes_bytes_(destinationBytes) CHAR* destination,
    _In_ SIZE_T destinationBytes,
    _In_reads_bytes_(sourceBytes) const VOID* source,
    _In_ SIZE_T sourceBytes
    )
{
    // Do not access an empty buffer.
    if (destination == NULL || destinationBytes == 0U) {
        return;
    }

    // First zero out the entire destination to ensure a NUL terminator is always present.
    RtlZeroMemory(destination, destinationBytes);
    // Copy bytes up to the destination capacity minus one only if the source is valid.
    if (source != NULL && sourceBytes != 0U) {
        // copyBytes is explicitly limited before the target NUL.
        const SIZE_T kCopyBytes = min(sourceBytes, destinationBytes - 1U);
        // Copy raw CPUID ASCII bytes.
        RtlCopyMemory(destination, source, kCopyBytes);
    }
}

// kswordArkCpuPowerDecodeIdentity: decodes extended encoding for family/model/stepping.
static VOID
kswordArkCpuPowerDecodeIdentity(
    _In_ ULONG signature,
    _Out_ ULONG* familyArg,
    _Out_ ULONG* modelArg,
    _Out_ ULONG* stepping
    )
{
    // First extract the base fields, then extend them according to CPUID rules.
    ULONG family = (signature >> 8U) & 0x0FUL;
    // model retains the base four bits.
    ULONG model = (signature >> 4U) & 0x0FUL;
    // extendedFamily is accumulated only when the base family is 0xF.
    const ULONG kExtendedFamily = (signature >> 20U) & 0xFFUL;
    // extendedModel is concatenated to the high bits when family is 0x6 or 0xF.
    const ULONG kExtendedModel = (signature >> 16U) & 0x0FUL;
    // baseFamily preserves the pre-extension field for model determination.
    const ULONG kBaseFamily = family;

    // Family 0xF uses the extended field.
    if (family == 0x0FUL) {
        family += kExtendedFamily;
    }
    // Family 0x6 or base family 0xF uses an extended model.
    if (kBaseFamily == 0x06UL || kBaseFamily == 0x0FUL) {
        model |= kExtendedModel << 4U;
    }

    // Publish decoding results item by item.
    *familyArg = family;
    *modelArg = model;
    *stepping = signature & 0x0FUL;
}

// kswordArkCpuPowerRawPowerToMilliwatts: Decode the 15-bit power value according to RAPL power units.
static ULONG
kswordArkCpuPowerRawPowerToMilliwatts(
    _In_ ULONGLONG rawPower,
    _In_ ULONG powerUnitMicrowatts
    )
{
    // 0 indicates RAPL unit read failure; forged power consumption cannot be generated.
    if (powerUnitMicrowatts == 0UL) {
        return 0UL;
    }

    // Use 64-bit integers and round to mW to avoid kernel floating-point arithmetic.
    return (ULONG)(((rawPower & KSW_CPU_POWER_LIMIT_VALUE_MASK) *
        (ULONGLONG)powerUnitMicrowatts + 500ULL) / 1000ULL);
}

// kswordArkCpuPowerDecodeTimeWindowMilliseconds: decodes RAPL Y/Z time windows.
static ULONG
kswordArkCpuPowerDecodeTimeWindowMilliseconds(
    _In_ ULONG encodedWindow,
    _In_ ULONG timeUnitNanoseconds
    )
{
    // Y is in the lower 5 bits; Z is in the upper 2 bits.
    const ULONG kY = encodedWindow & 0x1FUL;
    // Z represents the multiplier of 1 + Z/4.
    const ULONG kZ = (encodedWindow >> 5U) & 0x03UL;
    // Perform multiplication in 64-bit and divide by four first to reduce overflow probability.
    ULONGLONG nanoseconds = (ULONGLONG)timeUnitNanoseconds *
        (ULONGLONG)(4UL + kZ);

    // Saturate to the ULONG millisecond limit before left-shifting a large Y value.
    if (kY >= 31UL || nanoseconds > (MAXULONGLONG >> kY)) {
        return MAXULONG;
    }
    // After applying 2^Y, the rate becomes one-quarter of Z.
    nanoseconds = (nanoseconds << kY) / 4ULL;
    // Convert to milliseconds and saturate at ULONG max.
    if (nanoseconds / 1000000ULL > MAXULONG) {
        return MAXULONG;
    }
    // Return integer milliseconds.
    return (ULONG)(nanoseconds / 1000000ULL);
}

// kswordArkCpuPowerCaptureCpuid: Fills in vendor, brand, identity, and architecture capabilities.
static VOID
kswordArkCpuPowerCaptureCpuid(
    _Inout_ KSWORD_ARK_CPU_POWER_RESPONSE* response,
    _Out_ BOOLEAN* perfControlSupported,
    _Out_ BOOLEAN* turboSupported,
    _Out_ BOOLEAN* hwpSupported,
    _Out_ BOOLEAN* hwpEppSupported
    )
{
    // CPUID register buffer uses four ints as specified by MSVC intrinsics.
    int registers[4] = { 0, 0, 0, 0 };
    // vendorBytes: Concatenates the 12-byte vendor ID in EBX/EDX/ECX order.
    CHAR vendorBytes[12] = { 0 };
    // brandBytes: Stores the 48-byte brand string from three extended leaves.
    CHAR brandBytes[48] = { 0 };
    // Maximum basic leaf determines whether leaf 1 and leaf 6 are accessible.
    ULONG maximumBasicLeaf = 0UL;
    // The maximum extended leaf determines whether a brand string exists.
    ULONG maximumExtendedLeaf = 0UL;

    // initialize capability output to prevent stale values from passing through the no-capability path.
    *perfControlSupported = FALSE;
    *turboSupported = FALSE;
    *hwpSupported = FALSE;
    *hwpEppSupported = FALSE;

    // Leaf 0 returns the maximum leaf and the vendor string.
    __cpuidex(registers, 0, 0);
    // Save maximum basic leaf.
    maximumBasicLeaf = (ULONG)registers[0];
    // Copy the vendor ID in architectural order.
    RtlCopyMemory(vendorBytes + 0, &registers[1], sizeof(registers[1]));
    RtlCopyMemory(vendorBytes + 4, &registers[3], sizeof(registers[3]));
    RtlCopyMemory(vendorBytes + 8, &registers[2], sizeof(registers[2]));
    // Publish fixed NUL-terminated vendor text.
    kswordArkCpuPowerCopyCpuidText(
        response->vendorId,
        sizeof(response->vendorId),
        vendorBytes,
        sizeof(vendorBytes));

    // Precisely identify Intel and AMD; other vendors remain Unknown.
    if (RtlCompareMemory(vendorBytes, "GenuineIntel", sizeof(vendorBytes)) ==
        sizeof(vendorBytes)) {
        response->vendor = KSWORD_ARK_CPU_POWER_VENDOR_INTEL;
    }
    else if (RtlCompareMemory(vendorBytes, "AuthenticAMD", sizeof(vendorBytes)) ==
        sizeof(vendorBytes)) {
        response->vendor = KSWORD_ARK_CPU_POWER_VENDOR_AMD;
    }

    // Leaf 1 provides the signature and the hypervisor-present bit.
    if (maximumBasicLeaf >= 1UL) {
        // Read processor signature and general features.
        __cpuidex(registers, 1, 0);
        // Decode family/model/stepping.
        kswordArkCpuPowerDecodeIdentity(
            (ULONG)registers[0],
            &response->family,
            &response->model,
            &response->stepping);
        // ECX[7] indicates Enhanced Intel SpeedStep and declares the IA32_PERF_CTL path.
        *perfControlSupported = ((((ULONG)registers[2]) &
            (1UL << KSW_CPU_POWER_CPUID1_EIST_BIT)) != 0UL) ? TRUE : FALSE;
        // ECX[31] indicates that a hypervisor is present in the current environment.
        if ((((ULONG)registers[2]) & (1UL << 31U)) != 0UL) {
            response->responseFlags |=
                KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_HYPERVISOR_PRESENT;
        }
    }

    // Leaf 6 provides Turbo, HWP, and HWP EPP architectural capabilities.
    if (maximumBasicLeaf >= 6UL) {
        // Note: Reads the thermal/power management feature leaf.
        __cpuidex(registers, 6, 0);
        // EAX[1] indicates Intel Turbo Boost Technology.
        *turboSupported = ((((ULONG)registers[0]) &
            (1UL << KSW_CPU_POWER_CPUID6_TURBO_BIT)) != 0UL) ? TRUE : FALSE;
        // EAX[7] indicates Hardware-Controlled Performance States.
        *hwpSupported = ((((ULONG)registers[0]) &
            (1UL << KSW_CPU_POWER_CPUID6_HWP_BIT)) != 0UL) ? TRUE : FALSE;
        // EAX[10] indicates HWP Energy Performance Preference.
        *hwpEppSupported = ((((ULONG)registers[0]) &
            (1UL << KSW_CPU_POWER_CPUID6_EPP_BIT)) != 0UL) ? TRUE : FALSE;
    }

    // Extended leaf 0x80000000 returns the maximum brand leaf.
    __cpuidex(registers, (int)0x80000000UL, 0);
    // Save maximum extended leaf.
    maximumExtendedLeaf = (ULONG)registers[0];
    // All three brand leaves must exist to copy the complete 48 bytes.
    if (maximumExtendedLeaf >= 0x80000004UL) {
        // Write to the fixed brand buffer leaf by leaf.
        for (ULONG leafOffset = 0UL; leafOffset < 3UL; ++leafOffset) {
            // Read the current 16-byte brand fragment.
            __cpuidex(registers, (int)(0x80000002UL + leafOffset), 0);
            // Copy four registers to the corresponding offset.
            RtlCopyMemory(
                brandBytes + (leafOffset * sizeof(registers)),
                registers,
                sizeof(registers));
        }
        // Publish fixed NUL-terminated brand text.
        kswordArkCpuPowerCopyCpuidText(
            response->brandText,
            sizeof(response->brandText),
            brandBytes,
            sizeof(brandBytes));
    }

    // Mark that the CPUID-based identity is available.
    response->fieldFlags |= KSWORD_ARK_CPU_POWER_FIELD_CPUID;
}

// kswordArkCpuPowerDecodeSnapshot: decodes raw MSR data already read into stable protocol fields.
static VOID
kswordArkCpuPowerDecodeSnapshot(
    _Inout_ KSWORD_ARK_CPU_POWER_RESPONSE* response
    )
{
    // Decode power/time unit when RAPL unit is present.
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_RAPL_UNIT) != 0UL) {
        // powerExponent is located in MSR[3:0].
        const ULONG kPowerExponent = (ULONG)(response->msrRaplPowerUnit & 0x0FULL);
        // timeExponent is located in MSR[19:16].
        const ULONG kTimeExponent =
            (ULONG)((response->msrRaplPowerUnit >> 16U) & 0x0FULL);
        // powerDenominator is 2 raised to the power of the exponent.
        const ULONGLONG kPowerDenominator = 1ULL << kPowerExponent;
        // timeDenominator is 2 raised to the power of timeExponent.
        const ULONGLONG kTimeDenominator = 1ULL << kTimeExponent;
        // Use rounded integer units, with a minimum of 1 microwatt.
        response->powerUnitMicrowatts = (ULONG)max(
            1ULL,
            (1000000ULL + (kPowerDenominator / 2ULL)) / kPowerDenominator);
        // Time units are also expressed as integer nanoseconds.
        response->timeUnitNanoseconds = (ULONG)max(
            1ULL,
            (1000000000ULL + (kTimeDenominator / 2ULL)) / kTimeDenominator);
    }

    // Decodes current PL1/PL2 and enable/clamp/lock bits.
    if ((response->fieldFlags &
        KSWORD_ARK_CPU_POWER_FIELD_PACKAGE_POWER_LIMIT) != 0UL) {
        // PL1 uses the lower 15 bits.
        response->pl1Milliwatts = kswordArkCpuPowerRawPowerToMilliwatts(
            response->msrPackagePowerLimit,
            response->powerUnitMicrowatts);
        // PL2 uses bits 46:32.
        response->pl2Milliwatts = kswordArkCpuPowerRawPowerToMilliwatts(
            response->msrPackagePowerLimit >> KSW_CPU_POWER_LIMIT_SECOND_SHIFT,
            response->powerUnitMicrowatts);
        // Publish enable and clamp states separately.
        response->pl1Enabled =
            (ULONG)((response->msrPackagePowerLimit >>
                KSW_CPU_POWER_LIMIT_ENABLE_BIT) & 1ULL);
        response->pl1ClampEnabled =
            (ULONG)((response->msrPackagePowerLimit >>
                KSW_CPU_POWER_LIMIT_CLAMP_BIT) & 1ULL);
        response->pl2Enabled =
            (ULONG)((response->msrPackagePowerLimit >>
                KSW_CPU_POWER_LIMIT_SECOND_ENABLE) & 1ULL);
        response->pl2ClampEnabled =
            (ULONG)((response->msrPackagePowerLimit >>
                KSW_CPU_POWER_LIMIT_SECOND_CLAMP) & 1ULL);
        // Once bit 63 is locked, the state can only be re-established by reset or firmware.
        if (((response->msrPackagePowerLimit >>
            KSW_CPU_POWER_LIMIT_LOCK_BIT) & 1ULL) != 0ULL) {
            response->responseFlags |=
                KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_POWER_LIMIT_LOCKED;
        }
    }

    // Decode SKU TDP, minimum/maximum power consumption, and maximum time window.
    if ((response->fieldFlags &
        KSWORD_ARK_CPU_POWER_FIELD_PACKAGE_POWER_INFO) != 0UL) {
        // Bits 14:0 represent the Thermal Spec Power.
        response->packageTdpMilliwatts = kswordArkCpuPowerRawPowerToMilliwatts(
            response->msrPackagePowerInfo,
            response->powerUnitMicrowatts);
        // Bits 30:16 represent Minimum Power.
        response->packageMinimumPowerMilliwatts =
            kswordArkCpuPowerRawPowerToMilliwatts(
                response->msrPackagePowerInfo >> 16U,
                response->powerUnitMicrowatts);
        // Bits 46:32 represent Maximum Power.
        response->packageMaximumPowerMilliwatts =
            kswordArkCpuPowerRawPowerToMilliwatts(
                response->msrPackagePowerInfo >> 32U,
                response->powerUnitMicrowatts);
        // Bits 54:48 use the same Y/Z time encoding.
        response->packageMaximumTimeWindowMilliseconds =
            kswordArkCpuPowerDecodeTimeWindowMilliseconds(
                (ULONG)((response->msrPackagePowerInfo >> 48U) & 0x7FULL),
                response->timeUnitNanoseconds);
        // Some SKUs return 0 for maximum power; the UI must display 'Platform maximum unknown'.
        if (response->packageMaximumPowerMilliwatts == 0UL) {
            response->responseFlags |=
                KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_PLATFORM_MAX_UNKNOWN;
        }
    }

    // Decode platform ratio information and programmability hints.
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_PLATFORM_INFO) != 0UL) {
        // The maximum non-Turbo ratio is located at bits 15:8.
        response->maximumNonTurboRatio =
            (ULONG)((response->msrPlatformInfo >> 8U) & 0xFFULL);
        // Maximum efficiency ratio is located at bits 47:40.
        response->maximumEfficiencyRatio =
            (ULONG)((response->msrPlatformInfo >> 40U) & 0xFFULL);
        // Bit 28 indicates that the Turbo Ratio Limit is programmable.
        if (((response->msrPlatformInfo >>
            KSW_CPU_POWER_PLATFORM_RATIO_BIT) & 1ULL) != 0ULL) {
            response->capabilityFlags |=
                KSWORD_ARK_CPU_POWER_CAP_TURBO_RATIO_PROGRAMMABLE;
        }
        // Bit 29 serves as additional evidence for platform-programmable TDP.
        if (((response->msrPlatformInfo >>
            KSW_CPU_POWER_PLATFORM_TDP_BIT) & 1ULL) != 0ULL) {
            response->capabilityFlags |=
                KSWORD_ARK_CPU_POWER_CAP_PACKAGE_POWER_PROGRAMMABLE;
        }
    }

    // Any readable and unlocked package limit allows structured PL1/PL2 modification.
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_PACKAGE_POWER_LIMIT) != 0UL &&
        (response->responseFlags &
            KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_POWER_LIMIT_LOCKED) == 0UL) {
        response->capabilityFlags |=
            KSWORD_ARK_CPU_POWER_CAP_PACKAGE_POWER_PROGRAMMABLE;
    }

    // When IA32_MISC_ENABLE[38] is 1, Turbo is disabled.
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_MISC_ENABLE) != 0UL) {
        response->turboEnabled =
            ((response->msrMiscEnable >> KSW_CPU_POWER_MISC_TURBO_DISABLE_BIT) &
                1ULL) == 0ULL ? 1UL : 0UL;
        response->capabilityFlags |= KSWORD_ARK_CPU_POWER_CAP_TURBO_CONTROL;
    }

    // IA32_PERF_CTL[15:8] is the software-requested multiplier; IA32_PERF_STATUS[15:8] is the current multiplier feedback.
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_PERF_CONTROL) != 0UL) {
        response->requestedMultiplier =
            (ULONG)((response->msrPerfControl >>
                KSW_CPU_POWER_PERF_RATIO_SHIFT) & 0xFFULL);
    }
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_PERF_STATUS) != 0UL) {
        response->currentMultiplier =
            (ULONG)((response->msrPerfStatus >>
                KSW_CPU_POWER_PERF_RATIO_SHIFT) & 0xFFULL);
    }

    // IA32_PM_ENABLE[0] indicates that HWP has been enabled by firmware or the operating system.
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_PM_ENABLE) != 0UL &&
        (response->msrPmEnable & 1ULL) != 0ULL) {
        response->capabilityFlags |= KSWORD_ARK_CPU_POWER_CAP_HWP_ENABLED;
    }

    // Decode the four performance bytes of HWP capability in architectural order.
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_HWP_CAPABILITIES) != 0UL) {
        response->hwpHighestPerformance =
            (ULONG)(response->msrHwpCapabilities & 0xFFULL);
        response->hwpGuaranteedPerformance =
            (ULONG)((response->msrHwpCapabilities >> 8U) & 0xFFULL);
        response->hwpMostEfficientPerformance =
            (ULONG)((response->msrHwpCapabilities >> 16U) & 0xFFULL);
        response->hwpLowestPerformance =
            (ULONG)((response->msrHwpCapabilities >> 24U) & 0xFFULL);
    }

    // The min/max/desired/EPP fields of the HWP request are located in the lower four bytes.
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_HWP_REQUEST) != 0UL) {
        response->hwpMinimumPerformance =
            (ULONG)(response->msrHwpRequest & 0xFFULL);
        response->hwpMaximumPerformance =
            (ULONG)((response->msrHwpRequest >> 8U) & 0xFFULL);
        response->hwpDesiredPerformance =
            (ULONG)((response->msrHwpRequest >> 16U) & 0xFFULL);
        response->hwpEnergyPerformancePreference =
            (ULONG)((response->msrHwpRequest >> 24U) & 0xFFULL);
    }

    // The eight bytes of the Turbo Ratio Limit are displayed in order of active core count.
    if ((response->fieldFlags &
        KSWORD_ARK_CPU_POWER_FIELD_TURBO_RATIO_LIMIT) != 0UL) {
        // Decode byte-by-byte, preserving 0 to indicate that this level is not implemented.
        for (ULONG ratioIndex = 0UL;
            ratioIndex < KSWORD_ARK_CPU_POWER_TURBO_RATIO_COUNT;
            ++ratioIndex) {
            response->turboRatios[ratioIndex] =
                (ULONG)((response->msrTurboRatioLimit >>
                    (ratioIndex * 8U)) & 0xFFULL);
        }
    }
}

// kswordArkCpuPowerQuerySnapshotUnlocked: performs a complete read-only snapshot when the caller holds the lock.
static NTSTATUS
kswordArkCpuPowerQuerySnapshotUnlocked(
    _Out_ KSWORD_ARK_CPU_POWER_RESPONSE* response
    )
{
    // perfControlSupported: derived from CPUID.1:ECX.EIST, serving as the architectural gate for reading 0x198/0x199.
    BOOLEAN perfControlSupported = FALSE;
    // Capability status is output by CPUID leaf 6.
    BOOLEAN turboSupported = FALSE;
    // hwpSupported indicates architecture support, not that IA32_PM_ENABLE is enabled.
    BOOLEAN hwpSupported = FALSE;
    // hwpEppSupported: Independently controls whether the EPP byte is writable.
    BOOLEAN hwpEppSupported = FALSE;
    // firstFailure stores the first MSR exception; the response still returns other readable fields.
    NTSTATUS firstFailure = STATUS_SUCCESS;
    // status: Receives the result of each whitelist MSR read.
    NTSTATUS status = STATUS_SUCCESS;

    // Output packet must be valid.
    if (response == NULL) {
        return STATUS_INVALID_PARAMETER;
    }

    // Zero the full response and establish a versioned fixed header.
    RtlZeroMemory(response, sizeof(*response));
    response->size = sizeof(*response);
    response->version = KSWORD_ARK_CPU_POWER_PROTOCOL_VERSION;
    // Query the number of active processors and processor groups in the current system.
    response->logicalProcessorCount =
        KeQueryActiveProcessorCountEx(ALL_PROCESSOR_GROUPS);
    response->processorGroupCount = (ULONG)KeQueryActiveGroupCount();

    // Capture CPUID first; this path does not access model-specific MSRs.
    kswordArkCpuPowerCaptureCpuid(
        response,
        &perfControlSupported,
        &turboSupported,
        &hwpSupported,
        &hwpEppSupported);

    // This module only defines write semantics for whitelisted Intel MSR registers.
    if (response->vendor != KSWORD_ARK_CPU_POWER_VENDOR_INTEL) {
        response->responseFlags |=
            KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_UNSUPPORTED_VENDOR;
        response->lastStatus = STATUS_NOT_SUPPORTED;
        return STATUS_SUCCESS;
    }

    // Publish CPUID architectural capabilities without negating the capability fact due to a single MSR read failure.
    if (turboSupported != FALSE) {
        response->capabilityFlags |= KSWORD_ARK_CPU_POWER_CAP_TURBO;
    }
    if (hwpSupported != FALSE) {
        response->capabilityFlags |= KSWORD_ARK_CPU_POWER_CAP_HWP;
    }
    if (hwpEppSupported != FALSE) {
        response->capabilityFlags |= KSWORD_ARK_CPU_POWER_CAP_HWP_EPP;
    }

    // Read the requested value and current feedback when EIST declares IA32_PERF_CTL/STATUS.
    if (perfControlSupported != FALSE) {
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_PERF_CONTROL,
            &response->msrPerfControl);
        if (NT_SUCCESS(status)) {
            response->fieldFlags |= KSWORD_ARK_CPU_POWER_FIELD_PERF_CONTROL;
            response->capabilityFlags |=
                KSWORD_ARK_CPU_POWER_CAP_PERF_CONTROL |
                KSWORD_ARK_CPU_POWER_CAP_PERF_CONTROL_PROGRAMMABLE;
        }
        else if (NT_SUCCESS(firstFailure)) {
            firstFailure = status;
        }

        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_PERF_STATUS,
            &response->msrPerfStatus);
        if (NT_SUCCESS(status)) {
            response->fieldFlags |= KSWORD_ARK_CPU_POWER_FIELD_PERF_STATUS;
        }
        else if (NT_SUCCESS(firstFailure)) {
            firstFailure = status;
        }
    }

    // Read RAPL unit.
    status = kswordArkCpuPowerReadMsr(
        KSW_CPU_POWER_MSR_RAPL_POWER_UNIT,
        &response->msrRaplPowerUnit);
    if (NT_SUCCESS(status)) {
        response->fieldFlags |= KSWORD_ARK_CPU_POWER_FIELD_RAPL_UNIT;
        response->capabilityFlags |= KSWORD_ARK_CPU_POWER_CAP_RAPL;
    }
    else {
        firstFailure = status;
    }

    // Continue reading the package power domain only if the unit is readable.
    if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_RAPL_UNIT) != 0UL) {
        // Read current PL1/PL2 and the lock bit.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_PACKAGE_POWER_LIMIT,
            &response->msrPackagePowerLimit);
        if (NT_SUCCESS(status)) {
            response->fieldFlags |=
                KSWORD_ARK_CPU_POWER_FIELD_PACKAGE_POWER_LIMIT;
            response->capabilityFlags |=
                KSWORD_ARK_CPU_POWER_CAP_PACKAGE_POWER_LIMIT;
        }
        else if (NT_SUCCESS(firstFailure)) {
            firstFailure = status;
        }

        // Read SKU power info; this register is optional, and failure does not block the current limit display.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_PACKAGE_POWER_INFO,
            &response->msrPackagePowerInfo);
        if (NT_SUCCESS(status)) {
            response->fieldFlags |=
                KSWORD_ARK_CPU_POWER_FIELD_PACKAGE_POWER_INFO;
            response->capabilityFlags |=
                KSWORD_ARK_CPU_POWER_CAP_PACKAGE_POWER_INFO;
        }
        else if (NT_SUCCESS(firstFailure)) {
            firstFailure = status;
        }
    }

    // Platform info provides multipliers and programmable hints.
    status = kswordArkCpuPowerReadMsr(
        KSW_CPU_POWER_MSR_PLATFORM_INFO,
        &response->msrPlatformInfo);
    if (NT_SUCCESS(status)) {
        response->fieldFlags |= KSWORD_ARK_CPU_POWER_FIELD_PLATFORM_INFO;
    }
    else if (NT_SUCCESS(firstFailure)) {
        firstFailure = status;
    }

    // Turbo switch depends on IA32_MISC_ENABLE.
    if (turboSupported != FALSE) {
        // Read the current Turbo disable bit.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_MISC_ENABLE,
            &response->msrMiscEnable);
        if (NT_SUCCESS(status)) {
            response->fieldFlags |= KSWORD_ARK_CPU_POWER_FIELD_MISC_ENABLE;
        }
        else if (NT_SUCCESS(firstFailure)) {
            firstFailure = status;
        }
    }

    // Read the three whitelisted MSRs (enable, capability, request) when HWP architecture is supported.
    if (hwpSupported != FALSE) {
        // First read whether HWP has already been enabled by the platform.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_PM_ENABLE,
            &response->msrPmEnable);
        if (NT_SUCCESS(status)) {
            response->fieldFlags |= KSWORD_ARK_CPU_POWER_FIELD_PM_ENABLE;
        }
        else if (NT_SUCCESS(firstFailure)) {
            firstFailure = status;
        }

        // Read performance upper and lower bound capabilities.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_HWP_CAPABILITIES,
            &response->msrHwpCapabilities);
        if (NT_SUCCESS(status)) {
            response->fieldFlags |=
                KSWORD_ARK_CPU_POWER_FIELD_HWP_CAPABILITIES;
        }
        else if (NT_SUCCESS(firstFailure)) {
            firstFailure = status;
        }

        // Read the current HWP request only when PM_ENABLE[0] is known to be 1.
        if ((response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_PM_ENABLE) != 0UL &&
            (response->msrPmEnable & 1ULL) != 0ULL) {
            // Read the request bytes for the current logical processor.
            status = kswordArkCpuPowerReadMsr(
                KSW_CPU_POWER_MSR_HWP_REQUEST,
                &response->msrHwpRequest);
            if (NT_SUCCESS(status)) {
                response->fieldFlags |=
                    KSWORD_ARK_CPU_POWER_FIELD_HWP_REQUEST;
            }
            else if (NT_SUCCESS(firstFailure)) {
                firstFailure = status;
            }
        }
    }

    // Only read 0x1AD if the platform explicitly declares the ratio limit as programmable.
    if (turboSupported != FALSE &&
        (response->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_PLATFORM_INFO) != 0UL &&
        ((response->msrPlatformInfo >> KSW_CPU_POWER_PLATFORM_RATIO_BIT) & 1ULL) != 0ULL) {
        // Read up to eight Turbo Ratio Limit levels.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_TURBO_RATIO_LIMIT,
            &response->msrTurboRatioLimit);
        if (NT_SUCCESS(status)) {
            response->fieldFlags |=
                KSWORD_ARK_CPU_POWER_FIELD_TURBO_RATIO_LIMIT;
            response->capabilityFlags |=
                KSWORD_ARK_CPU_POWER_CAP_TURBO_RATIO_LIMIT;
        }
        else if (NT_SUCCESS(firstFailure)) {
            firstFailure = status;
        }
    }

    // Decode all successfully read raw fields into integer units directly consumable by the UI.
    kswordArkCpuPowerDecodeSnapshot(response);
    // Mark as partial if any expected MSR fails, but do not disguise success fields as full failure.
    if (!NT_SUCCESS(firstFailure)) {
        response->responseFlags |=
            KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_PARTIAL_MSR;
        response->lastStatus = firstFailure;
    }
    else {
        response->lastStatus = STATUS_SUCCESS;
    }

    // Query IOCTLs always return a fixed packet upon successful transmission; the semantic status is located in lastStatus/flags.
    return STATUS_SUCCESS;
}

// kswordArkCpuPowerQuerySnapshot: performs a public read-only query under push lock.
NTSTATUS
kswordArkCpuPowerQuerySnapshot(
    _Out_ KSWORD_ARK_CPU_POWER_RESPONSE* response
    )
{
    // status receives the result of the internal fixed packet query.
    NTSTATUS status = STATUS_SUCCESS;

    // Query while entering a critical region to prevent reading an intermediate state of a modification.
    KeEnterCriticalRegion();
    ExAcquirePushLockShared(&gKswordCpuPowerLock);
    // Perform sampling for all current processors within the lock.
    status = kswordArkCpuPowerQuerySnapshotUnlocked(response);
    // Symmetrically release shared lock and critical region.
    ExReleasePushLockShared(&gKswordCpuPowerLock);
    KeLeaveCriticalRegion();
    // Returns transport-level result.
    return status;
}

// kswordArkCpuPowerMilliwattsToRaw: Converts user-space mW to RAPL 15-bit unit values.
static NTSTATUS
kswordArkCpuPowerMilliwattsToRaw(
    _In_ ULONG milliwatts,
    _In_ ULONG powerUnitMicrowatts,
    _Out_ ULONGLONG* rawPower
    )
{
    // Input and output must be within the protocol's hard boundaries.
    if (rawPower == NULL || powerUnitMicrowatts == 0UL ||
        milliwatts == 0UL ||
        milliwatts > KSWORD_ARK_CPU_POWER_ABSOLUTE_MAX_MILLIWATTS) {
        return STATUS_INVALID_PARAMETER;
    }

    // scaledMicrowatts uses 64-bit; even 1000 W remains far below the overflow boundary.
    const ULONGLONG kScaledMicrowatts = (ULONGLONG)milliwatts * 1000ULL;
    // Encode RAPL power fields to the nearest integer.
    const ULONGLONG kRawPower =
        (kScaledMicrowatts + ((ULONGLONG)powerUnitMicrowatts / 2ULL)) /
        (ULONGLONG)powerUnitMicrowatts;
    // 0 or values exceeding 15 bits cannot be silently truncated.
    if (kRawPower == 0ULL || kRawPower > KSW_CPU_POWER_LIMIT_VALUE_MASK) {
        return STATUS_INTEGER_OVERFLOW;
    }

    // Publish the verified 15-bit value.
    *rawPower = kRawPower;
    return STATUS_SUCCESS;
}

// kswordArkCpuPowerValidateExpectedSnapshot: Prevents the UI from overwriting firmware or other tools' new settings with stale values.
static NTSTATUS
kswordArkCpuPowerValidateExpectedSnapshot(
    _In_ const KSWORD_ARK_CPU_POWER_CONTROL_REQUEST* request,
    _Inout_ KSWORD_ARK_CPU_POWER_RESPONSE* snapshot
    )
{
    // Return directly when an optimistic check is not requested.
    if ((request->requestFlags &
        KSWORD_ARK_CPU_POWER_REQUEST_FLAG_REQUIRE_CURRENT) == 0UL) {
        return STATUS_SUCCESS;
    }

    // Only compare registers that will be modified in this operation; other operations will not cause irrelevant conflicts.
    if (((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_POWER_LIMITS) != 0UL &&
            request->expectedPackagePowerLimit != snapshot->msrPackagePowerLimit) ||
        ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_TURBO) != 0UL &&
            request->expectedMiscEnable != snapshot->msrMiscEnable) ||
        ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_HWP) != 0UL &&
            request->expectedHwpRequest != snapshot->msrHwpRequest) ||
        ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_TURBO_RATIO) != 0UL &&
            request->expectedTurboRatioLimit != snapshot->msrTurboRatioLimit) ||
        ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_PERF_CONTROL) != 0UL &&
            request->expectedPerfControl != snapshot->msrPerfControl)) {
        // Mark as stale, to be interpreted by the UI as 'refresh and retry'.
        snapshot->responseFlags |=
            KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_STALE_SNAPSHOT;
        // failureReason allows R3 to distinguish between concurrent snapshot conflicts and ordinary parameter errors.
        snapshot->failureReason =
            KSWORD_ARK_CPU_POWER_FAILURE_STALE_SNAPSHOT;
        snapshot->lastStatus = STATUS_REVISION_MISMATCH;
        return STATUS_REVISION_MISMATCH;
    }

    // All affected registers remain consistent with the UI snapshot.
    return STATUS_SUCCESS;
}

// kswordArkCpuPowerValidateRequest: validates structured requests against capabilities, lock bits, and value ranges.
static NTSTATUS
kswordArkCpuPowerValidateRequest(
    _In_ const KSWORD_ARK_CPU_POWER_CONTROL_REQUEST* request,
    _Inout_ KSWORD_ARK_CPU_POWER_RESPONSE* snapshot
    )
{
    // The protocol header, flags, and UI confirmation are hard-gated.
    if (request == NULL || snapshot == NULL) {
        return STATUS_INVALID_PARAMETER;
    }
    // If a response already exists, record the specific cause for protocol header/flags errors.
    if (
        request->size < sizeof(*request) ||
        request->version != KSWORD_ARK_CPU_POWER_PROTOCOL_VERSION ||
        request->applyFlags == 0UL ||
        (request->applyFlags & ~KSWORD_ARK_CPU_POWER_APPLY_ALL) != 0UL ||
        (request->requestFlags &
            ~(KSWORD_ARK_CPU_POWER_REQUEST_FLAG_UI_CONFIRMED |
              KSWORD_ARK_CPU_POWER_REQUEST_FLAG_REQUIRE_CURRENT |
              KSWORD_ARK_CPU_POWER_REQUEST_FLAG_TURBO_RATIO_ARRAY)) != 0UL ||
        ((request->requestFlags &
            KSWORD_ARK_CPU_POWER_REQUEST_FLAG_TURBO_RATIO_ARRAY) != 0UL &&
         (request->applyFlags &
            KSWORD_ARK_CPU_POWER_APPLY_TURBO_RATIO) == 0UL) ||
        (request->requestFlags &
            KSWORD_ARK_CPU_POWER_REQUEST_FLAG_UI_CONFIRMED) == 0UL) {
        snapshot->failureReason =
            KSWORD_ARK_CPU_POWER_FAILURE_REQUEST_HEADER;
        return STATUS_INVALID_PARAMETER;
    }

    // Note: AMD SMU interface varies by family/model; this version does not apply Intel MSR semantics to AMD.
    if (snapshot->vendor != KSWORD_ARK_CPU_POWER_VENDOR_INTEL) {
        snapshot->failureReason = KSWORD_ARK_CPU_POWER_FAILURE_VENDOR;
        return STATUS_NOT_SUPPORTED;
    }

    // Changing PL1/PL2 requires the units, current limits, and evidence that the settings are unlocked.
    if ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_POWER_LIMITS) != 0UL) {
        // Reject writes if either capability or lock is not satisfied.
        if ((snapshot->capabilityFlags &
                KSWORD_ARK_CPU_POWER_CAP_PACKAGE_POWER_PROGRAMMABLE) == 0ULL ||
            (snapshot->fieldFlags & KSWORD_ARK_CPU_POWER_FIELD_RAPL_UNIT) == 0UL ||
            (snapshot->fieldFlags &
                KSWORD_ARK_CPU_POWER_FIELD_PACKAGE_POWER_LIMIT) == 0UL ||
            (snapshot->responseFlags &
                KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_POWER_LIMIT_LOCKED) != 0UL) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_POWER_CAPABILITY;
            return STATUS_ACCESS_DENIED;
        }

        // The protocol absolute upper limit is always valid.
        if (request->pl1Milliwatts == 0UL ||
            request->pl2Milliwatts == 0UL ||
            request->pl1Milliwatts >
                KSWORD_ARK_CPU_POWER_ABSOLUTE_MAX_MILLIWATTS ||
            request->pl2Milliwatts >
                KSWORD_ARK_CPU_POWER_ABSOLUTE_MAX_MILLIWATTS) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_POWER_ABSOLUTE_RANGE;
            return STATUS_INVALID_PARAMETER;
        }

        // When the SKU provides a non-0 maximum power, prohibit exceeding this platform boundary.
        if (snapshot->packageMaximumPowerMilliwatts != 0UL &&
            (request->pl1Milliwatts >
                snapshot->packageMaximumPowerMilliwatts ||
             request->pl2Milliwatts >
                snapshot->packageMaximumPowerMilliwatts)) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_POWER_PLATFORM_MAXIMUM;
            return STATUS_INVALID_PARAMETER;
        }

        // Rejects values below the hardware-declared range when the SKU provides a non-0 minimum power.
        if (snapshot->packageMinimumPowerMilliwatts != 0UL &&
            (request->pl1Milliwatts <
                snapshot->packageMinimumPowerMilliwatts ||
             request->pl2Milliwatts <
                snapshot->packageMinimumPowerMilliwatts)) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_POWER_PLATFORM_MINIMUM;
            return STATUS_INVALID_PARAMETER;
        }

        // Four boolean fields accept only 0 or 1.
        if (request->pl1Enabled > 1UL ||
            request->pl1ClampEnabled > 1UL ||
            request->pl2Enabled > 1UL ||
            request->pl2ClampEnabled > 1UL) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_POWER_BOOLEAN;
            return STATUS_INVALID_PARAMETER;
        }
    }

    // The Turbo switch requires dual evidence from both CPUID and IA32_MISC_ENABLE.
    if ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_TURBO) != 0UL) {
        // Reject if the feature is not implemented or the input is not a boolean.
        if ((snapshot->capabilityFlags &
                KSWORD_ARK_CPU_POWER_CAP_TURBO_CONTROL) == 0ULL ||
            request->turboEnabled > 1UL) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_TURBO_CAPABILITY;
            return STATUS_NOT_SUPPORTED;
        }
    }

    // HWP modification requires firmware/OS to already have HWP enabled.
    if ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_HWP) != 0UL) {
        // capability, enabled, request, and the capability MSR are all required; none may be omitted.
        if ((snapshot->capabilityFlags & KSWORD_ARK_CPU_POWER_CAP_HWP) == 0ULL ||
            (snapshot->capabilityFlags &
                KSWORD_ARK_CPU_POWER_CAP_HWP_ENABLED) == 0ULL ||
            (snapshot->fieldFlags &
                KSWORD_ARK_CPU_POWER_FIELD_HWP_CAPABILITIES) == 0UL ||
            (snapshot->fieldFlags &
                KSWORD_ARK_CPU_POWER_FIELD_HWP_REQUEST) == 0UL) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_HWP_CAPABILITY;
            return STATUS_NOT_SUPPORTED;
        }

        // All four HWP fields are 8 bits.
        if (request->hwpMinimumPerformance > 0xFFUL ||
            request->hwpMaximumPerformance > 0xFFUL ||
            request->hwpDesiredPerformance > 0xFFUL ||
            request->hwpEnergyPerformancePreference > 0xFFUL) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_HWP_PLATFORM_RANGE;
            return STATUS_INVALID_PARAMETER;
        }
        // minimum > maximum is the most common UI relationship error; report it separately.
        if (request->hwpMinimumPerformance >
            request->hwpMaximumPerformance) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_HWP_ORDER;
            return STATUS_INVALID_PARAMETER;
        }

        // A non-0 desired value must be within the requested min/max range.
        if (request->hwpDesiredPerformance != 0UL &&
            (request->hwpDesiredPerformance <
                request->hwpMinimumPerformance ||
             request->hwpDesiredPerformance >
                request->hwpMaximumPerformance)) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_HWP_DESIRED_RANGE;
            return STATUS_INVALID_PARAMETER;
        }

        // HWP capability must enforce the provided non-0 upper and lower bounds.
        if (snapshot->hwpLowestPerformance != 0UL &&
            request->hwpMinimumPerformance <
                snapshot->hwpLowestPerformance) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_HWP_PLATFORM_RANGE;
            return STATUS_INVALID_PARAMETER;
        }
        if (snapshot->hwpHighestPerformance != 0UL &&
            (request->hwpMaximumPerformance >
                snapshot->hwpHighestPerformance ||
             request->hwpDesiredPerformance >
                snapshot->hwpHighestPerformance)) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_HWP_PLATFORM_RANGE;
            return STATUS_INVALID_PARAMETER;
        }

        // Prevent users from silently modifying this reserved byte when EPP is unsupported.
        if ((snapshot->capabilityFlags &
                KSWORD_ARK_CPU_POWER_CAP_HWP_EPP) == 0ULL &&
            request->hwpEnergyPerformancePreference !=
                snapshot->hwpEnergyPerformancePreference) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_HWP_EPP;
            return STATUS_NOT_SUPPORTED;
        }
    }

    // Turbo Ratio is enabled only when both platform bit 28 and 0x1AD are readable.
    if ((request->applyFlags &
        KSWORD_ARK_CPU_POWER_APPLY_TURBO_RATIO) != 0UL) {
        // Note: ratio is a full-range target from 1 to 255; the restore path can provide a structured array per step.
        if ((snapshot->capabilityFlags &
                KSWORD_ARK_CPU_POWER_CAP_TURBO_RATIO_PROGRAMMABLE) == 0ULL ||
            (snapshot->fieldFlags &
                KSWORD_ARK_CPU_POWER_FIELD_TURBO_RATIO_LIMIT) == 0UL) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_TURBO_RATIO;
            return STATUS_NOT_SUPPORTED;
        }

        // Only verify non-zero gear levels currently implemented by hardware; prohibit writing 0 or truncated values to valid gear levels.
        BOOLEAN hasImplementedRatio = FALSE;
        for (ULONG ratioIndex = 0UL;
            ratioIndex < KSWORD_ARK_CPU_POWER_TURBO_RATIO_COUNT;
            ++ratioIndex) {
            if (snapshot->turboRatios[ratioIndex] == 0UL) {
                continue;
            }
            hasImplementedRatio = TRUE;
            const ULONG kTargetRatio =
                (request->requestFlags &
                    KSWORD_ARK_CPU_POWER_REQUEST_FLAG_TURBO_RATIO_ARRAY) != 0UL
                ? request->turboRatios[ratioIndex]
                : request->turboRatio;
            if (kTargetRatio == 0UL || kTargetRatio > 0xFFUL) {
                snapshot->failureReason =
                    KSWORD_ARK_CPU_POWER_FAILURE_TURBO_RATIO;
                return STATUS_INVALID_PARAMETER;
            }
        }
        if (hasImplementedRatio == FALSE) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_TURBO_RATIO;
            return STATUS_NOT_SUPPORTED;
        }
    }

    // The request for frequency multiplier is restricted to IA32_PERF_CTL[15:8] and requires EIST capability and readability detection.
    if ((request->applyFlags &
        KSWORD_ARK_CPU_POWER_APPLY_PERF_CONTROL) != 0UL) {
        if ((snapshot->capabilityFlags &
                KSWORD_ARK_CPU_POWER_CAP_PERF_CONTROL_PROGRAMMABLE) == 0ULL ||
            (snapshot->fieldFlags &
                KSWORD_ARK_CPU_POWER_FIELD_PERF_CONTROL) == 0UL ||
            request->requestedMultiplier == 0UL ||
            request->requestedMultiplier > 0xFFUL) {
            snapshot->failureReason =
                KSWORD_ARK_CPU_POWER_FAILURE_PERF_CONTROL;
            return STATUS_NOT_SUPPORTED;
        }
    }

    // Finally perform the optimistic snapshot comparison.
    return kswordArkCpuPowerValidateExpectedSnapshot(request, snapshot);
}

// kswordArkCpuPowerBuildPackageLimit: Preserves time window and reserved bits; only replaces PL1/PL2 values and switches.
static NTSTATUS
kswordArkCpuPowerBuildPackageLimit(
    _In_ const KSWORD_ARK_CPU_POWER_CONTROL_REQUEST* request,
    _In_ ULONG powerUnitMicrowatts,
    _In_ ULONGLONG currentValue,
    _Out_ ULONGLONG* newValue
    )
{
    // rawPl1/rawPl2 receive validated 15-bit unit values.
    ULONGLONG rawPl1 = 0ULL;
    ULONGLONG rawPl2 = 0ULL;
    // status: Stores the result of each encoding operation.
    NTSTATUS status = STATUS_SUCCESS;
    // The low and high 17-bit intervals cover the value, enable, and clamp.
    const ULONGLONG kFirstMask = 0x1FFFFULL;
    const ULONGLONG kSecondMask = 0x1FFFFULL <<
        KSW_CPU_POWER_LIMIT_SECOND_SHIFT;

    // Encode PL1 and PL2 separately.
    status = kswordArkCpuPowerMilliwattsToRaw(
        request->pl1Milliwatts,
        powerUnitMicrowatts,
        &rawPl1);
    if (!NT_SUCCESS(status)) {
        return status;
    }
    status = kswordArkCpuPowerMilliwattsToRaw(
        request->pl2Milliwatts,
        powerUnitMicrowatts,
        &rawPl2);
    if (!NT_SUCCESS(status)) {
        return status;
    }

    // Clear the two controllable 17-bit regions first, preserving the time window, lock, and reserved bits.
    *newValue = currentValue & ~(kFirstMask | kSecondMask);
    // Write the original PL1 value.
    *newValue |= rawPl1;
    // Write PL1 enable/clamp as requested.
    *newValue |= ((ULONGLONG)request->pl1Enabled) <<
        KSW_CPU_POWER_LIMIT_ENABLE_BIT;
    *newValue |= ((ULONGLONG)request->pl1ClampEnabled) <<
        KSW_CPU_POWER_LIMIT_CLAMP_BIT;
    // Write the PL2 raw value along with the two switches.
    *newValue |= rawPl2 << KSW_CPU_POWER_LIMIT_SECOND_SHIFT;
    *newValue |= ((ULONGLONG)request->pl2Enabled) <<
        KSW_CPU_POWER_LIMIT_SECOND_ENABLE;
    *newValue |= ((ULONGLONG)request->pl2ClampEnabled) <<
        KSW_CPU_POWER_LIMIT_SECOND_CLAMP;
    // The lock bit must not change during construction.
    if (((*newValue ^ currentValue) &
        (1ULL << KSW_CPU_POWER_LIMIT_LOCK_BIT)) != 0ULL) {
        return STATUS_DATA_ERROR;
    }

    // Return the complete new value.
    return STATUS_SUCCESS;
}

// kswordArkCpuPowerApplyCurrentProcessor: applies whitelist modifications and re-reads on the currently bound logical processor.
static NTSTATUS
kswordArkCpuPowerApplyCurrentProcessor(
    _In_ const KSWORD_ARK_CPU_POWER_CONTROL_REQUEST* request,
    _In_ const KSWORD_ARK_CPU_POWER_RESPONSE* snapshot
    )
{
    // currentValue/newValue/readbackValue are reused for each serial MSR operation.
    ULONGLONG currentValue = 0ULL;
    ULONGLONG newValue = 0ULL;
    ULONGLONG readbackValue = 0ULL;
    // status: Stores the state for each read, construct, and write operation.
    NTSTATUS status = STATUS_SUCCESS;

    // RAPL package limit modifications preserve the two time windows, lock, and all reserved bits.
    if ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_POWER_LIMITS) != 0UL) {
        // Re-read for each processor to support independent current values on multi-package systems.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_PACKAGE_POWER_LIMIT,
            &currentValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // Write access to the processor is denied if any package is locked.
        if (((currentValue >> KSW_CPU_POWER_LIMIT_LOCK_BIT) & 1ULL) != 0ULL) {
            return STATUS_ACCESS_DENIED;
        }
        // Replace only the structurally controllable fields.
        status = kswordArkCpuPowerBuildPackageLimit(
            request,
            snapshot->powerUnitMicrowatts,
            currentValue,
            &newValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // Write the complete read-modify-write result.
        status = kswordArkCpuPowerWriteMsr(
            KSW_CPU_POWER_MSR_PACKAGE_POWER_LIMIT,
            newValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // Immediately read back and verify both 17-bit controllable regions.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_PACKAGE_POWER_LIMIT,
            &readbackValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        if (((readbackValue ^ newValue) &
            (0x1FFFFULL | (0x1FFFFULL <<
                KSW_CPU_POWER_LIMIT_SECOND_SHIFT))) != 0ULL) {
            return STATUS_DATA_ERROR;
        }
    }

    // The Turbo switch only modifies IA32_MISC_ENABLE[38].
    if ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_TURBO) != 0UL) {
        // Reads the current full value of this logical processor.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_MISC_ENABLE,
            &currentValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // Clear the disable bit when enabling Turbo; set the bit when disabling.
        newValue = request->turboEnabled != 0UL
            ? currentValue & ~(1ULL << KSW_CPU_POWER_MISC_TURBO_DISABLE_BIT)
            : currentValue | (1ULL << KSW_CPU_POWER_MISC_TURBO_DISABLE_BIT);
        // Write the full value changing only one architectural bit.
        status = kswordArkCpuPowerWriteMsr(
            KSW_CPU_POWER_MSR_MISC_ENABLE,
            newValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // Read back to verify bit 38; ignore other firmware concurrent changes to avoid false failure detection.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_MISC_ENABLE,
            &readbackValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        if (((readbackValue ^ newValue) &
            (1ULL << KSW_CPU_POWER_MISC_TURBO_DISABLE_BIT)) != 0ULL) {
            return STATUS_DATA_ERROR;
        }
    }

    // The request modifies only the IA32_PERF_CTL[15:8] multiplier bits, preserving voltage and all model-specific bits.
    if ((request->applyFlags &
        KSWORD_ARK_CPU_POWER_APPLY_PERF_CONTROL) != 0UL) {
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_PERF_CONTROL,
            &currentValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        newValue = currentValue & ~KSW_CPU_POWER_PERF_RATIO_MASK;
        newValue |= ((ULONGLONG)request->requestedMultiplier) <<
            KSW_CPU_POWER_PERF_RATIO_SHIFT;
        status = kswordArkCpuPowerWriteMsr(
            KSW_CPU_POWER_MSR_PERF_CONTROL,
            newValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_PERF_CONTROL,
            &readbackValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        if (((readbackValue ^ newValue) &
            KSW_CPU_POWER_PERF_RATIO_MASK) != 0ULL) {
            return STATUS_DATA_ERROR;
        }
    }

    // HWP requests are per-logical-processor states, so they must be updated per-processor.
    if ((request->applyFlags & KSWORD_ARK_CPU_POWER_APPLY_HWP) != 0UL) {
        // Read the current processor request and preserve the high 32 bits of the package/control field.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_HWP_REQUEST,
            &currentValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // Clear the min, max, and desired bytes.
        newValue = currentValue & ~0x0000000000FFFFFFULL;
        // Write three structured performance request bytes.
        newValue |= (ULONGLONG)request->hwpMinimumPerformance;
        newValue |= ((ULONGLONG)request->hwpMaximumPerformance) << 8U;
        newValue |= ((ULONGLONG)request->hwpDesiredPerformance) << 16U;
        // Replace the EPP byte only if CPUID declares EPP support.
        if ((snapshot->capabilityFlags &
            KSWORD_ARK_CPU_POWER_CAP_HWP_EPP) != 0ULL) {
            newValue &= ~0x00000000FF000000ULL;
            newValue |=
                ((ULONGLONG)request->hwpEnergyPerformancePreference) << 24U;
        }
        // Write the HWP request for the current logical processor.
        status = kswordArkCpuPowerWriteMsr(
            KSW_CPU_POWER_MSR_HWP_REQUEST,
            newValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // Reads back the lower 24 or 32 bits to verify the actually accepted value.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_HWP_REQUEST,
            &readbackValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // verifyMask: Selects the verification range based on EPP capability.
        const ULONGLONG kVerifyMask =
            (snapshot->capabilityFlags &
                KSWORD_ARK_CPU_POWER_CAP_HWP_EPP) != 0ULL
            ? 0x00000000FFFFFFFFULL
            : 0x0000000000FFFFFFULL;
        // Return data error when the firmware does not accept the request.
        if (((readbackValue ^ newValue) & kVerifyMask) != 0ULL) {
            return STATUS_DATA_ERROR;
        }
    }

    // Turbo Ratio Limit replaces only non-0 levels already implemented in the current MSR.
    if ((request->applyFlags &
        KSWORD_ARK_CPU_POWER_APPLY_TURBO_RATIO) != 0UL) {
        // Read the 1..8 core tier for the current package.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_TURBO_RATIO_LIMIT,
            &currentValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // newValue starts from the current value to avoid writing to unimplemented 0-ratio slots.
        newValue = currentValue;
        // changedMask: Only covers slots that were originally non-0.
        ULONGLONG changedMask = 0ULL;
        // Iterate over the eight architecture-defined ratio bytes.
        for (ULONG ratioIndex = 0UL;
            ratioIndex < KSWORD_ARK_CPU_POWER_TURBO_RATIO_COUNT;
            ++ratioIndex) {
            // shift: Byte offset of the current gear.
            const ULONG kShift = ratioIndex * 8U;
            // Keep the state as not implemented when the current byte is 0.
            if (((currentValue >> kShift) & 0xFFULL) == 0ULL) {
                continue;
            }
            // Normal operations write to the same target; restore operations recover each level according to the structured array.
            const ULONG kTargetRatio =
                (request->requestFlags &
                    KSWORD_ARK_CPU_POWER_REQUEST_FLAG_TURBO_RATIO_ARRAY) != 0UL
                ? request->turboRatios[ratioIndex]
                : request->turboRatio;
            newValue &= ~(0xFFULL << kShift);
            newValue |= ((ULONGLONG)kTargetRatio) << kShift;
            // Record this byte for post-write verification.
            changedMask |= 0xFFULL << kShift;
        }
        // Reject constructing a guess when no gear is implemented.
        if (changedMask == 0ULL) {
            return STATUS_NOT_SUPPORTED;
        }
        // Write package Turbo Ratio Limit.
        status = kswordArkCpuPowerWriteMsr(
            KSW_CPU_POWER_MSR_TURBO_RATIO_LIMIT,
            newValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        // Re-read all affected levels.
        status = kswordArkCpuPowerReadMsr(
            KSW_CPU_POWER_MSR_TURBO_RATIO_LIMIT,
            &readbackValue);
        if (!NT_SUCCESS(status)) {
            return status;
        }
        if (((readbackValue ^ newValue) & changedMask) != 0ULL) {
            return STATUS_DATA_ERROR;
        }
    }

    // All request fields for the current logical processor have completed back-read verification.
    return STATUS_SUCCESS;
}

// kswordArkCpuPowerApplyAllProcessors: Bind and update all active processors group-by-group at PASSIVE_LEVEL.
static NTSTATUS
kswordArkCpuPowerApplyAllProcessors(
    _In_ const KSWORD_ARK_CPU_POWER_CONTROL_REQUEST* request,
    _In_ const KSWORD_ARK_CPU_POWER_RESPONSE* snapshot,
    _Out_ ULONG* updatedProcessorCount,
    _Out_ ULONG* failedProcessorCount
    )
{
    // groupCount is the number of currently active processor groups.
    const USHORT kGroupCount = KeQueryActiveGroupCount();
    // firstFailure: Preserve the first failure status while continuing the loop to cover other packages/cores.
    NTSTATUS firstFailure = STATUS_SUCCESS;

    // initialize count output.
    *updatedProcessorCount = 0UL;
    *failedProcessorCount = 0UL;

    // Iterate over each active processor group.
    for (USHORT groupIndex = 0U; groupIndex < kGroupCount; ++groupIndex) {
        // processorCount is the number of active logical processors in the current group.
        const ULONG kProcessorCount =
            KeQueryActiveProcessorCountEx(groupIndex);
        // Iterate through all active processor indices within the group.
        for (ULONG processorIndex = 0UL;
            processorIndex < kProcessorCount;
            ++processorIndex) {
            // targetAffinity: Precisely bind the current system thread to a logical processor.
            GROUP_AFFINITY targetAffinity;
            // previousAffinity: Used to unconditionally restore the calling thread's original affinity.
            GROUP_AFFINITY previousAffinity;
            // status: Receives the complete modification result for the current logical processor.
            NTSTATUS status = STATUS_SUCCESS;

            // Processor indices that cannot be expressed by KAFFINITY are explicitly counted as failures.
            if (processorIndex >= sizeof(KAFFINITY) * 8UL) {
                ++(*failedProcessorCount);
                if (NT_SUCCESS(firstFailure)) {
                    firstFailure = STATUS_NOT_SUPPORTED;
                }
                continue;
            }

            // Zero out both affinity structures so retained fields do not carry stack garbage.
            RtlZeroMemory(&targetAffinity, sizeof(targetAffinity));
            RtlZeroMemory(&previousAffinity, sizeof(previousAffinity));
            // Set the target group and single-processor mask.
            targetAffinity.Group = groupIndex;
            targetAffinity.Mask = ((KAFFINITY)1) << processorIndex;
            // Bind the current system thread to the target processor.
            KeSetSystemGroupAffinityThread(
                &targetAffinity,
                &previousAffinity);
            // Execute whitelist read-modify-write and re-read on the target processor.
            status = kswordArkCpuPowerApplyCurrentProcessor(
                request,
                snapshot);
            // Restore the calling thread's affinity regardless of the result.
            KeRevertToUserGroupAffinityThread(&previousAffinity);

            // Accumulate successful and failed processors separately.
            if (NT_SUCCESS(status)) {
                ++(*updatedProcessorCount);
            }
            else {
                ++(*failedProcessorCount);
                if (NT_SUCCESS(firstFailure)) {
                    firstFailure = status;
                }
            }
        }
    }

    // Return explicit failure when no processors were updated.
    if (*updatedProcessorCount == 0UL && NT_SUCCESS(firstFailure)) {
        firstFailure = STATUS_NOT_FOUND;
    }
    // Return value: Returns the first failure; returns STATUS_SUCCESS if all succeed.
    return firstFailure;
}

// kswordArkCpuPowerApply: Serializes validation, performs cross-processor modifications, and publishes the final read-back snapshot.
NTSTATUS
kswordArkCpuPowerApply(
    _In_ const KSWORD_ARK_CPU_POWER_CONTROL_REQUEST* request,
    _Out_ KSWORD_ARK_CPU_POWER_RESPONSE* response
    )
{
    // status: Receives validation, write, and final query results.
    NTSTATUS status = STATUS_SUCCESS;
    // updatedCount/failedCount are saved separately before the final read-back overwrites the response.
    ULONG updatedCount = 0UL;
    ULONG failedCount = 0UL;

    // Public entry point first validates pointers; protocol fields are validated within the lock.
    if (request == NULL || response == NULL) {
        return STATUS_INVALID_PARAMETER;
    }
    // MSR writes are allowed only in system thread context at PASSIVE_LEVEL.
    if (KeGetCurrentIrql() != PASSIVE_LEVEL) {
        return STATUS_INVALID_DEVICE_STATE;
    }

    // Exclusive lock covers the initial snapshot, all processor writes, and the final readback.
    KeEnterCriticalRegion();
    ExAcquirePushLockExclusive(&gKswordCpuPowerLock);

    // Sample the current state first; all capability comparisons against expected values are based on the same snapshot within the lock.
    status = kswordArkCpuPowerQuerySnapshotUnlocked(response);
    if (!NT_SUCCESS(status)) {
        goto Exit;
    }
    // Validate protocol header, capabilities, values, lock bits, and optimistic snapshot.
    status = kswordArkCpuPowerValidateRequest(request, response);
    if (!NT_SUCCESS(status)) {
        response->lastStatus = status;
        goto Exit;
    }

    // Update all active logical processors group by group.
    status = kswordArkCpuPowerApplyAllProcessors(
        request,
        response,
        &updatedCount,
        &failedCount);
    if (!NT_SUCCESS(status)) {
        // Write phase failures and parameter validation failures must be distinguishable in the fixed response.
        response->failureReason =
            KSWORD_ARK_CPU_POWER_FAILURE_PROCESSOR_APPLY;
        // Explicitly mark as partial when some processors succeed, to avoid the UI claiming atomic success.
        if (updatedCount != 0UL) {
            response->responseFlags |=
                KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_WRITE_PARTIAL;
        }
        response->updatedProcessorCount = updatedCount;
        response->failedProcessorCount = failedCount;
        response->lastStatus = status;
        goto Exit;
    }

    // After all writes succeed, resample the current calling processor and return the actual read-back value to the UI.
    status = kswordArkCpuPowerQuerySnapshotUnlocked(response);
    if (!NT_SUCCESS(status)) {
        goto Exit;
    }
    // Restore cross-processor counts and mark all workers as having completed the back-read verification.
    response->updatedProcessorCount = updatedCount;
    response->failedProcessorCount = failedCount;
    response->responseFlags |=
        KSWORD_ARK_CPU_POWER_RESPONSE_FLAG_WRITE_VERIFIED;
    response->lastStatus = STATUS_SUCCESS;

Exit:
    // Symmetrically release exclusive lock and critical region.
    ExReleasePushLockExclusive(&gKswordCpuPowerLock);
    KeLeaveCriticalRegion();
    // Return value: Returns the true semantic status; the IOCTL handler still sets a fixed response length.
    return status;
}
