"""Generate the English CLI command reference from the built-in help registry."""

import argparse
from pathlib import Path

from cli_catalog import read_catalog

ROOT = Path(__file__).resolve().parents[1]


def render(root: Path = ROOT) -> str:
    families, commands = read_catalog(root / "apps/cli/CliHelp.cpp")
    lines = ["# CLI reference", "", "[简体中文](zh-CN/cli.md) · [Documentation index](README.md)", "",
             "<!-- Generated by tools/generate_cli_docs.py. Edit CliHelp.cpp, then regenerate. -->", "",
             "This reference lists every registered command and alias. Help works without a loaded",
             "driver. Most operations require an administrator and an available KswordARK device;",
             "a successful help check does not establish runtime support.", "",
             "## Finding help", "", "```powershell", "KswordCLI.exe help",
             "KswordCLI.exe help <family>", "KswordCLI.exe help <family> <command>",
             "KswordCLI.exe <family> help", "KswordCLI.exe <family> <command> --help", "```", "",
             "## Argument conventions", "",
             "- Numbers accept decimal or `0x` hexadecimal; the existing base-zero parser also accepts octal with a leading zero.",
             "- Unsigned values reject negatives and overflow; they do not silently clamp to the maximum integer.",
             "- `--flags` is a bitmask defined by the corresponding `shared/driver/` protocol.",
             "- `--limit` bounds printed rows; `--max-*` typically bounds the driver query budget.",
             "- Hex payloads accept one initial `0x` and whitespace, comma, colon, hyphen, or underscore separators.",
             "  Odd digit counts, a bare `0x`, and non-hex characters are rejected.",
             "- Hex and file forms of the same payload are mutually exclusive.", "",
             "## Command families", "", "| Family | Purpose |", "| --- | --- |"]
    lines += [f"| [{name}](#{name}) | {summary.replace('|', r'\|')} |" for name, summary in families]
    for family, summary in families:
        lines += ["", f"## {family}", "", summary]
        for command in commands:
            if command.family != family:
                continue
            lines += ["", f"### {family} {command.name}".rstrip(), "", command.summary,
                      "", "```text", command.syntax, "```"]
            for description in (command.options, command.notes):
                if description:
                    lines += ["", description]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "docs/cli.md"
    expected = render()
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            print("CLI reference is stale. Run: python tools/generate_cli_docs.py")
            return 1
        print("CLI reference matches the help registry.")
    else:
        path.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Updated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
