"""Check source membership in tracked MSBuild projects and Visual Studio filters.

This checks declarative source items, not evaluated MSBuild output. Dynamic
items containing properties, item expressions or globs are left to MSBuild.
"""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
import posixpath
import subprocess
import xml.etree.ElementTree as ET


SOURCE_TYPES = {"ClCompile", "ClInclude", "QtMoc", "QtUic", "QtRcc", "ResourceCompile", "MASM"}
# Generated by apps/setup's GenerateKswordSetupPayload target before compilation.
GENERATED_INPUTS = {
    "apps/setup/generated/PayloadResources.h",
    "apps/setup/generated/PayloadResources.rc",
}


def git_files(root: Path, *patterns: str) -> list[str]:
    raw = subprocess.check_output(
        ["git", "ls-files", "-z", "--", *patterns], cwd=root,
    )
    return [path.decode("utf-8") for path in raw.split(b"\0") if path]


def source_items(path: Path) -> list[tuple[str, str]]:
    items = []
    for group in ET.parse(path).getroot():
        if group.tag.rsplit("}", 1)[-1] != "ItemGroup":
            continue
        for item in group:
            kind = item.tag.rsplit("}", 1)[-1]
            include = item.get("Include")
            # Item metadata is text, never a nested source list. Catch malformed
            # project edits before MSBuild reports an invalid project GUID.
            for metadata in item:
                if len(metadata):
                    raise ValueError(f"{path.name}: nested XML in {kind} metadata {metadata.tag.rsplit('}', 1)[-1]}")
            if kind in SOURCE_TYPES and include:
                items.append((kind, posixpath.normpath(include.replace("\\", "/"))))
    return items


def audit_project(root: Path, project: str, tracked: set[str]) -> list[str]:
    errors = []
    path = root / project
    filters = Path(str(path) + ".filters")
    try:
        items = source_items(path)
        if not filters.is_file():
            return [f"{project}: missing .filters file"]
        filter_items = source_items(filters)
    except (OSError, ET.ParseError, ValueError) as error:
        return [f"{project}: {error}"]

    for label, entries in ((project, items), (project + ".filters", filter_items)):
        counts = Counter((kind, name.casefold()) for kind, name in entries)
        for (kind, name), count in sorted(counts.items()):
            if count > 1:
                errors.append(f"{label}: duplicate {kind} {name} ({count} entries)")

    project_set = {(kind, name.casefold()) for kind, name in items}
    filter_set = {(kind, name.casefold()) for kind, name in filter_items}
    for kind, name in sorted(project_set - filter_set):
        errors.append(f"{project}.filters: missing {kind} {name}")
    for kind, name in sorted(filter_set - project_set):
        errors.append(f"{project}.filters: stale or wrong item type: {kind} {name}")
    for kind, name in items:
        if any(marker in name for marker in ("$(", "%(", "@(", "*", "?", ";")):
            continue
        relative = posixpath.normpath(posixpath.join(posixpath.dirname(project), name))
        if relative in GENERATED_INPUTS:
            continue
        # Check Git's exact spelling as well as existence, so Linux CI catches
        # paths that only work on case-insensitive developer filesystems.
        if relative not in tracked:
            errors.append(f"{project}: {kind} input is not tracked with this spelling: {relative}")
        elif not (root / relative).is_file():
            errors.append(f"{project}: missing input: {relative}")
    return errors


def audit(root: Path) -> list[str]:
    tracked = set(git_files(root))
    projects = sorted(path for path in tracked if path.endswith(".vcxproj"))
    if not projects:
        return ["No tracked MSBuild projects found."]
    errors = [error for project in projects for error in audit_project(root, project, tracked)]
    print(f"Checked {len(projects)} MSBuild projects.")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    errors = audit(args.repo_root.resolve())
    for error in errors:
        print(error)
    return int(bool(errors))


if __name__ == "__main__":
    raise SystemExit(main())
