#pragma once

// ============================================================
// RegistryDock.h
// Purpose:
// 1) Provide registry browsing and editing capabilities similar to regedit.
// 2) Supports key tree navigation, value table display, and create/delete/rename/edit operations.
// 3) Support .reg import/export and background full-text search to avoid blocking the UI.
// ============================================================

#include "../Framework.h"

#include <QWidget>

#include <atomic>      // std::atomic_bool: Controls the running state of the search thread.
#include <deque>       // std::deque: FIFO queue for search results to avoid head-consumption shifting.
#include <memory>      // std::unique_ptr: manages the background thread object.
#include <mutex>       // std::mutex: Protect cross-thread result queue.
#include <thread>      // std::thread: Background search thread.
#include <vector>      // std::vector: Container for result cache and historical paths.

// Qt forward declaration: reduces header coupling and compilation time.
class QHBoxLayout;
class QLabel;
class QLineEdit;
class QPushButton;
class QSplitter;
class QStatusBar;
class QTabWidget;
class QTableWidget;
class QTableWidgetItem;
class QTimer;
class QTreeWidget;
class QTreeWidgetItem;
class QVBoxLayout;
class RegistryOptimizationPage;

// ============================================================
// RegistryDock
// Notes:
// - Left tree: Registry key hierarchy navigation.
// - Right table: list of values for the current key and search results.
// - All heavy operations (search/import/export) are executed on a background thread.
// ============================================================
class RegistryDock final : public QWidget
{
    Q_OBJECT

public:
    // Constructor:
    // - Purpose: initialize UI, root key nodes, and signal-slot connections.
    // - Parameter parent: Qt parent widget.
    explicit RegistryDock(QWidget* parent = nullptr);

    // Destructor:
    // - Purpose: Safely stop the background search thread and refresh timer.
    ~RegistryDock() override;

private:
    // SearchOptions：
    // - Purpose: Encapsulate match scope options during search.
    struct SearchOptions
    {
        bool searchKeyName = true;      // Whether to match key names.
        bool searchValueName = true;    // Whether to match value names.
        bool searchValueData = true;    // Whether to match value data text.
        bool caseSensitive = false;     // Whether case-sensitive.
    };

    // PendingSearchRow：
    // - Purpose: UI row data pending flush, generated by the background search thread.
    struct PendingSearchRow
    {
        QString keyPathText;            // Full path of the matched key.
        QString valueNameText;          // Matched value name (may be empty if the key matched).
        QString rawValueName;           // The raw Win32 name of the value; defaults to an actual empty string.
        QString valueTypeText;          // Value type (Key when key hit).
        QString valueDataPreviewText;   // Value data preview.
        QString hitSourceText;          // Match source (KeyName/ValueName/ValueData).
        bool isKeyResult = false;       // Whether this is a key hit; false indicates a value hit.
    };

private:
    // ===================== UI Initialization =====================
    void initializeUi();
    void initializeConnections();
    void initializeRootItems();

    // ===================== Navigation and Refresh =====================
    void navigateToPath(const QString& registryPath, bool recordHistory);
    void refreshCurrentKey(bool keepSelection);
    void refreshValueTable();
    void updateStatusBar(const QString& messageText);
    void selectTreeItemByPath(const QString& registryPath);
    void ensureTreeItemLoaded(QTreeWidgetItem* item);

    // ===================== Right-Click Menu and Editing =====================
    void showTreeContextMenu(const QPoint& localPos);
    void showValueContextMenu(const QPoint& localPos);
    void createSubKey();
    void createValue();
    void renameSelectedObject();
    void deleteSelectedObject();
    // deleteSearchResultValue：
    // - Purpose: Delete a registry value using the full key path and original value name saved in the search row.
    // - Note: Does not depend on the current tree selection; when the driver is available, deleteRegistryValueAny takes priority and executes in R0.
    void deleteSearchResultValue(const QString& keyPath, const QString& rawValueName);
    // deleteSearchResultKey：
    // - Purpose: Recursively delete a non-root registry key using the full key path saved in the search row.
    // - Note: When the current browsing location is within the target subtree, deletion reverts to the target parent key.
    void deleteSearchResultKey(const QString& keyPath);
    void editSelectedValue();
    void copyCurrentPathToClipboard();
    // copyCurrentKernelPathToClipboard：
    // - Purpose: Convert the current key path to \REGISTRY\... and write it to the clipboard.
    void copyCurrentKernelPathToClipboard();
    // copySelectedValueKernelPathToClipboard：
    // - Purpose: Convert the current value (or current key) path to \REGISTRY\... and write to clipboard.
    void copySelectedValueKernelPathToClipboard();
    // readSelectedValueByR0：
    // - Purpose: Read the currently selected registry value via the KswordARK driver.
    void readSelectedValueByR0();
    // readDefaultValueByR0：
    // - Purpose: Read the current key's default value via the KswordARK driver.
    void readDefaultValueByR0();
    // readRegistryValueByR0：
    // - Purpose: Internal public implementation; calls the R0 read-only IOCTL after receiving the value name.
    void readRegistryValueByR0(const QString& valueName);
    // refreshRegistryDriverModeIndicator：
    // - Purpose: Refresh the R0 registry read/write status indicator after the path bar.
    void refreshRegistryDriverModeIndicator();
    // shouldUseRegistryR0：
    // - Purpose: Determine whether the current registry page should prioritize using driver-based read/write operations.
    bool shouldUseRegistryR0() const;
    // readRegistryValueAny：
    // - Purpose: If R0 is online, use the driver; otherwise, fall back to Win32 to read the specified value.
    bool readRegistryValueAny(
        const QString& keyPath,
        const QString& valueName,
        DWORD* typeOut,
        QByteArray* dataOut,
        QString* errorTextOut);
    // writeRegistryValueAny：
    // - Purpose: If R0 is online, use the driver; otherwise, fall back to Win32 to write the specified value.
    bool writeRegistryValueAny(
        const QString& keyPath,
        const QString& valueName,
        DWORD valueType,
        const QByteArray& rawData,
        QString* errorTextOut);
    // createRegistryKeyAny：
    // - Purpose: Use driver when R0 is online; otherwise fall back to Win32 for key creation.
    bool createRegistryKeyAny(const QString& fullKeyPath, QString* errorTextOut);
    // deleteRegistryKeyAny：
    // - Purpose: If R0 is online, recursively delete via the driver; otherwise, fall back to Win32 tree deletion.
    bool deleteRegistryKeyAny(const QString& fullKeyPath, QString* errorTextOut);
    // deleteRegistryValueAny：
    // - Purpose: Use driver when R0 is online; otherwise fall back to Win32 for value deletion.
    bool deleteRegistryValueAny(
        const QString& keyPath,
        const QString& valueName,
        QString* errorTextOut);
    // renameRegistryValueAny：
    // - Functionality: When R0 is online, use the driver; otherwise, use Win32 read/write/delete to complete the value rename.
    bool renameRegistryValueAny(
        const QString& keyPath,
        const QString& oldValueName,
        const QString& newValueName,
        QString* errorTextOut);
    // renameRegistryKeyAny：
    // - Purpose: If R0 is online, use the driver; otherwise, call the system RegRenameKey.
    bool renameRegistryKeyAny(
        const QString& fullKeyPath,
        const QString& newKeyName,
        QString* newFullKeyPathOut,
        QString* errorTextOut);
    // deleteRegistryKeyByR0Recursive：
    // - Purpose: Uses driver enumeration and deletion only to recursively delete non-empty registry keys.
    bool deleteRegistryKeyByR0Recursive(
        const QString& kernelKeyPath,
        QString* errorTextOut) const;

    // ===================== Import/Export =====================
    void exportCurrentKeyAsync();
    void importRegFileAsync();

    // ===================== Search Capabilities =====================
    void startSearchAsync();
    void stopSearch(bool waitForThread);
    void flushPendingSearchRows();
    void enqueuePendingSearchRow(PendingSearchRow&& row);
    void searchRegistryRecursive(
        HKEY rootKey,
        const QString& subPath,
        const QString& keyword,
        const SearchOptions& options,
        std::size_t* scannedKeyCount,
        std::size_t* hitCount);
    // searchRegistryRecursiveByR0：
    // - Purpose: When R0 is online, perform background enumeration via the driver to avoid routing the search path back to Win32.
    void searchRegistryRecursiveByR0(
        const QString& kernelKeyPath,
        const QString& displayKeyPath,
        const QString& keyword,
        const SearchOptions& options,
        std::size_t* scannedKeyCount,
        std::size_t* hitCount);

    // ===================== WinAPI utilities =====================
    static bool parseRegistryPath(const QString& pathText, HKEY* rootKeyOut, QString* subPathOut);
    static QString normalizeRegistryPath(const QString& pathText);
    static QString rootKeyToText(HKEY rootKey);
    static QString valueTypeToText(DWORD valueType);
    static QString formatValueData(DWORD valueType, const QByteArray& valueData);
    static bool writeRegistryValue(
        HKEY rootKey,
        const QString& subPath,
        const QString& valueName,
        DWORD valueType,
        const QByteArray& rawData,
        QString* errorTextOut);
    static bool readRegistryValueRaw(
        HKEY rootKey,
        const QString& subPath,
        const QString& valueName,
        DWORD* valueTypeOut,
        QByteArray* rawDataOut,
        QString* errorTextOut);
    static QString winErrorText(LONG errorCode);

private:
    // ===================== Top-level Layout =====================
    QVBoxLayout* rootLayout_ = nullptr;         // Root layout.
    QTabWidget* registryTabWidget_ = nullptr;   // Top-level Registry Dock tab (editing/system optimization).
    QWidget* registryEditorPage_ = nullptr;     // Existing registry editor page container.
    QVBoxLayout* registryEditorLayout_ = nullptr; // Internal layout of the registry editor page.
    RegistryOptimizationPage* optimizationPage_ = nullptr; // JSON driver system optimization page.
    QWidget* toolBarWidget_ = nullptr;          // Top toolbar container.
    QHBoxLayout* toolBarLayout_ = nullptr;      // Top toolbar layout.

    // ===================== Top Controls =====================
    QPushButton* backButton_ = nullptr;         // Back navigation button.
    QPushButton* forwardButton_ = nullptr;      // Forward navigation button.
    QPushButton* refreshButton_ = nullptr;      // Refresh button.
    QPushButton* newKeyButton_ = nullptr;       // New key button.
    QPushButton* newValueButton_ = nullptr;     // New value button.
    QPushButton* renameButton_ = nullptr;       // Rename button.
    QPushButton* deleteButton_ = nullptr;       // Delete button.
    QPushButton* importButton_ = nullptr;       // Import .reg button.
    QPushButton* exportButton_ = nullptr;       // Export .reg button.
    QPushButton* searchButton_ = nullptr;       // Start search button.
    QPushButton* stopSearchButton_ = nullptr;   // Stop search button.
    QLineEdit* pathEdit_ = nullptr;             // Path input field.
    QLabel* driverRegistryModeLabel_ = nullptr; // R0 registry read/write status indicator.
    QLineEdit* searchEdit_ = nullptr;           // Search keyword input field.

    // ===================== Main area =====================
    QSplitter* mainSplitter_ = nullptr;         // Left-right splitter.
    QTreeWidget* keyTree_ = nullptr;            // Registry key tree.
    QTabWidget* rightTabWidget_ = nullptr;      // Right-side Tab (values/search results).
    QTableWidget* valueTable_ = nullptr;        // Current key-value list.
    QTableWidget* searchResultTable_ = nullptr; // Search result table.

    // ===================== Status Bar =====================
    QStatusBar* statusBar_ = nullptr;           // Status bar.
    QLabel* pathStatusLabel_ = nullptr;         // Current path text.
    QLabel* summaryStatusLabel_ = nullptr;      // Summary status text.

    // ===================== Navigation Status =====================
    QString currentPath_;                       // Currently selected registry path.
    std::vector<QString> navigationHistory_;    // Navigation history.
    int navigationIndex_ = -1;                  // Current history index.

    // ===================== Search Thread Status =====================
    std::atomic_bool searchRunning_{ false };   // Whether the search thread is running.
    std::atomic_bool searchStopFlag_{ false };  // Flag to stop the search thread.
    std::unique_ptr<std::thread> searchThread_; // Search thread object.
    std::mutex pendingMutex_;                   // Lock for pending search result queue to be flushed.
    std::deque<PendingSearchRow> pendingRows_;  // Bounded FIFO queue for pending search results to be flushed.
    QTimer* searchFlushTimer_ = nullptr;        // UI throttled refresh timer.

    // ===================== Progress and Statistics =====================
    int progressPid_ = 0;                       // Progress bar task PID.
    std::size_t searchScannedKeys_ = 0;         // Count of scanned keys during search.
    std::size_t searchHitCount_ = 0;            // Search hit count statistics.
};
